// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a repair did.
 *
 * **Internally tagged**, so a client matches on a word rather than working out which fields
 * arrived.
 */
export type Action = { "action": "repaired", 
/**
 * What was done, in a sentence.
 */
what: string, } | { "action": "enqueued", 
/**
 * What is waiting, in a sentence.
 */
what: string, } | { "action": "untouched", 
/**
 * Why it was left, in a sentence. Never advice.
 */
because: string, };
