// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeKind } from "./RuntimeKind";
import type { ServiceId } from "./ServiceId";

/**
 * What a version question is about.
 *
 * **Tagged rather than a bare string.** `php` is a language and `mariadb@main` is an instance; one
 * string field holding both is one collision away from applying an answer to the wrong thing.
 *
 * A service question only ever arises for an instance that already exists, so its id is always
 * spellable — which is why this may carry a [`ServiceId`] where
 * [`PlanAction::EnsureService`](crate::PlanAction) deliberately carries the package and the
 * instance apart.
 *
 * **Closed, where most of this crate is `non_exhaustive`**, on [`ProjectRef`]'s rule: a client
 * sends this, so a variant nothing here handles would be a request the daemon has to guess at.
 * What a *client* must tolerate growing is the plan it is answering, and that is
 * [`PlanAction`](crate::PlanAction), which is open.
 */
export type AnswerSubject = { "subject": "runtime", 
/**
 * Which language.
 */
kind: RuntimeKind, } | { "subject": "service", 
/**
 * Which instance.
 */
id: ServiceId, };
