// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an extension says it would call on the daemon API.
 *
 * **A disclosure, not a boundary** — see
 * `.claude/decisions/0014-an-extension-is-not-an-api-client.md`. Nothing is minted and nothing
 * checks it: an extension runs as the user's own account, and the endpoint's access control *is*
 * the account, so a token an extension held is one it could ignore by opening its own connection.
 * What this is for is telling somebody what they are about to install.
 */
export type ApiAccess = "read" | "write";
