// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether an artifact is published for this machine.
 */
export type ArtifactAvailability = { "type": "published", 
/**
 * Where it comes from.
 */
url: string, 
/**
 * What it must hash to.
 */
sha256: string, } | { "type": "other_targets", 
/**
 * The targets it does publish for, in the manifest's own words.
 */
targets: Array<string>, } | { "type": "not_required" };
