// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutostartMechanism } from "./AutostartMechanism";

/**
 * What every `autostart.*` method answers.
 */
export type AutostartReport = { 
/**
 * Which mechanism this machine has.
 */
mechanism: AutostartMechanism, 
/**
 * Where a person would go and look: the task name, the plist path, the unit path.
 *
 * A string and not a `PathBuf` for [`DaemonStatus`](crate::DaemonStatus)' reason, and here it
 * is not always a path at all — on Windows it is a name in the Task Scheduler library, and on
 * a machine with no mechanism it is what was looked for and did not answer.
 */
location: string, 
/**
 * Whether the entry is registered as things stand.
 */
enabled: boolean, 
/**
 * Whether *this call* is what registered it or removed it.
 *
 * Always `false` from `autostart.status`. It is what lets a client say "already set up" rather
 * than claiming a write it did not perform — the two are indistinguishable to somebody reading
 * the output, and only one of them is true.
 */
changed: boolean, 
/**
 * What the registered entry will run, as its own words.
 *
 * Empty when nothing is registered. Read back off the machine rather than composed from what
 * would be written, which is the whole point of carrying it: an entry naming a `mixengined`
 * that has moved, or a home that is not this one, is the failure this field exists to be able
 * to report.
 */
command?: Array<string>, 
/**
 * Whether that command names *this* daemon's home.
 *
 * `false` when nothing is registered, and `false` when the entry belongs to another home. There
 * is one entry per user, so enabling from a second home replaces it, and "registered, but not
 * for you" is the half-state this exists to name. Composed by the daemon: a client folding it
 * itself would be business logic in a client, and a place for two clients to disagree about
 * whose entry it is.
 */
for_this_home: boolean, };
