// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How this machine starts something at login, if it does.
 */
export type AutostartMechanism = "logon_task" | "launch_agent" | "systemd_user" | "none";
