// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Millis } from "./Millis";

/**
 * How long to wait between restart attempts.
 *
 * Exponential with a ceiling and a random spread, so a service whose dependency is down does not
 * retry in a tight loop and several restarting at once do not synchronise.
 */
export type Backoff = { 
/**
 * The wait before the first retry.
 */
initial: Millis, 
/**
 * The longest wait, however many retries have happened.
 */
max: Millis, 
/**
 * What each wait is multiplied by, as a percentage: `200` doubles it.
 *
 * An integer percentage rather than an `f64` because this type is compared and hashed like
 * everything else in this crate, and because a `NaN` multiplier arriving from a hand-written
 * manifest should not be representable in the first place.
 */
multiplier_percent: number, 
/**
 * How much to spread each wait by, as a percentage of itself: `20` means ±20 %.
 *
 * Under 100, always. At 100 the low end of the spread is zero, which is the tight retry loop
 * the whole type exists to prevent — the same reason an `initial` of zero is refused.
 */
jitter_percent: number, };
