// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlueprintSource } from "./BlueprintSource";
import type { SignatureCheck } from "./SignatureCheck";

/**
 * One blueprint, as a listing shows it.
 */
export type BlueprintSummary = { 
/**
 * The handle: what a person types, what the row's primary key is, and the file's stem.
 */
slug: string, 
/**
 * The display name.
 *
 * Equal to [`Self::slug`] for a captured blueprint. The two are separate because the gallery
 * (T79) ships blueprints whose title is not a handle, and one column serving both would have
 * to pick which of the two it lies about.
 */
name: string, 
/**
 * What it is for, or empty.
 */
description: string, 
/**
 * When it was captured, ISO-8601 UTC.
 */
created_at: string, 
/**
 * Where it came from.
 */
source: BlueprintSource, 
/**
 * Whether this build will offer to run the blueprint's own `[scaffold]` command — roadmap task
 * **T78a**, its design's D1.
 *
 * Decided once, by whatever wrote the row: this build's own gallery and this machine's own
 * captures are trusted, and a blueprint somebody handed over earns it only from a signature
 * that verified against the gallery key. **Nothing raises it afterwards**, which is what
 * "untrusted for good" means when it is a column rather than a promise.
 *
 * Defaulted, so a record written before this task reads as untrusted — the direction a missing
 * answer should fall in.
 */
trusted: boolean, 
/**
 * Why [`Self::trusted`] says what it says — roadmap task **T79b**.
 *
 * [`None`] where no signature was ever looked for — this build's own gallery and this
 * machine's own captures — and for a row written before this task, whose reason the schema
 * never recorded. Absent rather than guessed: an untrusted import from before this column is
 * *either* of the two, and the answer to which is not on disk anywhere.
 *
 * **A record of what arrived, and never a claim about the file on disk now** (the design's
 * D10). The rendering beside the row is not the artifact that was signed, and nothing
 * re-checks it — T78a's D16, which is also why trust is a column and not a promise.
 */
signature?: SignatureCheck | null, 
/**
 * The rendered file.
 *
 * Carried in the listing so that reading the TOML needs no `blueprint.get`: the row is the
 * truth and this file is its rendering (D7), so pointing at it is the whole of what a
 * "show me" method would have done.
 */
file: string, };
