// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlueprintPlan } from "./BlueprintPlan";
import type { JobSummary } from "./JobSummary";

/**
 * What `blueprint.apply` answers.
 *
 * **One method, two answers** — T77 argued the single method, because the plan a person reads and
 * the plan the daemon carries out have to be the same list. A tagged union is what lets that
 * survive execution arriving: a client reads which answer it got from the object rather than
 * inferring it from its own request.
 */
export type BlueprintApplyResponse = { "outcome": "planned", 
/**
 * The plan.
 */
plan: BlueprintPlan, } | { "outcome": "started", 
/**
 * The job, as [`JOB_STATUS`](crate::rpc::method::JOB_STATUS) would answer it.
 */
job: JobSummary, };
