// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectRef } from "./ProjectRef";

/**
 * `blueprint.capture` — write down what a project is made of.
 */
export type BlueprintCapture = { 
/**
 * Which project. The CLI fills this from the current directory when nobody named one.
 */
project: ProjectRef, 
/**
 * The slug to file it under, which becomes the row's key and the rendered file's stem.
 */
name: string, 
/**
 * What it is for.
 */
description?: string | null, 
/**
 * Whether to replace a blueprint already filed under this slug.
 *
 * Refusing by default is what stops a second capture quietly overwriting the first. There is
 * no `blueprint.delete` in this build, so without this flag a mistyped name would be
 * permanent — which is a worse default than asking.
 */
overwrite: boolean, };
