// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlueprintSummary } from "./BlueprintSummary";

/**
 * What `blueprint.list` answers.
 */
export type BlueprintList = { 
/**
 * Every blueprint this home holds, in slug order.
 */
blueprints: Array<BlueprintSummary>, };
