// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `blueprint.import` — take in a blueprint somebody else wrote.
 *
 * **The only thing in this build that can produce [`BlueprintSource::Imported`]**, and therefore
 * the only thing that can produce an untrusted one — roadmap task **T78a**, its design's D3. A
 * capture is this machine's own and the gallery is this build's own; everything else arrives
 * through here, and what it arrives with decides whether its `[scaffold]` will ever be offered.
 *
 * [`BlueprintSource::Imported`]: crate::BlueprintSource
 */
export type BlueprintImport = { 
/**
 * The manifest to read. Absolute; the client resolves it against its own current directory,
 * as every other path in this API is resolved.
 */
path: string, 
/**
 * A detached minisign signature to check it against.
 *
 * [`None`] looks for `<path>.minisig` — the name minisign gives it, so somebody handed a
 * signed pair has it on disk already — and uses that if it is there.
 *
 * **A signature that does not verify is not a refusal**: the blueprint lands untrusted. A file
 * whose signature is stale is still a file its owner may want, and saying so is more use than
 * throwing it away.
 */
signature?: string | null, 
/**
 * The slug to file it under. [`None`] takes the **file's own stem**, which is how every
 * rendering this product writes carries its name — `[blueprint] name` is display text and may
 * be spelled the way a person would say it.
 */
name?: string | null, 
/**
 * Whether to replace a blueprint already filed under that slug.
 *
 * Refusing by default for [`BlueprintCapture::overwrite`]'s reason, and one more of this
 * task's own: replacing a signed blueprint with an unsigned one is how a trusted row would
 * become an untrusted one, and that is a thing to ask about rather than do quietly.
 */
overwrite: boolean, };
