// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlueprintSource } from "./BlueprintSource";
import type { PlanStep } from "./PlanStep";
import type { SignatureCheck } from "./SignatureCheck";

/**
 * What applying a blueprint would do, decided before anything happens.
 */
export type BlueprintPlan = { 
/**
 * Which blueprint, by slug.
 */
blueprint: string, 
/**
 * The name the new project would have, which is also what `{project}` was expanded to.
 */
project: string, 
/**
 * Where it would live.
 */
root: string, 
/**
 * Every action, in the order it would be carried out.
 */
steps: Array<PlanStep>, 
/**
 * Where the blueprint being applied came from — roadmap task **T78a**, its design's D5.
 *
 * Defaulted, so a plan encoded before this task still decodes as what it was: something this
 * machine captured.
 */
source: BlueprintSource, 
/**
 * Whether this build will offer to run the blueprint's `[scaffold]` command.
 *
 * **Two facts rather than one**, because they are independent: a gallery file imported by hand
 * is [`BlueprintSource::Imported`] *and* trusted, and deriving either from the other would be a
 * build that lies about that case.
 *
 * Carried on the plan so that a client — this repository's `mix`, and the graphical one that is
 * not in it — shows the right words from the answer it already has, rather than making a second
 * call to find out who wrote the command it is about to offer.
 */
trusted: boolean, 
/**
 * Why [`Self::trusted`] says what it says — roadmap task **T79b**.
 *
 * Carried here as well as on [`BlueprintSummary`] because the `[scaffold]` question is where
 * it matters most: the moment somebody is asked to run a stranger's command is the moment
 * worth knowing that a signature came with this file and was not the gallery's.
 *
 * It changes what is *said* and nothing about what is allowed: one flag still answers for both
 * kinds of untrusted, and a signature that did not verify is still not a refusal (T78a's D3).
 */
signature?: SignatureCheck | null, };
