// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowserDatabase } from "./BrowserDatabase";

/**
 * What the browsers on this machine say about MixEngine's authority.
 *
 * **Four states, mirroring [`Trust`]'s** — and, as there, every branch that could not ask says why
 * rather than reporting `false`. A client renders what the daemon returns.
 */
export type Browsers = { "state": "reached", 
/**
 * One per database found.
 */
databases: Array<BrowserDatabase>, } | { "state": "no_tool", 
/**
 * In words, naming the package.
 */
because: string, } | { "state": "not_searched", 
/**
 * In words.
 */
because: string, } | { "state": "unknown", 
/**
 * What went wrong.
 */
because: string, };
