// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One NSS database, and whether it holds the authority.
 */
export type BrowserDatabase = { 
/**
 * The directory, so a person can go and look at it.
 */
path: string, 
/**
 * What put it there: `Firefox`, `Firefox (snap)`, `Chrome and Chromium`.
 *
 * **Which browser and not just which path**, because what a person does about a database that
 * lacks it is restart the browser that owns it.
 */
owner: string, 
/**
 * Whether it holds exactly this authority.
 */
installed: boolean, 
/**
 * Why not, or why this one could not be asked.
 */
because?: string | null, };
