// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Member } from "./Member";
import type { Omission } from "./Omission";
import type { Timestamp } from "./Timestamp";

/**
 * `daemon.bundle`'s answer.
 *
 * **The sizes are here and not in [`Manifest`].** The manifest is written last and cannot state its
 * own size from inside itself; rather than one member carrying a hole, the counts live where every
 * one of them is known — in the value the call returns, after the archive has been closed.
 */
export type BundleReport = { 
/**
 * Where it was written, absolute.
 */
path: string, 
/**
 * The finished archive's size on disk.
 */
bytes: number, 
/**
 * When it was taken.
 */
taken_at: Timestamp, 
/**
 * Each part that was written, and the bytes it contributed, in packing order.
 */
members: Array<Member>, 
/**
 * What was left out, and why.
 */
omitted: Array<Omission>, };
