// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Timestamp } from "./Timestamp";

/**
 * A certificate authority that exists and parses.
 */
export type Ca = { 
/**
 * The distinguished name, as X.509 spells it.
 */
subject: string, 
/**
 * SHA-256 of the certificate's DER, lowercase hex, no separators.
 *
 * **The number a browser shows and a trust store lists**, and therefore the only one a person
 * can compare against anything. Not the same value as [`key_id`](Self::key_id), and the T48
 * design's D1 is why there are two.
 */
fingerprint: string, 
/**
 * The first eight hex characters of the SHA-256 of the public key, which is what
 * [`subject`](Self::subject) ends with.
 *
 * A certificate cannot carry a hash of itself — the subject is inside the bytes the hash is
 * over — so the name is derived from the key instead. That also makes two certificates over
 * one key recognisable as one authority, which is what a rotation of the certificate alone
 * would produce.
 */
key_id: string, 
/**
 * When it starts being valid.
 */
not_before: Timestamp, 
/**
 * When it stops.
 */
not_after: Timestamp, 
/**
 * Whole days from now until [`not_after`](Self::not_after).
 *
 * **Signed, and allowed to be negative.** An expired authority is a true statement about a
 * certificate that exists and parses, not an unusable one: what it needs is rotation, which is
 * T54's and not this build's.
 */
days_left: number, 
/**
 * The certificate itself, PEM. The public half, and there is no field for the other one.
 */
certificate_pem: string, };
