// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ca } from "./Ca";
import type { CaStatus } from "./CaStatus";
import type { SiteCertOutcome } from "./SiteCertOutcome";

/**
 * What `cert.ca_rotate` did — roadmap task **T54**.
 */
export type CaRotateReport = { 
/**
 * The authority that was replaced.
 *
 * [`None`] for a home whose authority was damaged: [`CaState::Unusable`] carries no [`Ca`],
 * because there was nothing parseable to describe — and that is a state a rotation repairs
 * rather than refuses. It is also the one case where the old certificate is left in the trust
 * store, since nothing may be removed that cannot be named by key-id.
 */
previous?: Ca | null, 
/**
 * Where this home and this machine stand now, **measured after the grant rather than reported
 * by it**.
 *
 * The same [`CaStatus`] `cert.ca_status` answers, produced by the same code, so the two cannot
 * come to disagree about what reading a trust store means. A rotation that did not commit
 * reports the *old* authority here, because that is what is there.
 */
status: CaStatus, 
/**
 * One entry per site whose certificate was reissued, exactly `cert.issue`'s.
 *
 * Empty when nothing was committed. A rotation reissues through the call `mix cert issue`
 * already runs, because T50 made a leaf signed by a superseded authority unreusable — so there
 * is no second reissue path to keep in step with the first.
 */
sites: Array<SiteCertOutcome>, } & ({ "outcome": "rotated", } | { "outcome": "not_committed", 
/**
 * What the reading said, in words.
 */
because: string, } | { "outcome": "nothing_to_rotate", 
/**
 * Why not, and what to run instead.
 */
because: string, });
