// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `cert.ca_rotate` takes no options, and says so in a type — [`CaStatusQuery`]'s reasoning.
 */
export type CaRotateQuery = Record<symbol, never>;
