// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `cert.ca_status` takes no options, and says so in a type.
 *
 * An empty struct with `deny_unknown_fields` rather than no parameters at all: a caller who
 * misspells something is told, instead of being silently given the default — the reasoning T40
 * established for every parameterless method since.
 */
export type CaStatusQuery = Record<symbol, never>;
