// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ca } from "./Ca";
import type { Unusable } from "./Unusable";

/**
 * Whether this home has a usable certificate authority.
 *
 * **Internally tagged**, so a client matches on a word rather than working out which fields
 * arrived.
 */
export type CaState = { "state": "absent", } | { "state": "present", 
/**
 * What it is.
 */
ca: Ca, } | { "state": "unusable", 
/**
 * Which of the ways, as a name rather than a sentence.
 */
because: Unusable, };
