// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `cert.ca_uninstall` takes no options, and says so in a type.
 */
export type CaUninstallQuery = Record<symbol, never>;
