// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaStatus } from "./CaStatus";

/**
 * What `cert.ca_uninstall` did — roadmap task **T54**.
 */
export type CaUninstallReport = { 
/**
 * Where this machine stands now, measured after.
 *
 * **What is left is read here and stated nowhere else.** [`CaStatus::trust`] is
 * [`Trust::Installed`] when the system store still holds it, and [`CaStatus::browsers`] lists
 * each database and whether it does. A second field restating that would be a second answer
 * that can disagree with the first; [`UninstallOutcome`] carries the *reason*, which a
 * measurement genuinely cannot.
 */
status: CaStatus, } & ({ "outcome": "removed", } | { "outcome": "partly_removed", 
/**
 * Which store still holds it, and why it was not taken out.
 */
because: string, } | { "outcome": "nothing_to_remove", 
/**
 * Why not.
 */
because: string, });
