// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SiteRef } from "./SiteRef";

/**
 * `cert.issue` — give a site the certificate its names need, or every site one.
 *
 * **It names a site and never a list of domains.** `.claude/features/tls.md` specified
 * `{ domains }`; that would put in the client the decision of *what a certificate covers*, which is
 * business logic, and `.claude/CLAUDE.md`'s first rule is that a client only renders what the
 * daemon returns. The daemon reads the site's domains from its own rows.
 */
export type CertIssue = { 
/**
 * One site, or **every site with HTTPS declared** when it is absent.
 *
 * The absent form is what the daemon's own producer calls and what `mix cert issue` runs with
 * no argument, so the automatic path and the manual one are one piece of code.
 */
site?: SiteRef | null, };
