// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SiteRef } from "./SiteRef";

/**
 * What `cert.status` was asked about — roadmap task **T53**.
 */
export type CertStatusQuery = { 
/**
 * One site, by any of its domains. Every site when this is left out.
 */
site: SiteRef | null, };
