// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SiteCert } from "./SiteCert";
import type { Unusable } from "./Unusable";

/**
 * Whether a site has a usable certificate — roadmap task **T50**.
 *
 * **[`CaState`]'s vocabulary, reused deliberately.** The ways a key and a certificate on disk can
 * disagree do not depend on which of the two they are, so [`Unusable`] is the same closed enum
 * rather than a second one that would drift from it.
 */
export type CertState = { "state": "absent", } | { "state": "present", 
/**
 * What it is.
 */
cert: SiteCert, } | { "state": "unusable", 
/**
 * Which of the ways, as a name rather than a sentence.
 */
because: Unusable, };
