// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SiteCertOutcome } from "./SiteCertOutcome";

/**
 * What `cert.issue` did, per site.
 */
export type CertIssueReport = { 
/**
 * One entry per site considered, in primary-domain order.
 */
sites: Array<SiteCertOutcome>, };
