// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SiteCertStatus } from "./SiteCertStatus";

/**
 * What this home's certificates are doing — roadmap task **T53**.
 */
export type CertStatusReport = { 
/**
 * One entry per site considered, in primary-domain order.
 */
sites: Array<SiteCertStatus>, };
