// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A condition of one site's certificate — roadmap task **T53**.
 *
 * **A name for a condition rather than advice**, which is [`ProblemId`](crate::ProblemId)'s own
 * words about itself and holds here unchanged: `mix` renders the command to run and a graphical
 * client renders a button. A daemon that answered with the command string would be sending a GUI
 * a sentence telling its user to open a terminal.
 *
 * **Not [`ProblemId`](crate::ProblemId) itself.** Those name conditions of the *machine* that `mix
 * doctor` repairs, and merging would mean every one of these needs an entry in the daemon's repair
 * table — while [`Self::ServedCertificateDiffers`] is repaired by reloading a front end rather
 * than by touching a certificate at all.
 */
export type CertProblem = "no_certificate" | "names_differ" | "not_served" | "served_certificate_differs" | "not_trusted" | "expiring";
