// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Outcome } from "./Outcome";

/**
 * One thing examined.
 */
export type Check = { 
/**
 * What was examined, phrased for a person: "the managed hosts block".
 */
name: string, 
/**
 * What was found.
 */
outcome: Outcome, };
