// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where in **this repository's own source** a panic was raised.
 *
 * [`file`](Self::file) is `std::panic::Location::file`, which is the path as it was written in the
 * source tree — `crates/mixengine-daemon/src/…` — and is a `&'static str` baked into the binary
 * rather than a directory on anybody's disk.
 */
export type CrashLocation = { 
/**
 * The source file, as this repository spells it.
 */
file: string, 
/**
 * The line.
 */
line: number, 
/**
 * The column.
 */
column: number, };
