// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CrashLocation } from "./CrashLocation";
import type { DaemonVersion } from "./DaemonVersion";
import type { Timestamp } from "./Timestamp";

/**
 * One panic, as much of it as may travel.
 */
export type CrashReport = { 
/**
 * [`CRASH_FORMAT`].
 */
format: number, 
/**
 * When the hook ran, which is within microseconds of the panic.
 */
recorded_at: Timestamp, 
/**
 * What was running, and what it spoke.
 */
daemon: DaemonVersion, 
/**
 * `std::env::consts::OS`.
 */
os: string, 
/**
 * `std::env::consts::ARCH`.
 */
arch: string, 
/**
 * The panicking thread's name, or [`None`] when it had none.
 *
 * Every thread name reachable here is a literal from `std` or `tokio` — nothing in this
 * workspace names a thread — so this is one of the three safe kinds of field the module header
 * lists rather than an exception to them.
 */
thread?: string | null, 
/**
 * Where it was raised, or [`None`] when `std` reported none.
 */
location?: CrashLocation | null, 
/**
 * The backtrace, as symbol names alone.
 *
 * **Symbol names and nothing else**: the `at <path>:<line>` lines a rendered backtrace carries
 * are the one place a build machine's directories appear, and they are dropped before a report
 * is built. Empty is an ordinary answer rather than a failure — a stripped build on a system
 * with no unwind tables has a location and no frames, which is still most of what a reader
 * needs.
 */
frames: Array<string>, };
