// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobFinish } from "./JobFinish";
import type { JobProgress } from "./JobProgress";
import type { PendingOp } from "./PendingOp";
import type { ServiceTransition } from "./ServiceTransition";
import type { SharingChange } from "./SharingChange";
import type { SiteSharing } from "./SiteSharing";

/**
 * One message on the event stream.
 *
 * Internally tagged, so the discriminator travels inside the JSON object rather than in the SSE
 * `event:` line. That gives the GUI one `onmessage` handler that switches on `type` instead of one
 * `addEventListener` per variant — and it means a variant added in a later phase reaches an older
 * client as an object it can recognise and ignore, rather than as an event type it never
 * subscribed to and silently never sees.
 * **Not [`Eq`], since T22.** [`JobOutcome::Succeeded`](crate::JobOutcome) carries a
 * [`serde_json::Value`], whose float variant has no total equality — and the payload of a job is
 * the one thing on this stream whose shape belongs to the method that produced it rather than to
 * this crate. [`PartialEq`] is what tests compare with anyway.
 */
export type DaemonEvent = { "type": "resync", 
/**
 * How many messages this receiver missed. For a log line, not for logic — the answer to a
 * resync is the same whether one was dropped or a thousand.
 */
missed: number, } | { "type": "service_state_changed" } & ServiceTransition | { "type": "elevation_required", 
/**
 * Everything waiting, oldest first.
 */
pending: Array<PendingOp>, } | { "type": "job_progress" } & JobProgress | { "type": "job_finished" } & JobFinish | { "type": "cert_expiring", 
/**
 * The site, by its primary domain.
 */
domain: string, 
/**
 * Why the renewal did not happen, in words.
 */
because: string, } | { "type": "site_sharing_changed", 
/**
 * The site, by its primary domain.
 */
domain: string, 
/**
 * What it is now, or [`None`] for a site no longer shared.
 */
sharing: SiteSharing | null, 
/**
 * Why it changed.
 */
because: SharingChange, } | { "type": "update_available", 
/**
 * The version that is waiting.
 */
version: string, 
/**
 * When it was published, as `YYYY-MM-DDTHH:MM:SSZ`.
 */
published_at: string, };
