// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Error } from "./Error";
import type { ServiceWalk } from "./ServiceWalk";

/**
 * What a `daemon.shutdown` did on its way out.
 *
 * **The answer arrives before the daemon does go, and after everything it stopped has stopped.**
 * That ordering is the whole reason this type has anything in it: a client told only "accepted"
 * would have to re-derive from the event stream whether the database it cares about was flushed or
 * killed, which is the business-logic-in-a-client bug `CLAUDE.md` forbids. The connection is closed
 * by the daemon exiting a moment later, which a client reads as the shutdown having happened rather
 * than as a request that failed.
 *
 * A struct rather than a bare [`ServiceWalk`] so that what a shutdown reports can grow — which it
 * since has: [`DaemonShutdown::unordered`] arrived beside the walk rather than as a shape every
 * client had to decode a second way.
 */
export type DaemonShutdown = { 
/**
 * Stopping every supervised service, in reverse dependency order.
 *
 * [`ServiceWalk::failed`] here is what T18 made possible and nothing else: a process that
 * outlived a previous daemon, was adopted by this one, and would not die. **The daemon stops
 * anyway** — refusing to shut down because something will not is a machine with no way out of
 * the situation — and the next daemon meets that survivor as the crash recovery it already
 * performs on every boot. Whoever asked is told, which is the point.
 */
services: ServiceWalk, 
/**
 * Why there was no order to stop them in, on the shutdown where there was none.
 *
 * **The reporting half of T9a's "it is reported, the ordered walk is skipped".** A daemon that
 * cannot say what it declares — an `extension.toml` somebody is in the middle of editing —
 * still stops, because refusing over a half-typed file would leave them a daemon they can only
 * kill. What stops the services then is the root token, all at once, the way a signal would
 * have: each still stops the way its own spec asks, and what is lost is the *order* — a site is
 * no longer guaranteed to go before the database it is serving requests against.
 *
 * Without this field that walk goes out empty and [`complete`](ServiceWalk::complete), which on
 * the wire is **indistinguishable from a home that declares no services at all** — so a client
 * could only say `mixengined is stopping`, and could not say that the ordering the whole method
 * exists for did not happen. A client cannot work that out for itself from an answer the daemon
 * never sent, which is the business-logic-in-a-client bug `CLAUDE.md` forbids, arriving from
 * the side a client cannot fix.
 *
 * The wire [`Error`] and not a vocabulary of its own, because this is the same failure the same
 * declarations hand `service.list` — the same code, the same message, the same hint about where
 * services are written down — and a second spelling of it would be a second thing to keep in
 * step with whatever T30's generator can fail with.
 *
 * [`None`] is every ordinary shutdown, and it is absent from the wire rather than `null`: a
 * daemon built before this field answers byte for byte what one that walked the plan in order
 * answers now, so neither side of a version skew has to special-case the other.
 */
unordered?: Error | null, };
