// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProtocolVersion } from "./ProtocolVersion";

/**
 * The cheap half of [`DaemonStatus`], for `daemon.version`.
 *
 * Its own method because a client asks this before it can safely ask anything else — a daemon from
 * another release may answer `daemon.status` with fields this client cannot decode, and finding
 * that out by failing to parse the answer is worse than asking first.
 */
export type DaemonVersion = { 
/**
 * The daemon's build version.
 */
version: string, 
/**
 * The API version it speaks.
 */
protocol: ProtocolVersion, };
