// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceId } from "./ServiceId";

/**
 * `database.client` — where one instance could be opened, and with what. Reads only.
 */
export type DatabaseClientQuery = { 
/**
 * Which instance: `mariadb@main`, `redis@main`.
 */
service: ServiceId, };
