// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Provisioned } from "./Provisioned";
import type { SecretAddress } from "./SecretAddress";
import type { ServiceId } from "./ServiceId";

/**
 * A database and the account that reaches it, as `database.create` answers.
 */
export type DatabaseAccount = { 
/**
 * Which instance holds it.
 */
service: ServiceId, 
/**
 * The database's name.
 */
database: string, 
/**
 * The account's name.
 */
user: string, 
/**
 * Where the account's password lives in this machine's credential store.
 *
 * **Never the password.** Derivable rather than secret — telling a caller the rule is what
 * makes a second method for looking one up unnecessary until T83 gives that a shape.
 *
 * **Both halves since roadmap task T84**: the namespace is part of the contract, so a client
 * renders the address without knowing any of MixEngine's constants.
 */
secret: SecretAddress, 
/**
 * What this call made, and what it found already there.
 */
made: Provisioned, };
