// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a database client speaks to one of our servers — roadmap task **T83**, the design's D5.
 *
 * **The recipe's answer, and a fact about the server.** MariaDB speaks MySQL's protocol whichever
 * client is on the other end, so `mariadb` and `mysql` are one word here. The word is what the
 * handoff URL carries as `kind`.
 */
export type DatabaseProtocol = "mysql" | "postgres" | "redis";
