// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceId } from "./ServiceId";

/**
 * `database.create` — make sure a database and an account for it exist on one instance.
 */
export type DatabaseCreate = { 
/**
 * Which instance: `mariadb@main`, `postgres@shop`.
 */
service: ServiceId, 
/**
 * The database's name.
 */
database: string, 
/**
 * The account's name. The database's own name when nobody says.
 */
user?: string | null, 
/**
 * A password the caller chose, rather than one MixEngine generates. Roadmap task **T77b**.
 *
 * Validated and never escaped: `mixengine_core::generate::databases::validated_password`
 * refuses everything that could end the quoted SQL literal it is interpolated into. Absent
 * (rather than empty) means *generate one*, which is what every caller built before this task
 * still asks for.
 */
password?: string | null, };
