// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceId } from "./ServiceId";

/**
 * `database.open` — hand one instance to the installed desktop client.
 */
export type DatabaseOpen = { 
/**
 * Which instance.
 */
service: ServiceId, 
/**
 * The account to sign in as. The server's administrator when nobody says.
 */
user?: string | null, 
/**
 * A database to open at, when the client should land in one.
 */
database?: string | null, };
