// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DatabaseProtocol } from "./DatabaseProtocol";
import type { DesktopClient } from "./DesktopClient";
import type { Launch } from "./Launch";
import type { SecretAddress } from "./SecretAddress";
import type { ServiceId } from "./ServiceId";

/**
 * `database.open`'s answer.
 *
 * **What is not here is the password**, exactly as [`DatabaseAccount`]: `secret` is the keyring
 * address it was read from, and the value went into one process's environment and nowhere else.
 */
export type DatabaseHandoff = { 
/**
 * Which instance.
 */
service: ServiceId, 
/**
 * What the client was told to speak.
 */
protocol: DatabaseProtocol, 
/**
 * The account it was signed in as. [`None`] for a server with no accounts.
 */
user?: string | null, 
/**
 * The database it was pointed at, when one was named.
 */
database?: string | null, 
/**
 * Where the password was read from. Never the password.
 *
 * Both halves since roadmap task **T84**, and the key half is also what the URL carries as
 * `secret_key` — so the connection the client saves can point at this entry instead of holding
 * a second copy of what is in it.
 */
secret?: SecretAddress | null, 
/**
 * The client, as it was found.
 */
client: DesktopClient, 
/**
 * What was started — present exactly when `client` is `installed`.
 */
launched?: Launch | null, };
