// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DatabaseProtocol } from "./DatabaseProtocol";
import type { DesktopClient } from "./DesktopClient";
import type { SecretAddress } from "./SecretAddress";
import type { ServiceId } from "./ServiceId";

/**
 * `database.client`'s answer: whether one service could be opened, and with what.
 */
export type DatabaseClientReport = { 
/**
 * Which instance.
 */
service: ServiceId, 
/**
 * What a client would speak to it, or [`None`] for a service no database client opens —
 * memcached, a front end, a pool. A state, not a refusal: `database.open` is what refuses.
 */
protocol?: DatabaseProtocol | null, 
/**
 * Where the administrator's password lives, for a server that has one — roadmap task **T84**.
 *
 * **Composed, never looked up.** This method starts nothing, opens nothing and touches the
 * credential store not at all — T83's D6, unchanged — because the address is what the recipe
 * and the service id say it is. That is what makes the convention *askable*: a client can draw
 * "stored in your credential store as …" beside the button without opening a database to find
 * out.
 *
 * [`None`] for a server with no accounts, and for a service no database client opens.
 */
secret?: SecretAddress | null, 
/**
 * Where it could be opened.
 */
client: DesktopClient, };
