// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionId } from "./ExtensionId";

/**
 * Where a database could be opened, as a state — roadmap task **T83**, the design's D3.
 *
 * **Three answers, and two of them are not errors.** A client renders `not_installed` and
 * `no_client` as an absent affordance with a sentence beside it; an error would be rendered as a
 * failure of something the person did.
 */
export type DesktopClient = { "state": "installed", 
/**
 * The extension.
 */
extension: ExtensionId, 
/**
 * Its display name — `MixDB`.
 */
name: string, 
/**
 * The executable this machine would start.
 */
program: string, } | { "state": "not_installed", 
/**
 * The extension.
 */
extension: ExtensionId, 
/**
 * Its display name.
 */
name: string, 
/**
 * Where this system looked, phrased for a person.
 */
searched: string, 
/**
 * Where to get it, when the manifest says.
 */
homepage?: string | null, } | { "state": "no_client" };
