// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a `desktop-app` would be opened with.
 */
export type DesktopAppSummary = { 
/**
 * The URL scheme a handoff is written to.
 */
scheme: string, 
/**
 * How this system would look for it, where the manifest says.
 *
 * **The hint, not the answer.** Locating an installed application is platform-layer work —
 * `database.client` asks it and answers a [`DesktopClient`](crate::DesktopClient) (T83); what
 * belongs in a manifest is the name each system looks it up by.
 */
detect: string | null, };
