// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a caller asks for.
 *
 * Empty, and a struct rather than no parameter at all, so that the first option to arrive is a
 * field and not an API change. The shape [`DoctorRepair`](crate::DoctorRepair) started with.
 */
export type DiagnosticsBundle = Record<symbol, never>;
