// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `daemon.disk_usage` takes.
 */
export type DiskUsageQuery = { 
/**
 * Walk the disk now rather than answering from the last reading.
 *
 * **Defaults to `false`**, and that default is the point. The dashboard this method exists for
 * holds the event stream open and re-reads whenever something changes; a walk of `runtimes/` is
 * tens of thousands of files, so an uncached reading would be a disk walk per event. The daemon
 * keeps the last one for a minute and [`DiskUsage::measured_at`] says how old it is, so a
 * client is never guessing. `mix disk` sends `true`: somebody who typed a command is asking
 * about now.
 */
refresh: boolean, };
