// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageVersion } from "./PackageVersion";
import type { VersionConstraint } from "./VersionConstraint";

/**
 * What this home makes of one action.
 */
export type Disposition = { "disposition": "satisfied" } | { "disposition": "create" } | { "disposition": "choice", 
/**
 * What this machine has, and would use if the answer were "use the installed one".
 */
installed: PackageVersion, 
/**
 * What the blueprint asks for.
 */
wanted: VersionConstraint, } | { "disposition": "confirm", 
/**
 * What they would be agreeing to.
 */
what: string, } | { "disposition": "blocked", 
/**
 * Why, in the words the CLI prints.
 */
reason: string, } | { "disposition": "unsupported", 
/**
 * Why.
 */
reason: string, };
