// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which mechanism a home's names resolve through.
 *
 * Closed rather than a string: a client renders a warning for one of these and not the other, and
 * a free-form value would make that a comparison against a spelling.
 */
export type DnsMode = "dns" | "hosts_only";
