// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DnsMode } from "./DnsMode";

/**
 * What this daemon's own DNS server is doing, and what it costs when it is not — roadmap task
 * **T44**, which also closes T46a.
 *
 * A home resolves its names one of two ways: through the built-in DNS server, which answers a
 * whole managed TLD by pattern, or through the hosts file, which has one line per name. The
 * difference is not a detail of implementation — it is whether `api.blog.test` works — so it is
 * reported rather than left for a client to work out.
 */
export type DnsStatus = { 
/**
 * Which mechanism is in use.
 */
mode: DnsMode, 
/**
 * Where the DNS server is answering, as `address:port`, or [`None`] when it is not.
 *
 * **Not the same question as [`DnsStatus::mode`]**, and that is the field's whole reason for
 * existing: a server can be listening perfectly while nothing on the machine sends it a name,
 * which is every machine until the resolver wiring of T45. A string for
 * [`DaemonStatus`]' reason — it is for reading, and nothing parses it back.
 */
listening: string | null, 
/**
 * The TLDs whose subdomains resolve — every name under one of these, at any depth.
 *
 * Empty in hosts-only mode, where it is the specific thing a user loses: a hosts file holds one
 * line per name and no patterns, so a subdomain nobody wrote down does not resolve. Stated here
 * rather than inferred from `mode`, because what a client renders is the loss and not the
 * mechanism.
 *
 * **A list rather than a `bool`, from T45 on.** While nothing could be wired, "does this home
 * have wildcards?" had one answer for the whole home. It no longer does: every mechanism there
 * is scopes to one TLD, and `.local` is deliberately never wired — so a home can perfectly well
 * answer `*.blog.test` by pattern and still need a hosts line for `shop.local`. A boolean would
 * have to say `true` and leave a client to work out which half of its sites it applies to,
 * which is the derivation this field exists to prevent.
 */
wildcards: Array<string>, 
/**
 * Why this home is not on DNS, phrased for a person, or [`None`] when it is.
 *
 * A sentence and not a code, on [`Error`]'s neighbouring precedent: the reasons are a port
 * somebody else is holding — named where this machine will name them — a key in `config.toml`,
 * and a resolver that has not been wired yet, and a vocabulary for them would be three
 * variants that every client would have to spell back out in English.
 */
because?: string | null, };
