// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Check } from "./Check";

/**
 * Everything `daemon.doctor` examined, and what each answered.
 */
export type DoctorReport = { 
/**
 * Every check this build knows how to make, in a fixed order, whatever each answered.
 *
 * **Fixed order and never filtered**: a check that found nothing wrong is the evidence that it
 * ran, and a shorter list on one operating system would read as a clean bill of health rather
 * than as a question nobody asked.
 */
checks: Array<Check>, };
