// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What to repair, and whether to raise the prompt.
 *
 * **`grant` exists because of T64**, not for symmetry: a person must be able to read what is about
 * to be allowed *before* it is allowed, and a call that enqueued and flushed in one step leaves no
 * moment for a client to show them. So the ordinary path is two calls — enqueue, show the batch,
 * then `elevation.grant` — and `grant: true` is for a caller that has already shown it and been
 * answered. `mix doctor --repair` takes the first path; `mix doctor --repair --yes` takes the
 * second.
 */
export type DoctorRepair = { 
/**
 * Flush the queue in this same call, raising the one prompt.
 *
 * **Defaults to false**, which is the safe direction: a caller that forgot the field gets the
 * path where somebody is shown the batch first.
 */
grant: boolean, };
