// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which names a diagnostic should answer about.
 */
export type DomainStatusQuery = { 
/**
 * One name, or every name this home declares.
 */
domain?: string | null, };
