// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Take one name away.
 *
 * **No site, and none to give.** `site_domains_domain` is `UNIQUE` — the index its own migration
 * calls "the one that decides ownership" — so a domain names its site. Asking a caller for it as
 * well would be asking for a fact the database holds, and would let them name a site the domain is
 * not on (T46 design, D2).
 */
export type DomainRemove = { 
/**
 * The name to take away.
 */
domain: string, };
