// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SiteRef } from "./SiteRef";

/**
 * Give a site one more name.
 */
export type DomainAdd = { 
/**
 * Which site gets it.
 */
site: SiteRef, 
/**
 * The name to add.
 *
 * **Never becomes the primary.** [`crate::SiteUpdate`] reorders and the head of that list is
 * the primary; a verb that says "add a domain" does not get to decide what a site *is* (T46
 * design, D3).
 */
domain: string, 
/**
 * `.local` is mDNS territory and is allowed only when the caller says they know.
 */
accept_risky_tld: boolean, };
