// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DomainStatus } from "./DomainStatus";

/**
 * What `domain.dns_status` answers.
 *
 * A report around the list rather than a bare `Vec`, on [`crate::SiteList`]'s precedent: the
 * one-domain and every-domain questions then have one answer shape, and a later field has somewhere
 * to go that is not inside every row.
 */
export type DomainStatusReport = { 
/**
 * One row per name asked about, in domain order.
 */
domains: Array<DomainStatus>, };
