// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PendingOpId } from "./PendingOpId";

/**
 * `elevation.drop` — forget one operation, or all of them.
 */
export type ElevationDrop = { 
/**
 * Which one. [`None`] is every one of them.
 *
 * `deny_unknown_fields` above is what keeps that safe: a client that misspells this field would
 * otherwise have asked to empty the queue and been obeyed.
 */
op: PendingOpId | null, };
