// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GrantOutcome } from "./GrantOutcome";
import type { InstalledHelper } from "./InstalledHelper";
import type { PendingOp } from "./PendingOp";

/**
 * `elevation.status`, and what `elevation.drop` leaves behind.
 */
export type ElevationStatus = { 
/**
 * As [`ElevationSummary::elevated`].
 */
elevated: boolean, 
/**
 * As [`ElevationSummary::can_prompt`].
 */
can_prompt: boolean, 
/**
 * Why not, when it cannot.
 *
 * On Linux this is the whole `pkexec` command to run by hand, which the platform layer built it
 * to be — dropping it would leave a person with "unavailable" and nothing to type. Absent
 * rather than `null` when there is nothing to say.
 */
reason?: string | null, 
/**
 * Where `mixengine-elevate` was found, when it was.
 *
 * A string and not a `PathBuf` for [`DaemonStatus`](crate::DaemonStatus)' reason: serde refuses
 * a `PathBuf` that is not valid UTF-8, and an oddly named directory is a reason to see it
 * spelled oddly rather than a reason for the call to fail.
 */
helper?: string | null, 
/**
 * What the installed helper turned out to be, when there is one and it answered — roadmap
 * task **T88a**.
 *
 * `default`, so a client built before this field existed still reads a newer daemon's answer.
 */
installed_helper?: InstalledHelper | null, 
/**
 * Everything waiting, oldest first.
 */
pending: Array<PendingOp>, 
/**
 * What the most recent grant did, **for as long as this daemon has been up**.
 *
 * Deliberately not persisted: the durable fact is the queue, and a stored "you declined once"
 * would outlive the reason it was true. A daemon that has just started answers [`None`], and
 * the pending list already says everything a client needs.
 */
last?: GrantOutcome | null, };
