// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The three facts `daemon.status` carries about elevation — the T40b design, D6.
 *
 * *Degraded* is not a field here and is not a column anywhere: it means
 * [`pending`](ElevationSummary::pending) is not zero, computed where it is asked for. A second
 * representation of one fact is a second thing that can be wrong, and this one would be wrong in
 * the worst direction — reporting a healthy machine that is missing its hosts entries.
 */
export type ElevationSummary = { 
/**
 * Is the **daemon itself** running with an administrative token?
 *
 * Reported rather than refused (D10): CI's Windows third runs the daemon suites under a full
 * token, and a hard refusal would turn one platform red for a reason that has nothing to do
 * with the code under test. What is worth saying about it is that every supervised service
 * inherits that token.
 */
elevated: boolean, 
/**
 * Could a prompt be raised on this machine? `Elevation::probe` and a helper that is there.
 */
can_prompt: boolean, 
/**
 * How many operations are waiting. Not zero means degraded.
 */
pending: number, };
