// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WhenExceeded } from "./WhenExceeded";

/**
 * What one field of a declared `ResourceLimits` actually does here.
 *
 * **Per field rather than one flag for the pair, and Linux is why.** systemd delegates a user
 * session's `memory` controller far more readily than its `cpu` controller, and which of the two
 * arrives has moved between releases — so a machine that caps memory and cannot cap CPU is an
 * ordinary machine, and a single flag could only describe it by lying about one of them.
 * **`#[non_exhaustive]` since T71a**, which is the first release to add a variant to it. A client
 * in another repository reads these values, and the honest thing to tell it is that the set of
 * answers a machine can give grows — the same promise [`StateReason`](crate::StateReason) has
 * always made.
 */
export type Enforcement = { "kind": "hard", 
/**
 * What the service sees at the cap.
 */
when: WhenExceeded, } | { "kind": "unsupported" } | { "kind": "unavailable", 
/**
 * Why not, phrased for a person: this is the line `mix doctor` prints.
 */
why: string, } | { "kind": "advisory", 
/**
 * Why there is no hard cap here, where that is something somebody could change.
 */
why: string | null, };
