// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One environment variable's value.
 *
 * **This is the type that keeps a password out of a spec.** MariaDB's generated root password lives
 * in the OS keyring; a spec names it and the supervisor resolves it through the platform `Keyring`
 * capability at the moment it builds the child's `Command`, so the value exists nowhere that is
 * persisted, serialised or logged.
 *
 * The shape is Kubernetes' `env.valueFrom.secretKeyRef` and systemd's `LoadCredential=`, both of
 * which exist because the obvious design leaks: `docker inspect` prints environment variables, and
 * so does `systemctl show`.
 *
 * **Written tagged, read tagged or bare.** The canonical form — what the daemon sends and what the
 * database stores — always carries `from`. Deserialisation additionally accepts a plain string as a
 * [`Literal`](EnvValue::Literal), because `TZ = "UTC"` is what an `extension.toml` author writes
 * and the tagged spelling buys nothing for the variant that names nothing. The same asymmetry
 * [`crate::Millis`] has, and for the same reason.
 */
export type EnvValue = { "from": "literal", 
/**
 * The value, exactly as the child will see it.
 */
value: string, } | { "from": "keyring", 
/**
 * The keyring service name the credential was stored under.
 */
service: string, 
/**
 * The account or key within it.
 */
key: string, };
