// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCode } from "./ErrorCode";

/**
 * What MixEngine adds to a JSON-RPC error: the stable code, and the way out where there is one.
 *
 * The message is *not* here — it is the standard `message` member one level up, and duplicating it
 * would put the same sentence on screen twice.
 */
export type ErrorData = { 
/**
 * The code from [`crate::Error`]. Branch on this.
 */
code: ErrorCode, 
/**
 * The suggested action, when there is one.
 */
hint?: string | null, };
