// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCode } from "./ErrorCode";

/**
 * A failure, as it crosses the wire.
 *
 * Built at the daemon boundary from a library error — see the mapping in `mixengine-daemon`, which
 * is the only place that decides a code and writes a hint. By the time one of these exists the
 * error chain has already been flattened into `message`, because a client is given one string and
 * cannot walk a `source()` it does not have.
 */
export type Error = { 
/**
 * What kind of failure this is. Stable; branch on this.
 */
code: ErrorCode, 
/**
 * What happened, phrased for the person reading it, causes included.
 *
 * Never parsed by a client and never guaranteed between releases.
 */
message: string, 
/**
 * What to do about it, when there is something to do.
 *
 * The GUI renders it as a suggested action next to the message
 * (`.claude/features/gui.md`), so it is advice and not a restatement: a hint that repeats the
 * message makes the same sentence appear twice on screen. `None` is the right answer whenever
 * the message already carries the way out.
 */
hint?: string | null, };
