// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What went wrong, in one word a program can branch on.
 *
 * A closed enum, unlike `mixengine_core::Error` and its neighbours, which are `#[non_exhaustive]`
 * so they can grow a variant without breaking their callers. The trade is deliberate and points
 * the other way here: a new code is a change to the API contract, so every `match` in the CLI, in
 * the GUI and in the daemon's own mapping should stop compiling until somebody has decided what it
 * means. Growth happens in the library enums; this list is the vocabulary they are translated
 * into.
 *
 * The set is the one in `.claude/architecture/daemon-and-ipc.md`; the strings are wire format and
 * never change.
 */
export type ErrorCode = "not_found" | "already_exists" | "invalid_argument" | "conflict" | "precondition_failed" | "port_in_use" | "privileged_required" | "unsupported_platform" | "dependency_missing" | "process_failed" | "io" | "internal";
