// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionOrigin } from "./ExtensionOrigin";

/**
 * Ask what installing something here would do.
 */
export type ExtensionPlanRequest = { 
/**
 * What to read.
 */
source: ExtensionOrigin, };
