// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactAvailability } from "./ArtifactAvailability";
import type { ExtensionId } from "./ExtensionId";
import type { ExtensionKind } from "./ExtensionKind";
import type { PackageVersion } from "./PackageVersion";

/**
 * One extension the registry publishes.
 */
export type ExtensionOffer = { 
/**
 * Its id.
 */
id: ExtensionId, 
/**
 * Its display name.
 */
name: string, 
/**
 * The published version.
 */
version: PackageVersion, 
/**
 * What it is.
 */
kind: ExtensionKind, 
/**
 * What it is for.
 */
description: string, 
/**
 * Whether this home already has it.
 */
installed: boolean, 
/**
 * Whether this machine has an artifact to install.
 */
artifact: ArtifactAvailability, };
