// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionId } from "./ExtensionId";
import type { ServiceId } from "./ServiceId";

/**
 * What an uninstall did.
 */
export type ExtensionRemoval = { 
/**
 * Which extension went.
 */
id: ExtensionId, 
/**
 * The service that went with it, where there was one.
 */
service: ServiceId | null, 
/**
 * The data directory that was **kept**, so a client can say where it still is.
 */
data_dir_kept: string | null, 
/**
 * The domain that was released with it, for a `web-app` — roadmap task **T81b**.
 */
site?: string | null, 
/**
 * The php-fpm pool that went with it, for a `web-app` — roadmap task **T82a**.
 *
 * Said rather than left to be discovered: a `web-app` runs on a pool of its own, and an
 * uninstall that removed a service without naming it would leave somebody comparing two
 * `mix service list` outputs to find out what happened.
 */
pool?: ServiceId | null, };
