// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceId } from "./ServiceId";

/**
 * An extension's identity: `mailpit`, `phpmyadmin`, `mixdb`.
 *
 * **A [`ServiceId`] with no instance.** It names a directory — `extensions/<id>/` — so every rule
 * a service id carries about directory names applies unchanged, down to the names Windows refuses;
 * a second charset check written out here would be a second place for `con` to slip through. And a
 * `service` extension's supervised process is named by this id, so holding the parsed [`ServiceId`]
 * means that conversion can never fail later, at a point where failing would be a surprise.
 *
 * `@` is refused on top: `mariadb@main` is one server among several, and there is one Mailpit.
 */
export type ExtensionId = ServiceId;
