// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionId } from "./ExtensionId";

/**
 * Name one installed extension — for `start` and `stop`.
 */
export type ExtensionTarget = { 
/**
 * Which one.
 */
id: ExtensionId, };
