// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who decided that an extension is on or off.
 *
 * The question is asked precisely when the answer is surprising, and *on because the build says so*
 * and *on because you turned it on* are different answers to why xdebug is loaded — the second is
 * somebody's own doing and survives a reinstall; the first moves with the build.
 */
export type ExtensionSource = "build_default" | "user";
