// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an extension *is*, which decides which tables its manifest may carry.
 */
export type ExtensionKind = "service" | "web-app" | "desktop-app" | "recipe";
