// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeExtension } from "./RuntimeExtension";

/**
 * Every extension one installed runtime has.
 */
export type ExtensionList = { 
/**
 * Compiled-in first, then loadable, each in name order.
 */
extensions: Array<RuntimeExtension>, };
