// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionId } from "./ExtensionId";

/**
 * Remove an installed extension.
 */
export type ExtensionUninstall = { 
/**
 * Which one.
 */
id: ExtensionId, 
/**
 * Whether to delete its data directory as well.
 *
 * **`false` is the answer a client sends when nobody said**, because this is the one thing an
 * uninstall cannot give back.
 */
delete_data: boolean, };
