// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionId } from "./ExtensionId";
import type { NetworkReach } from "./NetworkReach";
import type { PackageVersion } from "./PackageVersion";

/**
 * Agreement to install one extension, naming what was read.
 *
 * **It names what was shown rather than saying yes** — [`ScaffoldConsent`](crate::ScaffoldConsent)'s
 * shape, and for its reason: the registry can be refreshed between the plan somebody read and the
 * install they sent, and a consent naming the version and the reach they were shown is the only
 * kind that cannot be spent on a different one. Disagreement in either direction refuses the
 * install before anything is fetched.
 */
export type ExtensionConsent = { 
/**
 * The extension as it was shown.
 */
id: ExtensionId, 
/**
 * The version as it was shown.
 */
version: PackageVersion, 
/**
 * Whether the person was told nothing vouches for this.
 */
signed: boolean, 
/**
 * The reach they were shown.
 */
network: NetworkReach, };
