// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionId } from "./ExtensionId";
import type { ExtensionKind } from "./ExtensionKind";
import type { PackageVersion } from "./PackageVersion";
import type { PortWish } from "./PortWish";
import type { ServiceId } from "./ServiceId";

/**
 * One installed extension, as a listing shows it.
 */
export type ExtensionSummary = { 
/**
 * Its id.
 */
id: ExtensionId, 
/**
 * Its display name.
 */
name: string, 
/**
 * Its own version.
 */
version: PackageVersion, 
/**
 * What it is.
 */
kind: ExtensionKind, 
/**
 * Whether a signature covered it when it arrived.
 *
 * **Decided once, when it was installed**, exactly as a blueprint's trust is (T79b): this is a
 * record of what was checked, never a re-check.
 */
signed: boolean, 
/**
 * The service it runs as, where it runs one.
 */
service: ServiceId | null, 
/**
 * The ports it holds, by the name each was asked for under.
 */
ports: Array<PortWish>, 
/**
 * The domain it is served on, for a `web-app` — roadmap task **T81b**.
 */
site?: string | null, };
