// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PoolOutcome } from "./PoolOutcome";
import type { RuntimeExtension } from "./RuntimeExtension";

/**
 * What one `runtime.set_extension` did, and what it means for the pool.
 */
export type ExtensionChange = { 
/**
 * The extension, as it now stands.
 */
extension: RuntimeExtension, 
/**
 * Whether anything that was running heard about it.
 *
 * Carried rather than left to the client because a client guessing from the operating system it
 * happens to be running on is a client that prints a confident wrong sentence: which pools can
 * be handed a configuration is a property of the *recipe*, and only the daemon holds it.
 */
pool: PoolOutcome, };
