// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiAccess } from "./ApiAccess";
import type { FilesystemReach } from "./FilesystemReach";
import type { NetworkReach } from "./NetworkReach";

/**
 * `[permissions]`.
 */
export type ExtensionPermissions = { 
/**
 * What it says it would call. A disclosure — see [`ApiAccess`].
 */
services: Array<ApiAccess>, 
/**
 * How far its listeners reach. Enforced, through [`NetworkReach::listen_address`].
 */
network: NetworkReach, 
/**
 * Which paths it says it needs. `own-data` is enforced by the placeholder vocabulary itself.
 */
filesystem: Array<FilesystemReach>, };
