// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionOffer } from "./ExtensionOffer";

/**
 * What the registry publishes.
 */
export type ExtensionCatalogue = { 
/**
 * The entries this build can read.
 */
extensions: Array<ExtensionOffer>, 
/**
 * How many entries it could not — roadmap task **T81**, the design's D4.
 *
 * **Said rather than swallowed.** An extension missing from a listing is one somebody goes
 * looking for in the wrong place, and "your MixEngine is older than this entry" is an answer
 * nothing else can give them.
 */
unreadable: number, 
/**
 * Whether this came from a cache past its freshness because the network could not be reached.
 */
stale: boolean, };
