// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionConsent } from "./ExtensionConsent";
import type { ExtensionOrigin } from "./ExtensionOrigin";

/**
 * Install an extension.
 */
export type ExtensionInstall = { 
/**
 * What to install.
 */
source: ExtensionOrigin, 
/**
 * What the person agreed to, from the plan they were shown.
 */
consent: ExtensionConsent, };
