// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which manifest to read.
 */
export type ExtensionInspect = { 
/**
 * The directory holding `extension.toml`, or that file itself — because that is what a person
 * types.
 *
 * Absolute; the client resolves it against its own current directory, as every path in this
 * API is resolved. The daemon has no idea what directory a client is in, and reading a
 * relative path against its own would read the wrong file rather than fail.
 */
path: string, };
