// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionId } from "./ExtensionId";

/**
 * Where an install gets its manifest — roadmap task **T81**.
 *
 * **`ExtensionOrigin` and not `ExtensionSource`**: that name belongs to a *PHP* extension's
 * `runtime_api`, which is the same collision `php_extensions.rs` was renamed for in T80.
 */
export type ExtensionOrigin = { "type": "registry", 
/**
 * Which entry.
 */
id: ExtensionId, } | { "type": "path", 
/**
 * The directory holding `extension.toml`, or that file. Absolute, as every path in this
 * API is.
 */
path: string, };
