// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageVersion } from "./PackageVersion";
import type { RuntimeKind } from "./RuntimeKind";

/**
 * Which extension of which runtime to turn round.
 *
 * [`RuntimeTarget`] and two more fields, flattened so the wire spells the version exactly as every
 * other `runtime.*` call does. One name per call rather than a set: a refusal that named a whole
 * list would leave a client working out which half of its request happened.
 */
export type ExtensionChoice = { 
/**
 * Which extension, spelled as the index spells it.
 */
name: string, 
/**
 * Whether it is to be loaded.
 */
enabled: boolean, 
/**
 * Which language.
 */
kind: RuntimeKind, 
/**
 * Which version, exactly as the index publishes it.
 */
version: PackageVersion, };
