// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DesktopPresence } from "./DesktopPresence";
import type { ExtensionId } from "./ExtensionId";
import type { ExtensionKind } from "./ExtensionKind";
import type { ExtensionPermissions } from "./ExtensionPermissions";
import type { PackageVersion } from "./PackageVersion";
import type { PlannedSite } from "./PlannedSite";
import type { PortWish } from "./PortWish";

/**
 * What installing it here would do, and what a person is being asked to agree to.
 */
export type ExtensionPlan = { 
/**
 * Its id.
 */
id: ExtensionId, 
/**
 * Its display name.
 */
name: string, 
/**
 * Its own version.
 */
version: PackageVersion, 
/**
 * What it is.
 */
kind: ExtensionKind, 
/**
 * What it is for.
 */
description: string, 
/**
 * Where it is from, when the manifest says.
 *
 * **On the plan since roadmap task T84**: for a `desktop-app`, whose install may end with
 * *"go and get it"*, this is the sentence's object. The plan is where a person decides, and
 * *"where is this from"* is part of deciding for every other kind too.
 */
homepage?: string | null, 
/**
 * Whether a signature covered it. `false` for every `--path` install, and every surface that
 * renders this says so loudly.
 */
signed: boolean, 
/**
 * What it declares.
 *
 * **`services` is a disclosure and not a boundary** — see [`ApiAccess`](crate::ApiAccess) and
 * ADR 0014.
 */
permissions: ExtensionPermissions, 
/**
 * The ports it asks for. **Asked for, not held.**
 */
ports: Array<PortWish>, 
/**
 * Where its own files would go.
 */
install_dir: string, 
/**
 * Where what it writes would go — outside `install_dir`, so an uninstall can keep it.
 */
data_dir: string, 
/**
 * The site it would be served on, for a `web-app` — roadmap task **T81b**.
 */
site?: PlannedSite | null, 
/**
 * Whether the application is on this machine — for kind `desktop-app`, and [`None`] for every
 * other kind — roadmap task **T84**, the design's D2.
 *
 * Filled by the daemon rather than by `mixengine_core::extensions::install::plan`: it is a
 * question about this machine and not about the manifest, and nothing but a `desktop-app` pays
 * for the registry walk, the Spotlight query or the XDG walk that answers it.
 *
 * It is also what makes the `version` above readable. MixEngine does not install a
 * `desktop-app` and such an application updates itself, so the version is the *entry's* and
 * this field is the machine's; a surface that prints one prints both.
 */
client?: DesktopPresence | null, };
