// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactAvailability } from "./ArtifactAvailability";
import type { DesktopAppSummary } from "./DesktopAppSummary";
import type { ExtensionId } from "./ExtensionId";
import type { ExtensionKind } from "./ExtensionKind";
import type { ExtensionPermissions } from "./ExtensionPermissions";
import type { PackageVersion } from "./PackageVersion";
import type { PortWish } from "./PortWish";
import type { RecipeAddition } from "./RecipeAddition";
import type { ServiceSpec } from "./ServiceSpec";
import type { WebAppSummary } from "./WebAppSummary";

/**
 * What one manifest says, and what installing it here would produce.
 */
export type ExtensionInspection = { 
/**
 * Its id, which is also its directory and — for a `service` — its service.
 */
id: ExtensionId, 
/**
 * The display name.
 */
name: string, 
/**
 * Its own version, not MixEngine's.
 */
version: PackageVersion, 
/**
 * What it is.
 */
kind: ExtensionKind, 
/**
 * What it is for.
 */
description: string, 
/**
 * Where to read about it.
 */
homepage: string | null, 
/**
 * What it declares.
 *
 * **`services` is a disclosure and not a boundary** — see [`ApiAccess`](crate::ApiAccess) and
 * ADR 0014. `network` and `filesystem` are enforced by the manifest format itself.
 */
permissions: ExtensionPermissions, 
/**
 * Whether this machine has an artifact to install.
 */
artifact: ArtifactAvailability, 
/**
 * The ports it asked for. **Asked for, not held** — see [`PortWish`].
 */
ports: Array<PortWish>, 
/**
 * Where it would be installed.
 */
install_dir: string, 
/**
 * Where it would write.
 */
data_dir: string, 
/**
 * The spec that would run, for a `service`.
 *
 * The rendered thing rather than a description of it: every placeholder substituted, the
 * address decided by `permissions.network`, and put through `ServiceSpec`'s own checks. For
 * the three kinds with nothing to supervise this is [`None`], and no spec is invented to have
 * something to show.
 */
runs: ServiceSpec | null, 
/**
 * The site that would be generated, for a `web-app`.
 */
serves: WebAppSummary | null, 
/**
 * What would be opened, for a `desktop-app`.
 */
opens: DesktopAppSummary | null, 
/**
 * What it adds to generated configuration. May be non-empty for any kind — a `service` that
 * also carries a recipe is Mailpit, and is the ordinary case rather than the odd one.
 */
extends: Array<RecipeAddition>, };
