// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which paths an extension says it needs.
 */
export type FilesystemReach = "own-data" | "project-roots:read";
