// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How this machine is asked to route managed TLDs to MixEngine's own DNS server — the T45
 * design, D2 and D3.
 *
 * What ports this machine should have open for MixEngine — roadmap task **T74**.
 *
 * **Whole state, like [`ResolverPlan`] and [`PortAccessPlan`]**: the plan names every port that
 * should end up open, so a second request supersedes the first, "already done" is a comparison
 * rather than a judgement, and revoking is this same operation carrying an empty list. There is no
 * `FirewallRevoke` beside it for that reason.
 *
 * **And unlike [`ResolverPlan`], it carries no OS mechanism.** That type has one variant per
 * mechanism because the daemon reads which one this machine has — through `ResolverConfig`, in
 * `mixengine-platform`, which this crate sits below and cannot link to — before it plans. Nothing
 * reads the firewall: the daemon has no trait for it and never asks what rules exist, so the helper
 * picks
 * the mechanism itself — `netsh` on Windows, `ufw` or `firewalld` on Linux where one is active,
 * and nothing at all on macOS, whose application firewall needs no rule for a listening socket.
 * A field the helper does not need is a field it cannot validate.
 */
export type FirewallPlan = { 
/**
 * Every port that should be reachable from the local network, sorted and deduplicated.
 *
 * Empty is the revoke, and is valid. Each one is checked by the helper itself against rules it
 * can apply without a database — see `mixengine-elevate`'s own `firewall` module.
 */
ports: Array<number>, 
/**
 * What the rules are named, so they can be found and removed again.
 *
 * The helper refuses anything that does not begin [`FIREWALL_LABEL`], which is what stops a
 * compromised daemon from writing a rule MixEngine would never recognise as its own — and
 * therefore never clean up.
 */
label: string, };
