// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrontEndOutcome } from "./FrontEndOutcome";
import type { ServiceId } from "./ServiceId";

/**
 * What a switch did — roadmap task **T97**.
 *
 * **A measurement of the home afterwards, not a claim about what was attempted**, which is
 * [`UninstallReport`](crate::UninstallReport)'s shape and its reasoning: the interesting outcomes
 * here are the ones where the home ends up where it started, and a client has to be able to render
 * each of them as the outcome it is rather than as a failure with no detail.
 */
export type FrontEndReport = { 
/**
 * What the home was reached through when the call began, and [`None`] for a home that had no
 * front end at all.
 */
was?: ServiceId | null, 
/**
 * What it is reached through now. Equal to [`was`](Self::was) whenever nothing moved, and
 * [`None`] only where a switch failed and could not be undone.
 */
now?: ServiceId | null, 
/**
 * What happened, and why.
 */
outcome: FrontEndOutcome, 
/**
 * Whether the front end named by [`now`](Self::now) may bind 80 and 443 on this machine.
 *
 * **Read from the machine after the walk, whatever the outcome.** `false` is the degraded mode
 * of [ADR 0005] and not a failure of this call: a Linux home where nobody has granted
 * `cap_net_bind_service` has a front end that will not start, and it had one before this was
 * called too.
 *
 * [ADR 0005]: https://github.com/mixnz/mixengine/blob/master/.claude/decisions/0005-on-demand-elevation.md
 */
answering: boolean, 
/**
 * The old front end's data directory, kept where it was.
 *
 * `service.delete`'s rule — nothing about replacing a program says anything about wanting its
 * files gone — and named for its reason: a directory nobody was told about is a directory
 * nobody ever cleans up. [`None`] when there was none on disk.
 */
kept_data?: string | null, 
/**
 * What did not travel to the new row, one sentence each.
 *
 * **Settings measured against the program that is going**: an override written in one server's
 * configuration language, a ceiling, an idle policy. A silently dropped override is the failure
 * this member exists to prevent; a listed one is something a person can put back. Empty when
 * the old row carried none of them.
 */
not_carried: Array<string>, };
