// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which front end a `[[recipe.front_end]]` fragment is written for — roadmap task **T81c**.
 *
 * **It names a configuration language rather than merely selecting a file.** A Caddyfile and an
 * `nginx.conf` are two syntaxes, and they spell a path differently as well: `ngx_conf_read_token`
 * treats a backslash inside a quoted string as an escape, so `mixengine-core` forward-slashes a
 * path it substitutes into an nginx fragment and leaves one bound for a Caddyfile as this system
 * spells it. That choice is made from this value and from nothing else.
 */
export type FrontEndServer = "caddy" | "nginx";
