// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobId } from "./JobId";
import type { Timestamp } from "./Timestamp";

/**
 * What one grant did.
 */
export type GrantOutcome = { 
/**
 * The job that raised the prompt, so `job.status` can be asked about it afterwards.
 */
job: JobId, 
/**
 * When it ended.
 */
at: Timestamp, 
/**
 * How many operations came back done — applied, or already so.
 */
applied: number, 
/**
 * How many are still in the queue afterwards.
 *
 * Not `pending.len()` minus `applied`: an operation the OS refused for a reason of its own is
 * kept and one the helper refused is dropped, so the two numbers do not add up and pretending
 * they do would make a client compute a third that is wrong.
 */
still_pending: number, } & ({ "outcome": "completed" } | { "outcome": "declined" } | { "outcome": "unavailable", 
/**
 * What is missing, phrased for a user, with the manual command where one exists.
 */
reason: string, });
