// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SiteCert } from "./SiteCert";
import type { Verdict } from "./Verdict";

/**
 * What this home's front end presented when asked for a site over TLS — roadmap task **T53**.
 *
 * **The first answer in this crate that comes from a socket rather than from a file.** Everything
 * else said about a certificate here is read off disk and believed; this is what the running
 * server actually hands a client, which is the only thing a browser ever sees.
 */
export type Handshake = { "handshake": "not_asked", } | { "handshake": "not_served", 
/**
 * In words.
 */
because: string, } | { "handshake": "failed", 
/**
 * In words, from the TLS library.
 */
because: string, } | { "handshake": "presented", 
/**
 * Its leaf, described exactly as the file on disk is — by the same function, so that the
 * two are comparable by construction rather than by agreement.
 */
cert: SiteCert, 
/**
 * Whether it validates against this home's own authority.
 */
trust: Verdict, };
