// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthProbe } from "./HealthProbe";
import type { Millis } from "./Millis";

/**
 * *Is it still fine?* — polled periodically, only once ready.
 *
 * Failing it makes a service `Degraded`, not `Failed`: the process is alive and the distinction is
 * what the GUI shows in amber and what `mix doctor` explains.
 */
export type HealthCheck = { 
/**
 * What to ask.
 */
probe: HealthProbe, 
/**
 * How often to ask it.
 */
interval: Millis, 
/**
 * How long one probe may take before it counts as a failure.
 */
timeout: Millis, 
/**
 * Consecutive failures before `Running` becomes `Degraded`.
 *
 * More than one, always: a single missed probe during a checkpoint flush is not a sick service,
 * and a dashboard that flickers amber teaches people to ignore it.
 */
failures_before_degraded: number, 
/**
 * Consecutive successes before `Degraded` becomes `Running` again.
 */
successes_before_running: number, };
