// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProtocolVersion } from "./ProtocolVersion";

/**
 * The body of `GET /health`.
 *
 * Unauthenticated and deliberately trivial: its one job is to tell a client whether to autostart a
 * daemon (`.claude/architecture/daemon-and-ipc.md`), and it must stay answerable while everything
 * else is still coming up. The version rides along because it is free and saves the caller a second
 * round trip.
 */
export type Health = { 
/**
 * Always `true` — a daemon that could not answer this does not answer at all. A field rather
 * than an empty object so the body is self-describing in a log or a `curl`.
 */
ok: boolean, 
/**
 * The daemon's build version.
 */
version: string, 
/**
 * The API version it speaks.
 */
protocol: ProtocolVersion, };
