// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a candidate helper's *signed* trusted comment says it is — roadmap task **T88a**.
 *
 * **The only fact about a candidate that a compromised daemon cannot write.** minisign's global
 * signature covers the trusted comment, and `minisign-verify` hands it over only after the
 * signature has verified, so this is where "which version, for which machine" can travel without
 * being taken on trust.
 *
 * Parsed here rather than in either crate that checks a signature, so that the daemon's pre-check
 * and the elevated check read one grammar with one set of tests behind it.
 */
export type HelperStamp = { 
/**
 * The version the release published this helper as.
 */
version: string, 
/**
 * `windows`, `macos` or `linux`, as the update feed spells them.
 */
os: string, 
/**
 * `x86_64`, `aarch64`, or `universal` for the one macOS builds.
 */
arch: string, };
