// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `elevation.upgrade` did.
 */
export type HelperUpgradeOutcome = { "outcome": "staged" } | { "outcome": "up-to-date" } | { "outcome": "unsupported", 
/**
 * What replaces it instead.
 */
reason: string, } | { "outcome": "unavailable", 
/**
 * Which of them, in words.
 */
reason: string, };
