// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PendingOp } from "./PendingOp";

/**
 * `elevation.upgrade` — what fetching the published privileged helper did — roadmap task **T88a**.
 *
 * **It queues rather than prompts.** `elevation.grant` is deliberately the only door into an
 * elevation prompt, and a second one would be a second place two concurrent prompts could come
 * from. So this leaves a row and says which command applies it, which is the idiom every producer
 * in this product already follows — creating a site enqueues a hosts change and tells you to grant
 * it.
 */
export type HelperUpgrade = { 
/**
 * What is installed now, when the handshake could read it.
 */
installed?: string | null, 
/**
 * What the published release offers for this machine, when it offers one.
 */
offered?: string | null, 
/**
 * The queue afterwards, so a client prints what will be asked for without calling again.
 */
pending: Array<PendingOp>, } & ({ "outcome": "staged" } | { "outcome": "up-to-date" } | { "outcome": "unsupported", 
/**
 * What replaces it instead.
 */
reason: string, } | { "outcome": "unavailable", 
/**
 * Which of them, in words.
 */
reason: string, });
