// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One line of the managed block: a name, and the address it resolves to.
 *
 * The address is an [`IpAddr`] and not a string because the helper refuses anything that is not
 * loopback, and a refusal that had to parse the field first would be a refusal with a second way
 * to be wrong. `serde` renders it the way a hosts file spells one.
 */
export type HostEntry = { 
/**
 * Where the name points. Only `127.0.0.1` and `::1` are ever accepted — see the T41 design, D5.
 */
address: string, 
/**
 * The name, lowercased and already checked by whoever built this.
 */
domain: string, };
