// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a client called its request, echoed back untouched on the response that answers it.
 *
 * The spec allows a string, a number or null, and says null is discouraged — so null is not
 * representable here, and a client of this crate cannot accidentally send one. It stays legal on a
 * *response*, which is why [`Response::id`] is an `Option<Id>` and this enum is not: an answer
 * carries a null id when the request's own id could not be read, and when the request spelled its
 * id `null` and is echoed the way it asked to be.
 *
 * Numbers are `i64` rather than `f64`: the spec discourages fractional ids, and a client that sends
 * one gets `invalid_request` instead of an id that comes back subtly different from what it sent.
 */
export type Id = number | string;
