// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IdleProbe } from "./IdleProbe";
import type { Millis } from "./Millis";

/**
 * When to stop a service that nothing is using.
 *
 * The product's central promise is that idle costs nothing, and this is the mechanism. `None` on a
 * [`ServiceSpec`] means never idle-stop — correct for the front-end web server, which is the thing
 * that starts everything else back up. Enforcement is roadmap task T69.
 */
export type IdlePolicy = { 
/**
 * How long the service must look idle before it is stopped.
 */
after: Millis, 
/**
 * What "idle" is measured with.
 */
probe: IdleProbe, };
