// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which of the three states `services.idle_minutes` is in, and what the recipe said about it.
 *
 * **Four values over three column states**, because `NULL` means two different things depending on
 * whether the recipe offers a default — and those two are exactly the pair a person needs told
 * apart. Both are a service that will not be stopped; only one of them is a setting anybody chose.
 */
export type IdleSource = "recipe" | "row" | "never" | "unset" | "unmeasurable";
