// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IdleExemption } from "./IdleExemption";
import type { IdlePolicy } from "./IdlePolicy";
import type { IdleSource } from "./IdleSource";
import type { ServiceId } from "./ServiceId";

/**
 * What `service.idle` answers — roadmap task **T69**.
 *
 * **The exemptions are carried rather than folded into `policy`**, on the rule T46 wrote for
 * `DnsStatus`: "why is this still running?" has four answers that look identical from outside — no
 * policy, policy switched off, a running dependent, a keep-warm project — and collapsing them into
 * one `Option` sends a person to change a setting that was never the cause.
 */
export type IdleReport = { 
/**
 * Which service this is about.
 */
service: ServiceId, 
/**
 * The policy in force, joined from the row and the recipe. [`None`] is never idle-stop.
 */
policy: IdlePolicy | null, 
/**
 * Where that policy came from, or why there is none.
 */
source: IdleSource, 
/**
 * What would stop it being stopped right now. Empty when nothing does.
 */
exempt: Array<IdleExemption>, };
