// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How to tell that a service has nothing to do.
 *
 * Measured, never assumed: an idle policy that only watched the clock would stop a database in the
 * middle of a long import. A service with an open connection is never idle.
 */
export type IdleProbe = { "type": "connections", 
/**
 * The port whose connections mean "in use".
 */
port: number, } | { "type": "http_counter", 
/**
 * The status URL to read.
 */
url: string, 
/**
 * The field within it holding the counter.
 */
field: string, } | { "type": "fast_cgi_status", 
/**
 * The pool's own listening socket.
 */
socket: string, 
/**
 * The `pm.status_path` the pool was configured with.
 *
 * **Never ends in `.php`**, which is the whole of what keeps it unreachable from a site:
 * both front ends hand FastCGI only what matches `.php`.
 */
path: string, };
