// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceId } from "./ServiceId";

/**
 * Why a service would not be idle-stopped right now even if its policy said so.
 */
export type IdleExemption = { "type": "dependent_running", 
/**
 * The dependent that is running.
 */
service: ServiceId, } | { "type": "project_kept_warm", 
/**
 * The project, by name.
 */
project: string, };
