// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionSummary } from "./ExtensionSummary";

/**
 * Every extension this home has installed.
 *
 * **`InstalledExtensions` and not `ExtensionList`**, for [`ExtensionOrigin`]'s reason: the shorter
 * name is a *PHP* extension listing's.
 */
export type InstalledExtensions = { 
/**
 * What is installed, by id.
 */
extensions: Array<ExtensionSummary>, };
