// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The three things `cert.issue` can do to one site.
 */
export type IssueOutcome = { "outcome": "issued", } | { "outcome": "reused", } | { "outcome": "not_wanted", 
/**
 * In words.
 */
because: string, } | { "outcome": "refused", 
/**
 * In words.
 */
because: string, };
