// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobState } from "./JobState";

/**
 * Which jobs `job.list` should answer with.
 *
 * Every field has a default, so `job.list` with no parameters is a question a person can type.
 */
export type JobFilter = { 
/**
 * Only jobs in this state, or all of them.
 *
 * `{"state":"running"}` is the one a GUI asks on every refresh — what is happening right now —
 * and it is a filter rather than its own method because "running" is not special to the daemon,
 * only to the client that is drawing a progress list.
 */
state?: JobState | null, 
/**
 * At most this many, newest first.
 *
 * **Bounded because the table is not.** `jobs` keeps every job a home has ever run, and a
 * listing that answered with all of them would grow without limit on a machine that installs a
 * runtime a week for two years. Fifty is what a person scrolls; a caller that wants the
 * history asks for more.
 */
limit: number, };
