// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Error } from "./Error";
import type { JobId } from "./JobId";
import type { Timestamp } from "./Timestamp";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A job ending: which one, how, and when.
 *
 * The value `mixengine-core` returns from the transaction that wrote it, and the value
 * [`crate::DaemonEvent::JobFinished`] carries — one description used twice, on
 * [`ServiceTransition`](crate::ServiceTransition)'s precedent, so an ending that was not persisted
 * cannot be announced.
 */
export type JobFinish = { 
/**
 * Which job.
 */
job: JobId, 
/**
 * When it ended.
 */
at: Timestamp, } & ({ "ending": "succeeded", 
/**
 * Whatever the method that owns this job documents. `null` for one that produces nothing
 * but the fact of having finished.
 */
result: JsonValue, } | { "ending": "failed", 
/**
 * The same wire error the call would have answered with had it been short enough to answer
 * inline — written once, by the layer that knows what went wrong, and rendered by a client
 * exactly as any other failure is. A job is not a second error vocabulary.
 */
error: Error, } | { "ending": "cancelled" });
