// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which job. The rowid of its `jobs` row, and nothing more.
 *
 * A number rather than the human-stable string a [`ServiceId`](crate::ServiceId) is, and the
 * difference is what the two identify: a service is named by whoever declared it and is typed by a
 * user for years, while a job is one run of one operation that nobody names and nobody types twice.
 * The database already mints exactly this — `jobs.id INTEGER PRIMARY KEY` is SQLite's rowid — so
 * generating an id of our own would be a second identity to keep in step with the first.
 *
 * `i64` and not `u64` because that is what the column holds; SQLite has no unsigned integer, and a
 * type that could express a value the store cannot round-trip would be a type that lies.
 */
export type JobId = number;
