// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of work a job is doing — `"runtime.install"`, `"cert.issue"`.
 *
 * **A kind is the method that produced the job**, and that is a rule rather than a convention: it
 * makes the vocabulary self-maintaining, since a method is already a name this project has agreed
 * on and already has documentation a user can be sent to. The alternative — a second vocabulary of
 * job names beside the method names — is two lists to keep in step, and the day they disagree the
 * GUI shows a job kind no page in the manual mentions.
 *
 * Validated rather than free text, because it is stored and shown: a kind with a newline in it is a
 * listing a person cannot read, and one built from user input is a value nothing else in the
 * database allows.
 */
export type JobKind = string;
