// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobSummary } from "./JobSummary";

/**
 * What `job.list` answers.
 *
 * An object around the list rather than a bare array, on [`ServiceList`](crate::ServiceList)'s
 * precedent: a field can be added beside it without changing every existing client's parser.
 */
export type JobList = { 
/**
 * The jobs that matched, newest first.
 */
jobs: Array<JobSummary>, };
