// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Error } from "./Error";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * What a finished job produced.
 *
 * Stored in `jobs.result_json` and carried by [`crate::DaemonEvent::JobFinished`], which is why it
 * is one type rather than a pair of nullable columns: a job that succeeded has a result and no
 * error, one that failed has an error and no result, and two independent options can express a
 * third thing that never happens.
 *
 * **The success payload is a [`serde_json::Value`]**, deliberately and unusually for this crate.
 * Every other wire type here is named, and this one cannot be: the shape of what a job produces
 * belongs to the method that produced it — an install answers with a version and a path, a
 * certificate issue with a fingerprint — and naming them all here would make `mixengine-proto`
 * depend on every feature in the roadmap. The typed half stays with the caller, which knows which
 * job it asked for and can deserialise accordingly.
 * The discriminator is `ending` rather than `outcome`, and that is not a spelling preference.
 * [`JobFinish`] flattens this type, so the tag lands beside `job` and `at` on the wire — where
 * `kind` would read as the job's kind (`"runtime.install"`) and `outcome` would nest as
 * `"outcome": {"outcome": …}` in [`JobSummary`](crate::JobSummary). One word that means the same
 * thing in both places is worth more than either.
 */
export type JobOutcome = { "ending": "succeeded", 
/**
 * Whatever the method that owns this job documents. `null` for one that produces nothing
 * but the fact of having finished.
 */
result: JsonValue, } | { "ending": "failed", 
/**
 * The same wire error the call would have answered with had it been short enough to answer
 * inline — written once, by the layer that knows what went wrong, and rendered by a client
 * exactly as any other failure is. A job is not a second error vocabulary.
 */
error: Error, } | { "ending": "cancelled" };
