// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobId } from "./JobId";
import type { Timestamp } from "./Timestamp";

/**
 * How far along a running job is.
 *
 * Its own type because it is what [`crate::DaemonEvent::JobProgress`] carries and what `jobs`
 * stores in two columns, and the pair is meaningless split: `40` with no sentence is a number a
 * user cannot act on, and `"verifying the download"` with no number is a progress bar that does not
 * move.
 */
export type JobProgress = { 
/**
 * Which job.
 */
job: JobId, 
/**
 * How far, as a percentage.
 *
 * A `u8` rather than a float, and clamped to 0–100 by the column's own `CHECK`: a progress bar
 * is drawn to the nearest pixel and no caller has ever needed a fraction of a percent. A job
 * that genuinely cannot say — a download whose server sent no `Content-Length` — reports `0`
 * and says so in the message, which is honest where an invented number is not.
 */
percent: number, 
/**
 * What it is doing right now, in one short clause a client puts beside the bar.
 *
 * Written by the producer and shown verbatim, so it is the producer's job to make it a sentence
 * rather than a debug line. Empty is allowed and means "no change to report".
 */
message: string, 
/**
 * When this was read, by the producer that reported it.
 */
at: Timestamp, };
