// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobId } from "./JobId";

/**
 * Which job a call is about.
 *
 * One params type for `job.status` and `job.cancel`, because the question each asks is the same
 * one, and the id is **required** in both: a status with no subject is a `job.list` that was typed
 * wrongly, and a cancel with no subject is not a request anybody should be able to make by
 * accident — see [`ServiceQuery`](crate::ServiceQuery), which is required for the first reason and
 * where this one adds the second.
 */
export type JobQuery = { 
/**
 * The job to describe, or to cancel.
 */
job: JobId, };
