// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a job is.
 *
 * **Closed, like [`ServiceState`](crate::ServiceState) and for the same reason**: this is a state
 * machine, and one with room for a state nobody has enumerated is one nobody can reason about. The
 * wire form is the snake_case name and it is also exactly what `jobs.state` holds — one spelling,
 * written by [`JobState::as_str`] and read back by [`JobState::parse`], with the column's `CHECK`
 * carrying the same closed list.
 *
 * **There is no `Cancelling`, and that is a decision rather than an omission.** Cancellation here
 * is cooperative: `job.cancel` cancels the token the work is watching, and the work ends when it
 * next looks. A state between the asking and the ending would have to be written by every producer
 * of a job — and this build has none yet, so the only thing that could justify it is a guess about
 * what T21's download will need. `Running` with a cancellation already requested is what a client
 * sees, which is the truth: the work is still going.
 */
export type JobState = "running" | "succeeded" | "failed" | "cancelled";
