// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobId } from "./JobId";
import type { JobKind } from "./JobKind";
import type { JobOutcome } from "./JobOutcome";
import type { JobState } from "./JobState";
import type { Timestamp } from "./Timestamp";

/**
 * One job, as the `jobs` row describes it. The whole of what `job.status` answers.
 *
 * One type for the listing, the single lookup, the wait and the cancel, on
 * [`ServiceSummary`](crate::ServiceSummary)'s precedent: all four are the same sentence about a
 * job, so a client renders them with one function.
 */
export type JobSummary = { 
/**
 * Which job.
 */
id: JobId, 
/**
 * What kind of work it is — the method that produced it.
 */
kind: JobKind, 
/**
 * Where it is.
 */
state: JobState, 
/**
 * How far along, as last reported. Stays at whatever it reached when the job ended, rather than
 * being snapped to 100: a job that failed at 40% failed at 40%, and rewriting that would erase
 * the one number that says where to look.
 */
percent: number, 
/**
 * What it last said it was doing. Empty for a job that has not reported anything yet.
 */
message: string, 
/**
 * When it started.
 */
started_at: Timestamp, 
/**
 * When it ended, or [`None`] while it is still going.
 */
finished_at?: Timestamp | null, 
/**
 * What it produced, once it has.
 *
 * [`None`] exactly while [`JobSummary::state`] is [`JobState::Running`] — the two are written
 * together by the same transaction, so a client may rely on that rather than checking both.
 */
outcome?: JobOutcome | null, };
