// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobFinish } from "./JobFinish";
import type { JobProgress } from "./JobProgress";

/**
 * One move of a job: progress, or the end of it.
 *
 * What a producer hands the daemon, so that the *writing* of a job's every move goes through one
 * door. A job that is over can no longer report progress, and this is the type that makes that
 * expressible rather than a rule each producer has to remember.
 */
export type JobUpdate = JobProgress | JobFinish;
