// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobId } from "./JobId";
import type { Millis } from "./Millis";

/**
 * Which job to wait for, and how long to wait.
 *
 * **`job.wait` is the one call in this API that blocks on purpose**, and the timeout is what keeps
 * that from contradicting the rule it is an exception to. `.claude/architecture/daemon-and-ipc.md`
 * says never to block an RPC call for minutes; a script that has nothing to do but wait for a
 * download is the case that rule was not written about, and it still does not get to hold a
 * connection open forever. What comes back when the time runs out is the job as it stands, not an
 * error: [`JobSummary::state`] says whether it finished, and a caller that wants to keep waiting
 * calls again.
 */
export type JobWait = { 
/**
 * The job to wait for.
 */
job: JobId, 
/**
 * How long to wait before answering with whatever the job is doing then.
 *
 * Defaults to thirty seconds, which is long enough that a short job is answered when it
 * finishes and short enough that nothing holds a connection past a person's patience. The
 * daemon bounds it: a client asking for an hour is answered by the daemon's own ceiling rather
 * than being trusted with the socket.
 */
timeout: Millis, };
