// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What became of the process — roadmap task **T83**, the design's D8.
 */
export type Launch = { "launch": "running", 
/**
 * Its process id.
 */
pid: number, } | { "launch": "handed_on" };
