// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How this system caps a supervised service. One per system, chosen by the system.
 *
 * The same shape as `PortAccessMethod` and for its reason: there is no
 * fallback chain and nothing to negotiate, because a machine has the mechanism its operating
 * system has.
 */
export type LimitMechanism = "job_object" | "cgroup_v2" | "none";
