// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Enforcement } from "./Enforcement";
import type { LimitMechanism } from "./LimitMechanism";
import type { MemoryMeasure } from "./MemoryMeasure";

/**
 * Everything a client needs to know before it offers a limit control.
 */
export type LimitSupport = { 
/**
 * Which mechanism this system uses.
 */
mechanism: LimitMechanism, 
/**
 * What a `cpu_percent` does here.
 */
cpu: Enforcement, 
/**
 * What a `memory_mb` does here.
 */
memory: Enforcement, 
/**
 * What a `memory_mb` is measured as here.
 */
memory_measure: MemoryMeasure, 
/**
 * Whether asking for a background priority does anything.
 *
 * True on all three so far, and reported rather than assumed so that the day one of them
 * cannot, nothing above has to change shape to say so.
 */
priority: boolean, 
/**
 * How many cores a `cpu_percent` may be spent across.
 *
 * **So a client can draw the ceiling it would otherwise be refused at**: `cpu_percent` is a
 * percentage of *one* core, so 800 is the whole of an eight-core machine. The refusal itself
 * lives in the daemon rather than in `mixengine-proto`, because this number is a property of
 * the machine and proto has no host to ask.
 */
cores: number, };
