// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether an extension is part of the binary or a file beside it.
 */
export type Linkage = "static" | "shared";
