// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the log excerpt begins, in numbers.
 *
 * **An excerpt silent about where it starts is an excerpt claiming to be the whole log.** The
 * difference between "nothing was logged before this" and "1.4 GB was logged before this" is what a
 * reader needs, and it is three numbers.
 */
export type LogExcerpt = { 
/**
 * Bytes of `daemon.log` in the archive.
 */
included_bytes: number, 
/**
 * Bytes of the current file older than the cut, the partial line dropped at it included.
 */
skipped_bytes: number, 
/**
 * Rotated files beside it that are not here.
 */
rotated_files: number, };
