// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogLine } from "./LogLine";

/**
 * One message on `GET /logs/service/{id}` or `GET /logs/job/{id}`.
 *
 * Two variants, because a stream of lines has one thing to say that is not a line: that some were
 * lost. A client that fell behind the service's own output is told how many rather than handed a
 * gap nobody mentions — the same honesty [`DaemonEvent::Resync`](crate::DaemonEvent::Resync) offers
 * on the event stream, and for the same reason: the alternative is a log panel that silently shows
 * output with a hole in it, which is worse than one that says where the hole is.
 *
 * Internally tagged, like every other framed type here, so a client has one handler and a variant
 * added later arrives as an object it can ignore.
 */
export type LogFrame = { "type": "line" } & LogLine | { "type": "historic", 
/**
 * The line, exactly as it is in the file.
 */
text: string, } | { "type": "gap", 
/**
 * How many lines this reader missed.
 */
missed: number, };
