// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Stream } from "./Stream";
import type { Timestamp } from "./Timestamp";

/**
 * One line a service printed.
 *
 * The text has no trailing newline and no trailing `\r`: a Windows service writing CRLF and a Unix
 * one writing LF have to produce the same line, or every pattern a user writes needs two versions.
 */
export type LogLine = { 
/**
 * Which stream it arrived on.
 */
stream: Stream, 
/**
 * When the supervisor read it, which is not quite when the service wrote it — a pipe holds tens
 * of kilobytes, so a service that blocked on a full pipe has its backlog timestamped as it
 * drains. Close enough to order lines by and honest about what it measures.
 */
at: Timestamp, 
/**
 * The line itself, lossily decoded: a service that writes a stray byte gets a replacement
 * character rather than having the line dropped.
 */
text: string, };
