// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much of a service's output to keep, and where the ceiling is.
 *
 * Rotation is the supervisor's own job rather than an external logrotate's, because the supervisor
 * is the process holding the file handle. Enforcement is roadmap task T16.
 */
export type LogPolicy = { 
/**
 * Rotate once the live file passes this size.
 *
 * *Passes*, not *reaches*: a line is never split across two files, so one long backtrace can
 * carry the file over its limit.
 */
max_file_bytes: number, 
/**
 * How many rotated copies to keep beside the live file.
 */
max_files: number, 
/**
 * How many recent lines to keep in memory, so `service.logs` and the GUI's log panel answer
 * instantly instead of reading from disk.
 */
ring_lines: number, };
