// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobId } from "./JobId";
import type { ServiceId } from "./ServiceId";

/**
 * Whose output a log stream carries — roadmap task **T78a**, its design's D13.
 *
 * **A second kind of subject rather than a second surface.** The ring, the frames, the [`Gap`] a
 * slow reader is told about and the per-connection back-pressure are the ones
 * [ADR 0009](https://github.com/mixnz/mixengine/blob/master/.claude/decisions/0009-logs-travel-on-their-own-stream.md)
 * argued for a service's output, and a blueprint's `[scaffold]` command needs every one of them for
 * the same reason: how much it prints is decided by somebody else's program.
 *
 * The route says which kind it is — `GET /logs/service/{id}` and `GET /logs/job/{id}`, two segments
 * always — so nothing has to decide whether a first segment is a package name or the word `job`.
 *
 * [`Gap`]: LogFrame::Gap
 */
export type LogSubject = { "subject": "service", 
/**
 * Which service.
 */
id: ServiceId, } | { "subject": "job", 
/**
 * Which job.
 */
id: JobId, };
