// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DaemonVersion } from "./DaemonVersion";
import type { LogExcerpt } from "./LogExcerpt";
import type { Omission } from "./Omission";
import type { Part } from "./Part";
import type { Timestamp } from "./Timestamp";

/**
 * `manifest.json` — what this bundle is.
 */
export type Manifest = { 
/**
 * [`MANIFEST_FORMAT`].
 */
format: number, 
/**
 * When it was taken.
 */
taken_at: Timestamp, 
/**
 * The home it was taken from.
 */
home: string, 
/**
 * The daemon that took it.
 */
daemon: DaemonVersion, 
/**
 * Every part in this archive, this one included.
 */
parts: Array<Part>, 
/**
 * What was left out, and why.
 */
omitted: Array<Omission>, 
/**
 * Where the log excerpt begins.
 */
daemon_log: LogExcerpt, };
