// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Part } from "./Part";

/**
 * One part that was written, and what it cost.
 */
export type Member = { 
/**
 * Which part.
 */
part: Part, 
/**
 * Its size before compression.
 */
bytes: number, };
