// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What watches a service's `memory_mb` where this machine cannot enforce it — task **T71a**.
 *
 * **Per service, which is why it is not a field of [`LimitSupport`]**: that type answers for the
 * machine and is handed no service, so it cannot say whether *this* one would be restarted. The
 * recipe answers that, and the answer therefore travels with the service.
 */
export type MemoryWatchdog = { 
/**
 * Consecutive finished minutes over the line before the service is restarted.
 *
 * Minutes because the unit is the metrics row: the sampler finishes one per subject per
 * minute, and the count is spent in those exactly as an idle policy is spent in sweeps.
 */
after_minutes: number, 
/**
 * Whether a restart follows at all, which is the recipe's answer.
 *
 * `false` is a service that is warned about and then left alone — a database, a cache. The
 * warning still happens; a client that renders only the restart would show nothing at all for
 * the services most worth saying something about.
 */
restarts: boolean, };
