// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a memory limit is measured as here.
 *
 * One number, two meanings, and neither system is wrong: a job object bounds **commit charge**, and
 * cgroup v2's `memory.max` bounds **charged pages**, which includes page cache. Reported beside the
 * number rather than resolved into one of them, so a caller is told what it means *here* instead of
 * assuming it means the same everywhere — which is `PortBinding`'s idea
 * applied to a quantity rather than to a port.
 * `#[non_exhaustive]` on [`Enforcement`]'s reasoning, and in the same release, because the two
 * travel together: a machine that changes what enforces a ceiling changes what the ceiling is
 * measured as.
 */
export type MemoryMeasure = "commit" | "charged_pages" | "resident";
