// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetricsSubject } from "./MetricsSubject";
import type { Timestamp } from "./Timestamp";

/**
 * What a client wants out of the history.
 */
export type MetricsHistoryQuery = { 
/**
 * One subject, or every subject when absent.
 */
subject: MetricsSubject | null, 
/**
 * The oldest minute wanted. Absent is as far back as the history goes.
 */
since: Timestamp | null, 
/**
 * The newest minute wanted. Absent is now.
 */
until: Timestamp | null, };
