// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetricsSubject } from "./MetricsSubject";
import type { Timestamp } from "./Timestamp";

/**
 * One subject's minute, out of the 24-hour history.
 */
export type MetricsMinute = { 
/**
 * Whose minute this is.
 */
subject: MetricsSubject, 
/**
 * The minute itself, truncated to it.
 */
minute: Timestamp, 
/**
 * The mean of the readings that carried a CPU figure, or [`None`] where none did.
 */
cpu_avg: number | null, 
/**
 * The largest CPU figure among them.
 *
 * **The largest of what was looked at, not of the minute.** Where [`samples`](Self::samples) is
 * 1 it equals the average, and that is what the pair means. It exists because "what was eating
 * my battery" is a question about spikes: a service holding 900 MB for two seconds and 200 MB
 * for the rest of the minute leaves nothing behind in an average.
 */
cpu_peak: number | null, 
/**
 * The mean resident size over the readings.
 */
rss_avg: number, 
/**
 * The largest resident size among them.
 */
rss_peak: number, 
/**
 * **How many readings this row is made of** — 1 while nobody was watching, up to 60 while
 * somebody was.
 *
 * An average of one reading and an average of sixty may both be drawn, but not as though they
 * were equally supported, and the row has to carry the difference for that to be possible.
 */
samples: number, };
