// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whose reading this is.
 *
 * **A closed set rather than a string**, so a client matches on it rather than recognising it. Its
 * [`Display`](fmt::Display) is also its wire spelling *and* its column spelling: one encoding,
 * defined once, so a row read back out of the database is a subject rather than a parse of one.
 */
export type MetricsSubject = string;
