// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A length of time, in milliseconds.
 *
 * The third time type, and the last: [`Timestamp`] is when something happened, [`Uptime`] is how
 * long ago that was in the resolution a person reads, and this is how long something is *allowed*
 * to take. Not [`Duration`], whose serde form is a `{secs, nanos}` object; not [`Uptime`], because a
 * restart backoff starts at 500 ms and whole seconds would round it to nothing.
 *
 * **Written as a number, read as a number or as a human string.** The canonical form — what a
 * daemon sends and what a client should expect — is milliseconds as an integer. Deserialisation
 * additionally accepts `"500ms"`, `"10s"`, `"5m"`, `"2h"`, because the other direction this type
 * travels is a hand-written `extension.toml`, where `timeout = "10s"` is what an author will write
 * and `timeout = 10000` is what they will get wrong. Whole numbers only: `"1.5s"` is rejected
 * rather than rounded, since the unit to say it in already exists.
 */
export type Millis = number;
