// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What to do about a version that is not the one asked for.
 *
 * **There is no `Cancel`.** The third answer in the feature doc's sentence needs nothing on the
 * wire: it is not sending the apply.
 *
 * Closed, for the reason [`AnswerSubject`] is.
 */
export type MismatchAnswer = "install" | "use_installed";
