// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How far an extension's own listeners may be reached from.
 */
export type NetworkReach = "loopback" | "lan";
