// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Something this bundle does not carry, and why.
 *
 * **A field and not a comment in a document nobody reads.** A bundle silent about where it did not
 * look is a bundle claiming it looked everywhere, and the person reading the bug report is the one
 * who pays for that.
 */
export type Omission = { 
/**
 * What was left out, named as a person would say it: `"etc/"`, `"status.json"`.
 */
name: string, 
/**
 * Why. Either a decision, or the error that prevented it — never an apology.
 */
because: string, };
