// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What became of one operation.
 */
export type OpOutcome = { "outcome": "applied", 
/**
 * What changed, for a log line and for `mix doctor`.
 */
detail: string, } | { "outcome": "already-done" } | { "outcome": "refused", 
/**
 * Which rule it broke.
 */
reason: string, } | { "outcome": "unsupported", 
/**
 * What could not be decoded.
 */
reason: string, } | { "outcome": "failed", 
/**
 * The OS's own complaint.
 */
message: string, } | { "outcome": "unmanaged", 
/**
 * Why nothing was done, phrased for a user.
 */
reason: string, 
/**
 * What to run by hand where the port does turn out to be blocked. Empty where there is
 * nothing sensible to suggest.
 */
manual: string, };
