// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProblemId } from "./ProblemId";

/**
 * What a check found.
 *
 * **Internally tagged**, so a client matches on a word rather than working out which fields
 * arrived.
 */
export type Outcome = { "outcome": "ok", } | { "outcome": "note", 
/**
 * The fact, in a sentence.
 */
because: string, } | { "outcome": "problem", 
/**
 * A stable name for the condition, which `daemon.doctor_repair` matches on.
 */
id: ProblemId, 
/**
 * What is wrong, in a sentence, for a person. Never what to do about it.
 */
because: string, } | { "outcome": "skipped", 
/**
 * Why it could not be examined here.
 */
because: string, };
