// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageVersion } from "./PackageVersion";

/**
 * Which package a call is about.
 *
 * One params type for `package.install` and `package.uninstall`, on
 * [`RuntimeTarget`](crate::RuntimeTarget)'s reasoning: both fields are required in both, because a
 * package with no version is not an installable thing and a call that guessed one — the newest, the
 * only one installed — would be a client deciding something.
 */
export type PackageTarget = { 
/**
 * Which package, by the name a recipe is found under.
 *
 * A plain [`String`] rather than a closed enum: which packages exist is a property of the
 * build, not of the wire, and the daemon holds the set — so a name this build cannot run is
 * refused with the list of the ones it can, which is a better answer than a decode failure.
 */
package: string, 
/**
 * Which version, exactly as the index publishes it.
 */
version: PackageVersion, };
