// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which release channel a published version belongs to.
 *
 * The index's own three, mirrored here rather than shared with it: the document's vocabulary
 * belongs to `mixengine_core::index`, which is a description of a *file we publish*, and this one
 * belongs to the wire. They agree today and the conversion between them is one `match` in `core`,
 * which is the price of the two being able to move apart — a channel added to the index for the
 * publishing pipeline's own purposes should not become an API change by accident.
 */
export type PackageChannel = "stable" | "rc" | "beta";
