// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageSummary } from "./PackageSummary";

/**
 * What `package.uninstall` answers.
 *
 * The summary as it stood before the row went, which is the only moment anything could describe it.
 */
export type PackageRemoval = { 
/**
 * What is no longer installed.
 */
removed: PackageSummary, };
