// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Upstream's version string, exactly as upstream writes it.
 *
 * **Validated because it is a path component**, on [`ServiceId`](crate::ServiceId)'s reasoning: an
 * install lands in `runtimes/<kind>/<version>/` or `packages/<name>/<version>/`, so a value
 * carrying a separator, a `..` or a
 * trailing dot is not a lookup that fails — it is a write somewhere nobody meant. The charset is
 * narrow enough that none of those can be spelled at all, which is why the installer can `join`
 * this rather than escape it.
 *
 * **Not normalised**, which is what keeps it an identifier: `8.3.33` is the string a user pinned in
 * `mixengine.toml` and the string the index published, and rewriting it here would stop the two
 * matching — the directory on disk is named after it.
 *
 * **Two orders, and the derived one is not the version order.** `Ord` is the string's, kept because
 * this type is a `BTreeMap` key in the daemon and a map wants a cheap total order it can rely on.
 * Which of two versions is *newer* is [`cmp_precedence`](Self::cmp_precedence), and it is a
 * different answer: `8.10.0` is newer than `8.9.0` and sorts before it as text. Anything choosing a
 * version for somebody wants the second one.
 */
export type PackageVersion = string;
