// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which packages a listing should answer with.
 *
 * Every field has a default, so both listings with no parameters are questions a person can type.
 */
export type PackageFilter = { 
/**
 * Only this package, or all of them.
 *
 * A filter rather than a required argument for [`RuntimeFilter`](crate::RuntimeFilter)'s
 * reason: a GUI's first paint asks about everything at once, and the answer for a package
 * nobody has installed is an empty list rather than an error.
 */
package?: string | null, 
/**
 * Ask the package index again even if the cached copy is still fresh —
 * [`RuntimeFilter::refresh`](crate::RuntimeFilter::refresh)'s reason, meaningless here for
 * `package.list`.
 */
refresh?: boolean, };
