// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Everything this build puts in a bundle.
 *
 * **Closed, and never a directory walk.** `<root>/certs/` holds the internal CA's private key,
 * `<root>/data/` the user's databases, and `<root>/run/` what stands between a local process and
 * the daemon. A sweep written today omits all three because whoever wrote it remembered; a sweep
 * still omits them next year only if everyone who ever adds a file to the home happens to think
 * about an archive somebody emails. A variant is something a person wrote down.
 *
 * The compiler enforces most of that: a variant added here stops [`file_name`](Self::file_name)
 * compiling, and stops the daemon's own `match` compiling with it. What it cannot enforce is
 * [`ALL`](Self::ALL) — see the test in this module for where that gap is caught instead.
 */
export type Part = "manifest" | "doctor" | "status" | "platform" | "daemon_log" | "crashes";
