// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One place this machine keeps a PATH that survives a reboot, and what it says.
 *
 * A list of these rather than a boolean because Unix has more than one: a home with both a
 * `.bash_profile` and a `.zprofile` needs the line in both, and being told "the PATH is set up"
 * while one's own login shell disagrees is the confusing half-state this exists to name.
 */
export type PathPlace = { 
/**
 * What to show: a shell profile's path, or the registry value's full name.
 *
 * A string and not a `PathBuf` for [`DaemonStatus`](crate::DaemonStatus)' reason, and here it
 * is not always a path at all — on Windows it is `HKEY_CURRENT_USER\Environment\Path`.
 */
name: string, 
/**
 * Whether `<root>/bin` is in it as things stand.
 */
present: boolean, 
/**
 * Whether *this call* is what put it there or took it away.
 *
 * Always `false` from `path.status`. It is what lets a client say "already set up" rather than
 * claiming a write it did not perform — the two are indistinguishable to somebody reading the
 * output, and only one of them is true.
 */
changed: boolean, };
