// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PathPlace } from "./PathPlace";

/**
 * What every `path.*` method answers.
 */
export type PathReport = { 
/**
 * The directory in question: `<root>/bin`, as a string for display.
 */
directory: string, 
/**
 * Whether every place this OS reads a persisted PATH from carries it.
 *
 * **Every one and not any of them** — see [`PathPlace`]. Composed by the daemon rather than
 * left for each client to fold the list itself, which is business logic and a place for two
 * clients to disagree about what "set up" means.
 */
on_path: boolean, 
/**
 * Each of those places, in the order this OS reads them.
 */
places: Array<PathPlace>, 
/**
 * The commands `<root>/bin` answers to, as the files in it are named.
 *
 * Carried by all three methods because it is the other half of the same question: a PATH entry
 * naming a directory with no `php` in it is a PATH entry that does nothing, and the two are
 * set up together (roadmap task T26).
 */
commands: Array<string>, 
/**
 * What was in `<root>/bin` that no command answers to and could not be removed.
 *
 * Empty on every ordinary call. It is here rather than only in the daemon's log because a name
 * left behind is a name on the user's PATH running something this build no longer understands
 * — on Windows, most often a shim a shell in another window is still holding.
 */
stale?: Array<string>, };
