// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of the queue, by its rowid.
 *
 * A newtype rather than a bare `i64` on `.claude/standards/rust.md`'s rule: the one method that
 * takes one is `elevation.drop`, and an integer there could be a job, an operation or a mistake.
 */
export type PendingOpId = number;
