// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PendingOpId } from "./PendingOpId";
import type { PrivilegedOp } from "./PrivilegedOp";
import type { Timestamp } from "./Timestamp";

/**
 * One operation waiting for somebody to allow it.
 */
export type PendingOp = { 
/**
 * Which row, so `elevation.drop` can name one.
 */
id: PendingOpId, 
/**
 * The operation itself, decoded. A row this build cannot decode is deleted rather than carried
 * — see the T40b design, D2 — so this is never a value nobody can act on.
 */
op: PrivilegedOp, 
/**
 * [`PrivilegedOp::describe`], rendered here rather than by the client.
 *
 * `CLAUDE.md`: a client renders what the daemon returns. It matters more here than anywhere
 * else — this is the sentence somebody reads before allowing a change to a file outside their
 * home — and a second client composing its own wording would be a second chance to get it
 * wrong.
 */
description: string, 
/**
 * When it was first asked for.
 *
 * **First** and not last: the same operation enqueued again keeps this reading (D2), so
 * "pending since" says how long the machine has been missing it rather than how recently
 * somebody noticed.
 */
requested_at: Timestamp, };
