// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where an effective pin was read.
 */
export type PinSource = { "from": "registered" } | { "from": "manifest", 
/**
 * The file that decided it, because that is what somebody would go and edit.
 */
path: string, };
