// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceId } from "./ServiceId";

/**
 * The site a `web-app` would be given — roadmap task **T81b**.
 *
 * Shown in the plan so the name that will be taken and the PHP it will run on are read before
 * anything is fetched; **not part of the consent**, because it is derived from a manifest the
 * person already agreed to.
 */
export type PlannedSite = { 
/**
 * `<label>.mixengine.test`.
 */
domain: string, 
/**
 * The pool it would run on — **its own**, on the newest installed PHP inside
 * `[web-app.runtime].requires` (roadmap task **T82a**).
 *
 * T81b named the shared `php-fpm@<version>` here. A `web-app` now gets a second pool on that
 * same PHP, so an administrative interface onto this machine's databases is never in the
 * process serving somebody's project — and so the credential below has somewhere to be that is
 * nobody else's.
 */
pool: ServiceId, 
/**
 * The account this application would be **signed in as** — roadmap task **T82a**.
 *
 * Shown before anything is agreed to, beside the database: its own php-fpm pool would be given
 * that account's password, read from the OS keyring at the moment the pool starts and written
 * to no disk. It is the most consequential thing an extension can be granted, so a client that
 * renders the permissions renders this among them. [`None`] where the manifest asked for no
 * such thing, which is every published extension but phpMyAdmin.
 */
signs_in?: string | null, 
/**
 * The database it would administer, for a `web-app` declaring `[web-app.database]` — roadmap
 * task **T82**.
 *
 * **Shown before anything is agreed to**, because it is the second thing an install freezes:
 * which server this administrative interface opens onto is not a detail somebody should find
 * out afterwards. [`None`] where the manifest declares no database.
 */
database?: ServiceId | null, };
