// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DaemonVersion } from "./DaemonVersion";
import type { ReservedRange } from "./ReservedRange";

/**
 * `platform.json` — the facts the doctor's judgement was made from.
 *
 * **Only what is free to read.** `daemon.doctor` has already probed the resolver and port access,
 * and probing them again for this file would let one archive hold two answers about one machine.
 * What is here is a compile-time constant, a per-OS constant, or the read of a table.
 */
export type PlatformFacts = { 
/**
 * `std::env::consts::OS`.
 *
 * The operating system's *version* is deliberately absent: reading it is a system call, which
 * belongs behind a `mixengine-platform` capability that does not exist yet.
 */
os: string, 
/**
 * `std::env::consts::ARCH`.
 */
arch: string, 
/**
 * `std::env::consts::FAMILY`.
 */
family: string, 
/**
 * What this daemon is, and what it speaks.
 */
daemon: DaemonVersion, 
/**
 * What this system promises about a killed daemon's descendants — `total`, `immediate_child`
 * or `none`. See `.claude/decisions/0007-supervised-child-owns-a-process-group.md`.
 */
orphan_guarantee: string, 
/**
 * The same answer as the sentence a person reads.
 */
orphan_because: string, 
/**
 * Whether a prompt can be raised here, and what is missing when it cannot.
 */
elevation: string, 
/**
 * What this system has taken out of circulation, or [`None`] when it could not be read.
 */
reserved_ports: Array<ReservedRange> | null, };
