// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What happened to the pool that runs this version.
 */
export type PoolOutcome = "reloaded" | "restart_required" | "pool_not_running";
