// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a service is not on the port its recipe would have preferred — roadmap task **T34c**.
 *
 * **A port a person did not pick is one they have to be told about.** A recipe names the number
 * its product is documented under — 3306 for both databases, 6379 for Redis — and the first row to
 * ask for it is given it; every later asker is given the first free port above. So the sentence
 * this carries is either "the number you know is in use by `mysqld.exe`" or "another MixEngine
 * service already has it", and both of them are things a developer whose `.env` says 3306 needs to
 * read at the moment of creation rather than to discover from a connection that is refused.
 *
 * The two identifying fields are separate rather than one rendered string for
 * [`StateReason::PortInUse`]'s reason, and are empty in the case
 * that variant cannot have: a port lost to another *MixEngine* service is held by a process the
 * daemon knows about and may not be running at all.
 */
export type PortMoved = { 
/**
 * The port the recipe asked for, and did not get.
 */
preferred: number, 
/**
 * The process holding it, where this account may learn it.
 */
pid?: number | null, 
/**
 * The file name of that process's program, where this account may read it.
 */
program?: string | null, };
