// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One port a site is reached on, and the ordinary port a program binds to answer it.
 *
 * On macOS these differ — a packet-filter rule sends 80 to 8080 — and on the other two they do not.
 * The pair travels together because the layer that generates a front end's configuration needs both
 * numbers and may not ask which operating system it is on.
 */
export type PortRedirect = { 
/**
 * What a browser asks for: 80 or 443.
 */
answer: number, 
/**
 * What a program actually binds, which an ordinary account may.
 */
bind: number, };
