// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortRedirect } from "./PortRedirect";

/**
 * What granting port access means on the machine being asked — the T42 design, D2 and D4.
 *
 * **Two variants rather than one struct holding both a binary and a redirect list**, because a
 * field the helper does not use is a field the helper cannot validate, and validating is that
 * binary's entire job. Every OS refuses the variant that is not its mechanism; no branch quietly
 * does nothing.
 */
export type PortAccessPlan = { "method": "capability", 
/**
 * The program the capability goes on. The helper checks that the caller owns it and that
 * nobody else can write it — the T42 design, D5.
 */
binary: string, 
/**
 * Which reserved ports it is being allowed. Only 80 and 443 are ever accepted.
 */
ports: Array<number>, } | { "method": "redirect", 
/**
 * Every port that moves, and where to.
 */
redirects: Array<PortRedirect>, };
