// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What taking port access away means.
 *
 * Mirrors [`PortAccessPlan`] with only the fields a removal reads: a capability is cleared whole,
 * so there is no port to name, and the three files a redirect leaves behind are constants in the
 * helper rather than anything a request may choose.
 */
export type PortAccessTarget = { "method": "capability", 
/**
 * The program to clear it from, checked exactly as a grant's is.
 */
binary: string, } | { "method": "redirect", };
