// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One port an extension asked for.
 *
 * **A wish and not a reservation.** Allocation happens when a row is written, which is T81's, and
 * nothing here holds a number. A line that read like a reservation is how somebody concludes a
 * port is theirs.
 */
export type PortWish = { 
/**
 * The name `[ports]` gave it, which is also its placeholder.
 */
name: string, 
/**
 * The number it would like.
 */
wanted: number, };
