// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Scheduling priority, the one resource control every OS can honour.
 */
export type Priority = "normal" | "background";
