// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProtocolVersion } from "./ProtocolVersion";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * One batch of privileged operations, covered by one prompt.
 */
export type PrivilegedRequest = { 
/**
 * The protocol this daemon speaks. A helper that does not know it refuses the whole request.
 */
version: ProtocolVersion, 
/**
 * `MIXENGINE_HOME`. Every path in every operation is canonicalised and must resolve inside it,
 * and the helper checks that this directory belongs to whoever owns the request file — without
 * that, `--home C:\Windows\System32` is an escalation for every operation that takes a path.
 */
home: string, 
/**
 * Echoed into the response, so a daemon cannot read the answer to an earlier request as the
 * answer to this one. It is **not** the anti-replay check; [`RESPONSE_FILE_NAME`] is.
 */
nonce: string, 
/**
 * The operations, left undecoded.
 *
 * A `Vec<PrivilegedOp>` would fail as a whole on one variant this build has never heard of,
 * which — the helper being excluded from auto-update — is a routine event and not a corruption.
 * Decoded one element at a time, an unknown operation becomes
 * [`OpOutcome::Unsupported`] at its own index and its neighbours are applied. The daemon builds
 * a `Vec<PrivilegedOp>` and serialises it into this field; the asymmetry is confined here.
 */
ops: Array<JsonValue>, };
