// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpOutcome } from "./OpOutcome";
import type { ProtocolVersion } from "./ProtocolVersion";

/**
 * What the helper did, one entry per operation, plus what it is.
 *
 * **The report is a property of the response and not the outcome of `Probe`.** Nesting it in
 * [`OpOutcome::Applied`]'s `detail` would put a JSON document inside a JSON string, and would mean
 * the daemon learns what the installed helper can do only on the round trips where it thought to
 * ask. Here it costs a few strings, arrives on every answer, and is read the same way whatever the
 * request contained.
 */
export type PrivilegedResponse = { 
/**
 * The protocol the helper speaks.
 */
version: ProtocolVersion, 
/**
 * The helper binary's own version, which is not the protocol's: it is installed once and
 * excluded from auto-update, so it drifts behind the daemon by design.
 */
"elevate-version": string, 
/**
 * Echoed from the request.
 */
nonce: string, 
/**
 * Was this process actually running with an administrative token?
 */
elevated: boolean, 
/**
 * [`PrivilegedOp::ALL`] for the build that answered.
 */
"supported-ops": Array<string>, 
/**
 * Where this helper records what it applied — reported whether or not anything was written to
 * it, so `mix doctor` can find it on a machine where nothing has been applied yet.
 */
"audit-log": string, 
/**
 * One outcome per element of [`PrivilegedRequest::ops`], at the same index.
 */
results: Array<OpOutcome>, };
