// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectSummary } from "./ProjectSummary";

/**
 * What `project.delete` answers.
 */
export type ProjectRemoval = { 
/**
 * The project that is gone.
 */
removed: ProjectSummary, 
/**
 * The directory, left exactly as it was and said out loud.
 *
 * [`ServiceRemoval`](crate::ServiceRemoval)'s rule: a directory nobody was told about is a
 * directory nobody ever cleans up.
 */
root_kept: string, 
/**
 * Its manifest, when there was one, on the same reasoning.
 */
manifest_kept?: string | null, };
