// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `project.export` answers.
 */
export type ProjectExport = { 
/**
 * The file that was written, which is `<root>/mixengine.toml` and nowhere else.
 */
path: string, 
/**
 * Whether the file was made, or an existing one merged into.
 */
created: boolean, 
/**
 * The sites that were not written, because a manifest holds one `[site]` (spec D9).
 *
 * Their primary domains, so a person knows what the file does not say — a limit of the file
 * format rather than of the model.
 */
sites_omitted?: Array<string>, };
