// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectSummary } from "./ProjectSummary";

/**
 * What `project.list` answers.
 *
 * An object around the list rather than a bare array, on [`PackageList`](crate::PackageList)'s
 * precedent: a field can be added beside it without changing every existing client's parser.
 */
export type ProjectList = { 
/**
 * Every registered project, in name order.
 */
projects: Array<ProjectSummary>, };
