// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectRef } from "./ProjectRef";
import type { RuntimeKind } from "./RuntimeKind";
import type { VersionConstraint } from "./VersionConstraint";

/**
 * Change one of the three things a project row holds.
 *
 * **`pins` replaces rather than merges** (spec D6): an absent field means unchanged, and `{}`
 * clears every pin. A merge would leave no way to remove one.
 */
export type ProjectUpdate = { 
/**
 * Which project.
 */
project: ProjectRef, 
/**
 * A new name, validated exactly as a create's is.
 */
name?: string | null, 
/**
 * A new root — for a repository that moved, which is the only reason this exists.
 */
root?: string | null, 
/**
 * The pins, replacing whatever the row held.
 */
pins?: { [key in RuntimeKind]?: VersionConstraint } | null, 
/**
 * Whether to hold this project's services out of idle shutdown — roadmap task **T69**.
 *
 * A field here rather than a `project.keep_warm` method of its own: it is a setting on a
 * project, it travels on the call every other project setting travels on, and a whole RPC for
 * one boolean is a second door onto one row.
 */
keep_warm?: boolean | null, };
