// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One registered project.
 */
export type ProjectSummary = { 
/**
 * What it is called, which is also how it is addressed.
 */
name: string, 
/**
 * Its root directory, spelled the way the filesystem spells it.
 */
root: string, 
/**
 * When it was registered, as `YYYY-MM-DDTHH:MM:SSZ`.
 */
created_at: string, 
/**
 * The `mixengine.toml` at the root, when there is one.
 *
 * Which is what decides whether the row's pins can take effect at all — the file outranks the
 * row, so a listing that did not say whether one is there would be a listing missing the
 * reason.
 */
manifest?: string | null, 
/**
 * Whether this project's services are held out of idle shutdown — roadmap task **T69**.
 *
 * In the listing rather than in `project.show` alone, because it is the answer to "why is that
 * still running?" and the person asking is looking at a list.
 */
keep_warm: boolean, };
