// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeKind } from "./RuntimeKind";
import type { VersionConstraint } from "./VersionConstraint";

/**
 * Register a directory as a project.
 *
 * One method rather than a create and an import (spec D2): both produce one row, and the only
 * difference is where `name` and `pins` came from. Each falls through — the argument, then the
 * `mixengine.toml` at `root`, then the directory's own base name for `name` and nothing for
 * `pins`.
 */
export type ProjectCreate = { 
/**
 * The project's root, which has to be an absolute directory that exists.
 */
root: string, 
/**
 * What to call it. Falls through to `[project] name`, then to the directory's base name.
 */
name?: string | null, 
/**
 * The versions it wants. Falls through to `[runtimes]`, then to no pins at all.
 */
pins?: { [key in RuntimeKind]?: VersionConstraint } | null, };
