// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectRef } from "./ProjectRef";

/**
 * Which project `project.show`, `project.delete` and `project.export` are about.
 */
export type ProjectQuery = { 
/**
 * Which project.
 */
project: ProjectRef, };
