// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which project a call is about.
 *
 * **Two ways in, because a person has two.** A GUI holds the name it listed; a shell is *inside*
 * the directory and knows nothing else. [`ProjectRef::Path`] is resolved by walking up to the
 * nearest registered root, which is what the shim already does two feet away — so `mix project
 * show` typed three directories deep finds the project.
 */
export type ProjectRef = { "name": string } | { "path": string };
