// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageVersion } from "./PackageVersion";
import type { PinSource } from "./PinSource";
import type { RuntimeKind } from "./RuntimeKind";
import type { VersionConstraint } from "./VersionConstraint";

/**
 * One language's pin, where it was read, and whether this machine can satisfy it.
 */
export type ProjectPin = { 
/**
 * Which language.
 */
kind: RuntimeKind, 
/**
 * What was asked for.
 */
constraint: VersionConstraint, 
/**
 * Which of the two would win at resolve time, and where it was read.
 */
source: PinSource, 
/**
 * The installed version this resolves to today, or [`None`] when nothing does.
 */
resolved?: PackageVersion | null, 
/**
 * When it resolves to nothing: the command that would fix it.
 *
 * The same sentence a failed resolution already gives, so a person meets one wording rather
 * than two.
 */
hint?: string | null, };
