// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectPin } from "./ProjectPin";
import type { ProjectSummary } from "./ProjectSummary";

/**
 * One project and what it actually resolves to.
 */
export type ProjectDetail = { 
/**
 * The project itself.
 */
project: ProjectSummary, 
/**
 * Its pins in **effective** order — the manifest's entry where there is one, the row's where
 * there is not — because that is what the shim will do, and a panel showing anything else is
 * a panel that lies.
 */
pins: Array<ProjectPin>, };
