// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Made } from "./Made";

/**
 * What became of the database, and of the account.
 */
export type Provisioned = { 
/**
 * The database.
 */
database: Made, 
/**
 * The account.
 */
user: Made, };
