// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Millis } from "./Millis";

/**
 * *Can traffic be routed to it yet?*
 *
 * Distinct from [`HealthCheck`], which asks whether it is still fine, because MariaDB's first boot
 * initialises a schema and is slow while its steady-state ping is cheap. Every variant carries its
 * own timeout: exceeding it is what turns `Starting` into `Failed`.
 */
export type ReadyCheck = { "type": "tcp", 
/**
 * Where to connect.
 */
addr: string, 
/**
 * How long to keep trying before giving up.
 */
timeout: Millis, } | { "type": "unix_socket", 
/**
 * The socket path.
 */
path: string, 
/**
 * How long to keep trying before giving up.
 */
timeout: Millis, } | { "type": "http", 
/**
 * The URL to request.
 */
url: string, 
/**
 * The status that means ready. Often `200`, but a service whose root redirects says `302`.
 */
expect_status: number, 
/**
 * How long to keep trying before giving up.
 */
timeout: Millis, } | { "type": "log_pattern", 
/**
 * The pattern, in the `regex` crate's syntax.
 */
regex: string, 
/**
 * How long to keep reading before giving up.
 */
timeout: Millis, } | { "type": "pid_alive", 
/**
 * How long the process must stay up to count as ready.
 */
settle: Millis, } | { "type": "command", 
/**
 * The program to run.
 */
program: string, 
/**
 * Its arguments.
 */
args: Array<string>, 
/**
 * How long to keep retrying before giving up.
 */
timeout: Millis, };
