// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrontEndServer } from "./FrontEndServer";

/**
 * One thing an extension adds to generated configuration.
 */
export type RecipeAddition = { "type": "php_ini", 
/**
 * The ini key.
 */
key: string, 
/**
 * Its value, rendered.
 */
value: string, } | { "type": "front_end", 
/**
 * Which of the two front ends the fragment is written for — roadmap task **T81c**.
 *
 * Shown rather than folded away, because a home running the *other* front end renders
 * nothing for this entry: what an inspection would otherwise say is that something is
 * added, without saying to what.
 */
server: FrontEndServer, 
/**
 * The fragment, rendered.
 */
fragment: string, };
