// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Millis } from "./Millis";
import type { ReloadSignal } from "./ReloadSignal";

/**
 * How to hand a running service a configuration that has changed, without stopping it.
 *
 * **The whole point is what it is not**: a restart. `.claude/features/services.md` puts it as
 * "reload beats restart", and the cost it is avoiding is real — the front-end web server is the
 * thing every site is reached through, and dropping every connection because one site was edited is
 * a cost the user did not ask for and cannot see the reason for.
 *
 * `None` means a service with no such mechanism, which is most of them: Redis and Memcached read
 * their configuration once, and a change to one is a restart whichever way it is spelled.
 *
 * Two variants, because the two servers this ships with reload by different means: Caddy runs a
 * program, php-fpm takes a signal. Windows has neither of those signals, so a recipe there returns
 * no reload at all rather than one that would be refused — `.claude/decisions/0008-no-signal-stop-on-windows.md`.
 * `#[non_exhaustive]` is what leaves a third addition additive.
 */
export type ReloadBehaviour = { "type": "command", 
/**
 * The program to run.
 */
program: string, 
/**
 * Its arguments.
 */
args: Array<string>, 
/**
 * How long it is given before it is abandoned and the reload counted as not done.
 *
 * Not a grace period: nothing is killed when this expires and the service goes on running
 * the configuration it already had. What it bounds is how long the daemon waits.
 */
patience: Millis, } | { "type": "signal", 
/**
 * Which signal.
 */
signal: ReloadSignal, 
/**
 * How long the daemon treats the reload as in progress before it stops waiting.
 *
 * Not a grace period: nothing is killed when it expires, and unlike a command there is no
 * exit status to read either way. What it bounds is the window in which a second reload is
 * not sent on top of the first.
 */
patience: Millis, };
