// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which signal a [`ReloadBehaviour::Signal`] sends.
 *
 * **A closed list and not a number.** This crate is the wire vocabulary, is compiled for three
 * systems and must not leak `libc` — the same reason [`StopBehaviour::Signal`] names no signal
 * either. Three variants because three are what the servers MixEngine runs use: `SIGHUP` almost
 * everywhere, `SIGUSR1` for a log reopen, `SIGUSR2` for php-fpm's graceful pool restart. A fourth
 * is a variant added the day a recipe needs it, which is a decision somebody makes — where an
 * `i32` would be a number a recipe could invent and the platform layer would have to trust.
 */
export type ReloadSignal = "hup" | "usr1" | "usr2";
