// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What became of one thing on the list.
 *
 * **Internally tagged**, so a client matches on a word rather than working out which fields
 * arrived — [`Outcome`](crate::Outcome)'s rule.
 */
export type Removal = { "removal": "absent", } | { "removal": "planned", 
/**
 * What the real run would do, in a sentence.
 *
 * For everything that needs the helper this is
 * [`PrivilegedOp::describe`](crate::privileged::PrivilegedOp::describe)'s own sentence, so
 * that the plan and the elevation prompt say the same thing about the same operation.
 */
how: string, } | { "removal": "removed", 
/**
 * What was done, in a sentence.
 */
what: string, } | { "removal": "enqueued", 
/**
 * What is waiting, in a sentence.
 */
what: string, } | { "removal": "on_exit", 
/**
 * What goes, in a sentence.
 */
what: string, } | { "removal": "on_restart", 
/**
 * What is scheduled and why it had to be, in a sentence.
 */
what: string, } | { "removal": "kept", 
/**
 * Why it was left, in a sentence.
 */
because: string, } | { "removal": "failed", 
/**
 * What the machine said, and the fact that the thing is still there.
 */
because: string, };
