// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";
import type { Version } from "./Version";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * One call.
 *
 * `params` stays a [`Value`] until the method is known, because only the handler knows what shape
 * it expects — decoding it here would mean one enormous enum of every request type in the API, and
 * an unknown method would fail as a parse error rather than as `method_not_found`.
 */
export type Request = { 
/**
 * Always `"2.0"`.
 */
jsonrpc: Version, 
/**
 * `namespace.verb` — see [`method`].
 */
method: string, 
/**
 * The method's arguments, if it takes any.
 */
params?: JsonValue | null, 
/**
 * What to echo on the answer.
 *
 * `None` here means either of two things the spec keeps apart — an absent `id`, which is a
 * notification, and `"id":null`, which is a request that still has to be answered — because
 * `Option<Id>` reads both as the same value. Anything that has to tell them apart looks at the
 * undecoded JSON, which is why the daemon decides that before it decodes a call and why
 * [`Request::is_notification`] says out loud that it cannot.
 */
id?: Id | null, };
