// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A range this operating system will not let anything bind.
 *
 * Mirrored here rather than shared with `mixengine_platform::PortRange`, for the reason every other
 * mirrored vocabulary in this crate carries: `mixengine-platform` depends on this crate, and not
 * the other way round.
 */
export type ReservedRange = { 
/**
 * The first port, included.
 */
start: number, 
/**
 * The last port, included.
 */
end: number, };
