// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Removal } from "./Removal";
import type { ResidueId } from "./ResidueId";

/**
 * One thing MixEngine can have written, and what became of it.
 */
export type Residue = { 
/**
 * A stable name for the thing, which a client renders and a test asserts on.
 */
id: ResidueId, 
/**
 * What it is, phrased for a person: "the managed hosts block".
 */
what: string, 
/**
 * Where it is, phrased for a person: `/etc/hosts`, `HKEY_CURRENT_USER\Environment\Path`, a
 * name in the Task Scheduler library.
 *
 * A string and not a `PathBuf` for [`DaemonStatus`](crate::DaemonStatus)' reason — serde
 * refuses a `PathBuf` that is not valid UTF-8 — and here it is often not a path at all.
 */
location: string, 
/**
 * What became of it.
 */
outcome: Removal, };
