// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Priority } from "./Priority";

/**
 * Per-service CPU and memory caps.
 *
 * Applied through the platform layer, which cannot honour all of it everywhere: Windows has Job
 * Objects and Linux has cgroup v2, but **macOS has no hard memory cap**, so a limit there becomes a
 * watchdog rather than a wall. That asymmetry is a fact the GUI must show rather than hide — see
 * `.claude/features/resource-isolation.md`. Enforcement is roadmap task T68; the fields exist now
 * so a spec written before it does not have to be revisited.
 */
export type ResourceLimits = { 
/**
 * A ceiling on CPU, as a percentage of one core. `None` is uncapped.
 */
cpu_percent: number | null, 
/**
 * A ceiling on resident memory, in megabytes. `None` is uncapped.
 */
memory_mb: number | null, 
/**
 * How this service competes for CPU when nothing is capped.
 */
priority: Priority, };
