// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeSource } from "./RuntimeSource";
import type { RuntimeSummary } from "./RuntimeSummary";
import type { VersionConstraint } from "./VersionConstraint";

/**
 * What `runtime.resolve` answers: the installed runtime a command would use here, and why that one.
 *
 * **The reason travels with the answer** rather than being left for a client to reconstruct.
 * "Which PHP is this?" is a question people ask precisely when the answer is surprising, and a
 * version with no account of where it came from sends them looking through four possible sources by
 * hand — which is also four chances for a client to explain it differently from the next one.
 */
export type ResolvedRuntime = { 
/**
 * The installed runtime itself, as [`RuntimeSummary`] describes every other one.
 */
runtime: RuntimeSummary, 
/**
 * Which of the four sources decided it.
 */
source: RuntimeSource, 
/**
 * The constraint that source carried, when it carried one.
 *
 * Absent exactly for [`RuntimeSource::Default`], which names no version: it *is* the version
 * its kind falls back to.
 */
constraint?: VersionConstraint | null, };
