// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What unwiring means, per mechanism.
 *
 * Mirrors [`ResolverPlan`] with only what a removal reads. Every artifact each variant deletes is
 * a constant in the helper, so no variant carries a path.
 */
export type ResolverTarget = { "method": "resolver-directory", } | { "method": "systemd-link", } | { "method": "nrpt", };
