// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * **It carries no nameserver address, no link name and no registry key**, and that is the security
 * decision of the task rather than an economy. `mixengine-elevate` exists because a compromised
 * daemon *is* the attacker, so an operation that accepted an address from the request would be one
 * that let whoever owns the daemon redirect this machine's name resolution anywhere — with a valid
 * signature, through the audited binary, under the user's own Allow click. Every one of those
 * values is compiled into the helper. What travels is the two things the helper cannot know: which
 * of the managed TLDs to wire, and which port the server is listening on.
 *
 * One variant per OS mechanism, as [`PortAccessPlan`] has and for its reason: a field the helper
 * does not use is a field the helper cannot validate.
 */
export type ResolverPlan = { "method": "resolver-directory", 
/**
 * Which TLDs to route. Every one is checked against
 * [`WIRED_TLDS`](crate::domains::WIRED_TLDS) by the helper itself.
 */
tlds: Array<string>, 
/**
 * Where the server is listening.
 *
 * A real field because `[dns] port` is a real setting and a test daemon binds an ephemeral
 * one; bounded rather than trusted, being refused at zero.
 */
port: number, } | { "method": "systemd-link", 
/**
 * Which TLDs become routing domains on that link.
 */
tlds: Array<string>, 
/**
 * Where the server is listening.
 */
port: number, } | { "method": "nrpt", 
/**
 * Which namespaces the rule names.
 */
tlds: Array<string>, };
