// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";
import type { RpcError } from "./RpcError";
import type { Version } from "./Version";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * One answer.
 *
 * Exactly one of `result` and `error` is present, which is why [`ResponseOutcome`] is an enum and not two
 * `Option` fields: the invalid state — both, or neither — is simply not constructible.
 */
export type Response = { 
/**
 * Always `"2.0"`.
 */
jsonrpc: Version, 
/**
 * The id of the request this answers.
 *
 * `None` serialises as `null`, which the spec requires for a body so malformed that the id
 * could not be read out of it — and which is also what a request that spelled its own id
 * `null` gets back, since an answer echoes the id it was given rather than improving on it.
 */
id: Id | null, } & ({ 
/**
 * The method's return value.
 */
result: JsonValue, } | { 
/**
 * Why.
 */
error: RpcError, });
