// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Backoff } from "./Backoff";
import type { Millis } from "./Millis";

/**
 * What to do when a supervised process exits.
 */
export type RestartPolicy = { "type": "never" } | { "type": "on_failure", 
/**
 * How many restarts are allowed inside [`window`](RestartPolicy::OnFailure::window) before
 * the service goes `Failed` and stays there until an explicit `service.start`.
 */
max_retries: number, 
/**
 * The span the retries are counted over. A service that crashes once a day is not in a
 * crash loop, and counting since boot would eventually say it was.
 */
window: Millis, 
/**
 * The wait between attempts.
 */
backoff: Backoff, } | { "type": "always", 
/**
 * The wait between attempts.
 */
backoff: Backoff, };
