// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What became of a rotation — roadmap task **T54**.
 *
 * **Internally tagged and `#[non_exhaustive]`**, as [`CertProblem`] is: a client matches on a word,
 * and a later build may find a fourth thing to say.
 */
export type RotateOutcome = { "outcome": "rotated", } | { "outcome": "not_committed", 
/**
 * What the reading said, in words.
 */
because: string, } | { "outcome": "nothing_to_rotate", 
/**
 * Why not, and what to run instead.
 */
because: string, };
