// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The integer in a JSON-RPC `error` member.
 *
 * A transparent newtype with constants rather than a closed enum, unlike
 * [`ErrorCode`]. The reasoning that made *that* one closed does not apply here:
 * nothing branches on this number — [`ErrorData::code`] is what a client matches on — so an
 * unfamiliar value has nothing to be matched against and is simply carried through instead of
 * being flattened into a wrong one.
 */
export type RpcCode = number;
