// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorData } from "./ErrorData";
import type { RpcCode } from "./RpcCode";

/**
 * The `error` member of a failed [`Response`].
 */
export type RpcError = { 
/**
 * For generic JSON-RPC tooling. See [`RpcCode`].
 */
code: RpcCode, 
/**
 * What happened, phrased for the person reading it, causes included. The same string
 * [`Error::message`] carries, and written exactly once.
 */
message: string, 
/**
 * MixEngine's own classification of the failure, which is what clients branch on.
 *
 * Always present, including on the protocol-level failures above, so a client never has to
 * handle "an error with no code".
 */
data: ErrorData, };
