// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeSummary } from "./RuntimeSummary";

/**
 * What `runtime.uninstall` answers.
 *
 * The runtime **as it was**, plus the one consequence a caller cannot see from it: whether its kind
 * is now left with no default at all.
 */
export type RuntimeRemoval = { 
/**
 * What was removed, as it stood a moment before.
 */
removed: RuntimeSummary, 
/**
 * Whether the kind now has no default version.
 *
 * **True exactly when the removed version was the default**, because nothing is promoted in its
 * place — not because nothing *could* be. Naming the newest remaining version is one call now,
 * and an uninstall still does not get to move what `php` means: the project that would break is
 * the one nobody was thinking about while typing this. So the daemon says out loud that there
 * is no default, and `runtime.set_default` is one call as well.
 */
default_cleared: boolean, };
