// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageVersion } from "./PackageVersion";
import type { RuntimeKind } from "./RuntimeKind";

/**
 * Which runtime a call is about.
 *
 * One params type for `runtime.install`, `runtime.uninstall` and `runtime.set_default`. Both fields
 * are **required** in all three: a kind with no version is not an installable thing, and a call
 * that guessed one — the newest, the default — would be a client deciding something, which is
 * exactly what `CLAUDE.md` puts in the daemon. Choosing a version from a constraint has a method of
 * its own ([`RuntimeQuestion`]) rather than a default hidden in this one, and it answers from what
 * is *installed* — which is why none of these three can take a range: an install picking the newest
 * `8.3` would be picking between versions none of which are here yet.
 */
export type RuntimeTarget = { 
/**
 * Which language.
 */
kind: RuntimeKind, 
/**
 * Which version, exactly as the index publishes it.
 */
version: PackageVersion, };
