// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeSummary } from "./RuntimeSummary";

/**
 * What `runtime.list_installed` answers.
 *
 * An object around the list rather than a bare array, on [`ServiceList`](crate::ServiceList)'s
 * precedent: a field can be added beside it without changing every existing client's parser.
 */
export type RuntimeList = { 
/**
 * What is on this machine, by kind and then by the version string as it was published.
 */
runtimes: Array<RuntimeSummary>, };
