// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageVersion } from "./PackageVersion";
import type { RuntimeKind } from "./RuntimeKind";

/**
 * What `runtime.uninstall` takes: a version, and whether to cross a refusal.
 *
 * Flattened rather than made a field on [`RuntimeTarget`]: that type is also `runtime.install`'s
 * and `runtime.set_default`'s parameter, where a `force` would mean nothing. The flatten keeps
 * today's wire shape and adds one optional key, so an older client's request still parses.
 *
 * **It crosses the project-pin refusal and nothing else** (spec D8). A broken pin is a statement
 * about the future — the next `cd` into that directory fails with a message naming the install
 * that fixes it — and a person who has been shown the affected projects is entitled to decide. A
 * running php-fpm pool is a fact about the present, and no flag buys a live process with no files
 * under it.
 */
export type RuntimeUninstall = { 
/**
 * Remove it even though a registered project pins it.
 */
force?: boolean, 
/**
 * Which language.
 */
kind: RuntimeKind, 
/**
 * Which version, exactly as the index publishes it.
 */
version: PackageVersion, };
