// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeKind } from "./RuntimeKind";
import type { VersionConstraint } from "./VersionConstraint";

/**
 * What `runtime.resolve` asks: which language, from where, and what the caller was already told.
 *
 * **Both optional fields are things only the caller can know**, which is why they are asked for
 * rather than found. The daemon's own working directory is wherever it was started, and its
 * environment is whatever started it — neither is the shell somebody is typing in — so a client
 * sends the directory it is in and the value it read from `--php` or
 * [`RuntimeKind::override_env`], and the daemon does every step that reads a file or a table.
 */
export type RuntimeQuestion = { 
/**
 * Which language is being resolved.
 */
kind: RuntimeKind, 
/**
 * The directory the question is being asked from.
 *
 * Absolute, and refused when it is not: everything found by walking up from it —
 * `mixengine.toml`, a registered project root — would otherwise be walked from the daemon's
 * own directory, which is a different machine's worth of surprise.
 *
 * Absent means *do not look*: a caller with no directory to name is asking what the flag and
 * the default say, and gets exactly that.
 */
cwd?: string | null, 
/**
 * What the caller was told to use, ahead of anything the directory says.
 *
 * A flag or an environment variable, already read by the process the user invoked.
 */
version?: VersionConstraint | null, };
