// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionSource } from "./ExtensionSource";
import type { Linkage } from "./Linkage";

/**
 * One extension, and everything a client needs to render a line about it.
 */
export type RuntimeExtension = { 
/**
 * What it is called.
 */
name: string, 
/**
 * Whether it can be turned off at all.
 */
linkage: Linkage, 
/**
 * Whether it is loaded.
 */
enabled: boolean, 
/**
 * Why it is in that state.
 */
source: ExtensionSource, };
