// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which language runtime something is a version of.
 *
 * **Closed, unlike [`JobKind`](crate::JobKind) and like [`JobState`](crate::JobState).** The set
 * grows only when MixEngine learns to manage another language, which is a release of ours and a
 * migration of the `runtime_installs.kind` `CHECK` — never something a package index gets to
 * extend by publishing. An index naming a fifth one is describing something this build could not
 * install a shim for anyway.
 */
export type RuntimeKind = "php" | "node" | "python" | "ruby";
