// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the version a directory resolves to was decided.
 *
 * The four steps of
 * [runtime-versions.md](../../../../.claude/features/runtime-versions.md)'s order, in that order,
 * each carrying the one thing a person would ask next: *which* file, *which* project.
 */
export type RuntimeSource = { "from": "explicit" } | { "from": "manifest", 
/**
 * The file that pinned it.
 */
path: string, } | { "from": "project", 
/**
 * That project's root directory.
 */
root: string, } | { "from": "default" };
