// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceId } from "./ServiceId";

/**
 * What `service.set_idle` takes.
 *
 * **Three states, spelled on the wire the way the column stores them.** [`None`] restores whatever
 * the recipe wants, `Some(0)` switches idle-stopping off for this service whatever the recipe
 * wants, and `Some(n)` is minutes. They are deliberately not two states: a default arriving in a
 * later release has to reach the home that never touched this setting and must never reach the one
 * whose owner turned it off — see `IdleSource`.
 */
export type ServiceIdleSet = { 
/**
 * The service whose policy this is.
 */
service: ServiceId, 
/**
 * How many minutes it may look idle before it is stopped.
 */
minutes?: number | null, };
