// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a supervised service is doing right now.
 *
 * **Closed, unlike most of the wire vocabulary.** [`crate::DaemonEvent`] is `#[non_exhaustive]`
 * because a later phase invents new things to say; this enum is the state machine itself, and a
 * state machine with room for one more state is one nobody can reason about. The supervisor matches
 * on it exhaustively on purpose, so that adding a state is a compile error at every place that has
 * to decide what to do about it — and `services.state` carries the same closed list as a `CHECK`
 * constraint in the first migration.
 *
 * The wire form is the snake_case name (`"restarting"`, `"failed"`), and it is also **exactly what
 * is stored** in `services.state`: one spelling, produced by [`ServiceState::as_str`] and read back by
 * [`ServiceState::parse`], rather than a serde form and a database form that drift apart on the day
 * somebody renames a variant.
 */
export type ServiceState = "stopped" | "starting" | "running" | "degraded" | "stopping" | "restarting" | "failed";
