// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceLimits } from "./ResourceLimits";
import type { ServiceId } from "./ServiceId";

/**
 * What `service.set_limits` takes.
 *
 * **A complete [`ResourceLimits`], never a patch.** A field left at its default is a field being
 * set to its default — so setting `cpu_percent` alone removes a memory ceiling that was there. That
 * is the specified behaviour rather than an accident: the alternative is a three-way value per
 * field in every reader of limits, or a read-modify-write in a client, which is business logic a
 * client may not hold. `mix service limits set` prints all three fields of the result, which is
 * where the cost of this choice is paid.
 */
export type ServiceLimitsSet = { 
/**
 * The service to cap.
 */
service: ServiceId, 
/**
 * Everything it may take, in full.
 */
limits: ResourceLimits, };
