// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceId } from "./ServiceId";

/**
 * Which service `service.status` is about.
 *
 * Its own type rather than a [`ServiceTarget`] with the option filled in, because the id is
 * **required** here: a status with no subject is a `service.list` that was typed wrongly, and
 * answering it as one would hide the mistake instead of reporting `invalid_params`.
 */
export type ServiceQuery = { 
/**
 * The service to describe.
 */
service: ServiceId, };
