// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceId } from "./ServiceId";

/**
 * Which services a call is about, and whether the caller waits for the answer to be true.
 *
 * One params type for `service.start`, `service.stop` and `service.restart`, because the question
 * each asks is the same one: *which* service, and *how long may this take*.
 */
export type ServiceTarget = { 
/**
 * The service to act on, or [`None`] for every declared service.
 *
 * Naming one does not mean acting on one: a plan is the transitive set, so starting `php-fpm`
 * pulls in what it depends on and stopping `mariadb` pulls in what depends on *it*. What the
 * walk covered comes back in [`ServiceWalk::planned`].
 */
service?: ServiceId | null, 
/**
 * Whether to answer when the walk has finished rather than when it has been accepted.
 *
 * **Defaults to true, and the exit code is why.** `mix service start db && mix …` is a sentence
 * about the database being up; an answer sent before the walk would make it exit `0` for a
 * service that never came up, and the only way for a client to know better would be to re-derive
 * the verdict from the event stream — the business-logic-in-a-client bug `CLAUDE.md` forbids.
 *
 * A GUI sends `false`: it is already subscribed to
 * [`ServiceStateChanged`](crate::DaemonEvent::ServiceStateChanged) and would rather draw each
 * service arriving than block a window on the slowest one. What comes back then is the plan and
 * [`ServiceWalk::complete`] is `false` — the walk itself carries on inside the daemon.
 */
wait?: boolean, };
