// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageVersion } from "./PackageVersion";
import type { ServiceId } from "./ServiceId";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * What `service.create` takes: which service, from which version of its package.
 *
 * **The package is not a field**, because [`ServiceId::name`] already is one: it documents itself
 * as "the part before `@` — the package this is an instance of", so a second parameter would either
 * repeat the id or be a pair somebody has to police for agreement. The invariant is better held by
 * construction than by a check.
 *
 * **The version is required**, on [`RuntimeTarget`](crate::RuntimeTarget)'s reasoning: choosing a
 * version for somebody is a decision, and there is no `service.resolve` to make it.
 *
 * Everything else is optional because the column behind it is nullable and null already means
 * something: a service with no port is one whose recipe renders no port line, and a service with no
 * data directory is one the generator places under `data/<package>` itself.
 */
export type ServiceCreate = { 
/**
 * Which service to create, and — through its name — which package it is an instance of.
 */
id: ServiceId, 
/**
 * Which installed version of that package to run.
 */
version: PackageVersion, 
/**
 * The port it listens on, or [`None`] for the recipe's own default.
 */
port?: number | null, 
/**
 * The address it binds, or [`None`] for `127.0.0.1`.
 */
bind_addr?: string | null, 
/**
 * Where its data lives, or [`None`] for the home's own layout.
 */
data_dir?: string | null, 
/**
 * Whether it starts with the daemon. [`None`] is the column's default, which is no.
 */
autostart?: boolean | null, 
/**
 * The settings this instance overrides, checked against the recipe before the row is kept.
 *
 * A map rather than a [`String`] of JSON: the column holds a document, and a client that had to
 * serialise one itself would be a client that could send something that is not an object.
 */
overrides?: { [key in string]: JsonValue } | null, };
