// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceId } from "./ServiceId";
import type { StateReason } from "./StateReason";

/**
 * The service a walk stopped at, and what was persisted about why.
 */
export type ServiceFailure = { 
/**
 * Which service.
 */
service: ServiceId, 
/**
 * What was written about it, which is the same value the matching
 * [`ServiceStateChanged`](crate::DaemonEvent::ServiceStateChanged) carried.
 *
 * [`None`] when the failure was the daemon's own — a database that would not take the write, a
 * supervising task that panicked. That is in `daemon.log` and is not a state a client could
 * render; a client meeting one says so rather than inventing a reason.
 */
reason?: StateReason | null, };
