// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceFailure } from "./ServiceFailure";
import type { ServiceId } from "./ServiceId";

/**
 * What a `service.start`, `service.stop` or `service.restart` did.
 *
 * **Not a success or a failure**, which is why it is a struct rather than an error: a plan of six
 * services where the fourth fails leaves three running, one failed and two never tried, and a
 * client that has to render that needs all three lists. The failure is still a failure — `mix`
 * exits non-zero on one — but it is a described failure and not a lost walk.
 */
export type ServiceWalk = { 
/**
 * Everything the plan covered, in the order it was walked.
 *
 * This is the transitive set and not what the caller named: it is what a client watches the
 * event stream for, and the only way to know that starting one service is about to touch four.
 */
planned: Array<ServiceId>, 
/**
 * Whether the rest of this answer describes a finished walk.
 *
 * `false` for a call that asked not to wait ([`ServiceTarget::wait`]), where the plan has been
 * accepted and is being walked behind this answer — the three lists below are then empty
 * because nothing has happened yet, not because nothing happened.
 */
complete: boolean, 
/**
 * Services that reached what the walk was aiming for, in the order they got there.
 */
reached: Array<ServiceId>, 
/**
 * The service that stopped the walk, where one did.
 *
 * Always [`None`] for a stop: a service that is not running is already where the caller wants
 * it, so there is no state a stop fails to reach.
 */
failed?: ServiceFailure | null, 
/**
 * Services never tried, because something they depend on failed.
 *
 * Each was recorded as `failed` with
 * [`DependencyFailed`](StateReason::DependencyFailed) naming the direct edge it declared, so a
 * chain of four reads as four sentences leading to the one service to fix.
 */
blocked: Array<ServiceId>, };
