// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvValue } from "./EnvValue";
import type { HealthCheck } from "./HealthCheck";
import type { IdlePolicy } from "./IdlePolicy";
import type { LogPolicy } from "./LogPolicy";
import type { ReadyCheck } from "./ReadyCheck";
import type { ReloadBehaviour } from "./ReloadBehaviour";
import type { ResourceLimits } from "./ResourceLimits";
import type { RestartPolicy } from "./RestartPolicy";
import type { ServiceId } from "./ServiceId";
import type { StopBehaviour } from "./StopBehaviour";

/**
 * Everything needed to run and babysit one process.
 *
 * Built through [`ServiceSpec::builder`], which is where the invariants are checked — see
 * [`ServiceSpecBuilder::build`].
 *
 * **The fields are private and read through accessors**, which is what makes that sentence true
 * rather than merely intended: a public `program` could be reassigned to a relative path after
 * `build` refused one, and a public `depends_on` could be pushed onto until it named the service
 * itself. Nothing needs to mutate a spec — a changed service is a new spec, built and checked the
 * same way — so the ability to is only the ability to get it wrong. Private fields also leave T16,
 * T68 and T69 free to grow the struct, which is what `#[non_exhaustive]` would otherwise be here
 * for.
 *
 * **Deserialisation does not run those checks.** A spec arriving from SQLite or from an
 * `extension.toml` is validated by whoever loads it, at the point where a bad one can be reported
 * against its source; a `Deserialize` impl that refused would fail with no idea which row or which
 * file it was reading. [`ServiceId`] is the exception, and validates either way, because it becomes
 * a directory name. What a loader calls is [`ServiceSpec::validate`] — the same function `build`
 * runs, so there is one definition of "usable" rather than a second one written out by hand.
 */
export type ServiceSpec = { 
/**
 * What this service is called, everywhere.
 */
id: ServiceId, 
/**
 * The binary to execute. Absolute — a spec is never resolved against a `PATH`, because which
 * `PATH` would be ambiguous exactly where it matters.
 */
program: string, 
/**
 * Arguments, already split. Never a command line to be parsed, so a data directory with a space
 * in it needs no quoting and no escaping rule to get wrong.
 */
args: Array<string>, 
/**
 * The child's entire environment.
 *
 * **Not inherited wholesale.** The daemon's own environment carries whatever launched it —
 * a shell's `PATH`, another version manager's hooks, variables from a login session — and a
 * service that behaves differently depending on how the daemon was started is a bug nobody can
 * reproduce.
 */
env: { [key in string]: EnvValue }, 
/**
 * The working directory. Also where a relative path in the service's own config resolves from,
 * which is why it is explicit rather than inherited.
 */
cwd: string, 
/**
 * The TCP ports this service will listen on, as the recipe that rendered it knows them.
 *
 * **Declared rather than derived, and empty is a real answer.** A `ReadyCheck` names an address
 * only for the services that are checked by connecting to one — a database checked by running a
 * query names none, and a web server's admin endpoint is not the port its sites are served on.
 * The recipe wrote the number into the configuration and is the only thing that knows it.
 *
 * What reads this is the diagnosis of a failed start (roadmap task **T38**): the daemon asks
 * the OS who is listening on each of these before it decides what to call the failure. Nothing
 * reserves a port by declaring it here, and nothing binds one — see `service.create` for where
 * a port is *allocated*.
 */
ports: Array<number>, 
/**
 * When traffic may be routed to it.
 */
ready: ReadyCheck, 
/**
 * Whether it is still fine, once it is ready. `None` for a service with nothing cheap to poll.
 */
health: HealthCheck | null, 
/**
 * What to do when it exits.
 */
restart: RestartPolicy, 
/**
 * How to ask it to stop.
 */
stop: StopBehaviour, 
/**
 * How to hand it a configuration that changed while it is running. `None` for a service that
 * reads its configuration once.
 */
reload: ReloadBehaviour | null, 
/**
 * Services that must be ready before this one starts, and that stop after it.
 *
 * The edges of a DAG; a cycle among several specs is caught when they are assembled (roadmap
 * task T17). The one case a single spec can see for itself — depending on itself — is rejected
 * by [`ServiceSpecBuilder::build`].
 */
depends_on: Array<ServiceId>, 
/**
 * CPU and memory ceilings. Enforcement is roadmap task T68.
 */
limits: ResourceLimits, 
/**
 * Whether a memory watchdog may restart this service — roadmap task **T71a**.
 *
 * **The recipe's answer and not a person's.** Whether a program survives being restarted under
 * memory pressure is a property of the program: a php-fpm pool loses the requests in flight,
 * which `pm.max_requests` already recycles workers underneath, and a database loses a
 * transaction. `false` for everything that does not say otherwise, so the permission is opted
 * into and never inherited.
 *
 * It does nothing on its own: nothing watches a service that has declared no `memory_mb`, and
 * nothing watches any service on a machine whose kernel holds the ceiling itself.
 */
restart_over_memory: boolean, 
/**
 * When to stop it for being unused. Enforcement is roadmap task T69.
 */
idle: IdlePolicy | null, 
/**
 * How much of its output to keep. Enforcement is roadmap task T16.
 */
logs: LogPolicy, };
