// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceId } from "./ServiceId";
import type { ServiceState } from "./ServiceState";
import type { StateReason } from "./StateReason";
import type { Timestamp } from "./Timestamp";

/**
 * One move of the state machine: what changed, why, and when.
 *
 * The same value is written to `services.state` and published as
 * [`crate::DaemonEvent::ServiceStateChanged`], which is the only reason this is a type rather than
 * four arguments. `mixengine-core` returns one from the transaction that persisted it and the
 * daemon publishes exactly that — so the row and the event are not two descriptions of an event
 * that can disagree, they are one description used twice.
 */
export type ServiceTransition = { 
/**
 * Which service moved.
 */
service: ServiceId, 
/**
 * Where it was. Carried rather than left for the client to remember, because an event stream
 * is best-effort: a client that missed the previous one still gets a complete sentence.
 */
from: ServiceState, 
/**
 * Where it is now.
 */
to: ServiceState, 
/**
 * What caused it.
 */
reason: StateReason, 
/**
 * When it happened, as read by the caller that made the move.
 *
 * Carried by the event, not stored: `services` keeps only the state a restart has to recover,
 * and no column holds the moment of a transition. This is what orders the lines in a GUI's
 * activity list within one run of the daemon, and it is supplied rather than read from the
 * clock here so that a test can say when.
 */
at: Timestamp, };
