// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A service's human-stable identity: `caddy`, `mariadb@main`, `php-fpm@8.3`.
 *
 * Validated on construction *and* on deserialisation, because this string is not only an
 * identifier. It names a directory — `logs/services/<id>/`, `etc/<id>/` — so a value containing a
 * path separator, or one Windows refuses as a filename, is a broken install rather than a bad
 * lookup. The charset is narrow enough that the interesting cases cannot be spelled at all.
 */
export type ServiceId = string;
