// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrontEndServer } from "./FrontEndServer";

/**
 * What a service is *for*, where two packages can be for the same thing — roadmap task **T97**.
 *
 * The wire half of `mixengine-core`'s `Role`, which is what a recipe answers and what
 * `service.create` refuses a second front end by (**T37**).
 *
 * **[`FrontEnd`](Self::FrontEnd) carries which of the two it is, and that is the whole point.**
 * Without the payload a client that wanted to draw a two-way switch would be back where it started:
 * it would know that `caddy` is a front end and have no way to name the other one but by writing
 * the string. With it, the value read off the active row is the value
 * [`FrontEndSwitch::server`] takes, and
 * [ADR 0026](https://github.com/mixnz/mixengine/blob/master/.claude/decisions/0026-the-active-front-end-is-a-row-and-switching-it-is-a-job.md)'s
 * *no client may map a package name to a role* is something a client can obey.
 *
 * Only the one distinction, because only one exists: every other recipe is a server a home may run
 * beside any of the others.
 */
export type ServiceRole = { "role": "front_end", 
/**
 * Which of them, as the value a switch is asked for by.
 */
server: FrontEndServer, } | { "role": "other", };
