// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortMoved } from "./PortMoved";
import type { ServiceSummary } from "./ServiceSummary";

/**
 * What `service.create` answers: the service, and the port story where there is one.
 *
 * **Its own type rather than a [`ServiceSummary`]** — roadmap task **T34c** — because a create
 * answers two different questions and only one of them is true forever. What the service *is*
 * outlives the call and is a [`ServiceSummary`]; why it is not on the port its recipe prefers is
 * true only of this moment, and a field for it on every listing would be a sentence about a
 * decision nobody is making any more.
 */
export type ServiceCreation = { 
/**
 * The service that now exists, as `service.status` would answer it.
 */
service: ServiceSummary, 
/**
 * Why its port is not the one its recipe asked for, when it is not.
 */
moved_from?: PortMoved | null, };
