// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceId } from "./ServiceId";

/**
 * Which service `service.delete` is about, and whether a site declaring it may be crossed.
 *
 * Flattened over [`ServiceQuery`] on [`crate::RuntimeUninstall`]'s precedent: the same wire shape
 * every client has sent since T31a, plus one optional key an older client's request parses without.
 *
 * **`force` crosses a declaration and never a process** (spec D4). A site naming this service is a
 * statement about the next `site.start`, which somebody shown the sites is entitled to overrule; a
 * running service is a fact about now, and no flag buys it.
 */
export type ServiceDelete = { 
/**
 * Delete it even though a site declares it.
 */
force?: boolean, 
/**
 * The service to describe.
 */
service: ServiceId, };
