// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceSummary } from "./ServiceSummary";

/**
 * What `service.delete` answers: what went, and what deliberately did not.
 *
 * **A delete removes a row and a configuration directory, and never a data directory.** Generated
 * config is disposable and can be rendered again from the row; a data directory is somebody's
 * databases, and there is no undo behind a local development tool. So the path is *named* rather
 * than removed, because a directory nobody was told about is a directory nobody ever cleans up.
 */
export type ServiceRemoval = { 
/**
 * The service as it stood before its row went, which is the only moment anything could describe
 * it.
 */
removed: ServiceSummary, 
/**
 * The data directory left in place, when there was one on disk to leave.
 */
data_kept?: string | null, };
