// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceSummary } from "./ServiceSummary";

/**
 * What `service.list` answers.
 *
 * An object around the list rather than a bare array, on [`crate::DaemonStatus`]'s precedent: a
 * field can be added beside it — a count, a note about where the declarations came from — without
 * changing the shape of every existing client's parser.
 */
export type ServiceList = { 
/**
 * Every declared service, in [`ServiceId`] order.
 */
services: Array<ServiceSummary>, };
