// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LimitSupport } from "./LimitSupport";
import type { MemoryWatchdog } from "./MemoryWatchdog";
import type { ResourceLimits } from "./ResourceLimits";
import type { ServiceId } from "./ServiceId";

/**
 * What `service.limits` and `service.set_limits` both answer.
 *
 * **One report for a read and a write**, because the answer to "what are this service's limits" is
 * the same shape as the answer to "what are they now" — and because a client that has just written
 * one needs to be told what the machine will do with it just as much as one that has only read it.
 */
export type ServiceLimitsReport = { 
/**
 * Which service this is about.
 */
service: ServiceId, 
/**
 * What has been asked for. Stored whether or not this machine can enforce it — see
 * [`support`](Self::support), and the T68 design, D10.
 */
limits: ResourceLimits, 
/**
 * What this machine will actually do with each field of it.
 */
support: LimitSupport, 
/**
 * What is watching this service's ceiling, where nothing enforces it — task **T71a**.
 *
 * [`None`] means nothing is watching, which is two different situations with one answer: this
 * machine caps `memory_mb` itself, or this service has not declared one. A client that drew a
 * watchdog for either would be describing a loop that never runs.
 */
watchdog?: MemoryWatchdog | null, };
