// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a site's sharing changed — roadmap task **T76**.
 *
 * **Internally tagged under `kind`, not `type`.** It travels inside
 * [`DaemonEvent::SiteSharingChanged`](crate::DaemonEvent), which is itself tagged `type`, and two
 * discriminators spelled the same word collide the moment the outer variant flattens — the lesson
 * [`JobFinish`](crate::JobFinish) paid for with `ending`.
 */
export type SharingChange = { "kind": "requested", } | { "kind": "expired", } | { "kind": "network_changed", 
/**
 * The address that was bound and written into the certificate.
 */
was: string, 
/**
 * What the interface holds now, or [`None`] where the interface itself is gone.
 */
now?: string | null, };
