// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the signature check found when a blueprint arrived — roadmap task **T79b**.
 *
 * **Evidence beside an answer, never the answer.** [`BlueprintSummary::trusted`] is what decides
 * whether a `[scaffold]` command may be offered; this says which of three things happened. A file
 * that came with nothing and a file whose signature did not verify are both untrusted and are not
 * the same event: the second is the one the gallery key exists to catch, and today both reach a
 * person as one sentence.
 *
 * Three words rather than four: "signed by another key" is told from "signed by the gallery and
 * then edited" only by the key id inside the `.minisig`, and **a key id is not authenticated** —
 * whoever edits the file edits the key id with it. A message that branched on it would be a
 * message its subject chooses.
 */
export type SignatureCheck = "verified" | "missing" | "rejected";
