// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceId } from "./ServiceId";
import type { ServiceState } from "./ServiceState";

/**
 * One service a site declares.
 */
export type SiteServiceLink = { 
/**
 * Which service.
 */
service: ServiceId, 
/**
 * What it is doing, so a listing does not need a second call per link.
 */
state: ServiceState, };
