// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Timestamp } from "./Timestamp";

/**
 * A site the local network can reach, and how — roadmap task **T74**.
 */
export type SiteSharing = { 
/**
 * The interface it is shared on, by the name the OS gives it.
 */
interface: string, 
/**
 * The IPv4 address bound, certified and printed. IPv4 only — the T74 design, D4.
 */
address: string, 
/**
 * What to open, ready to hand to a browser or draw as a QR code.
 *
 * **HTTP, and the address rather than the name** — the T75 design, D11. The certificate covers
 * this address and this site's [`name`](Self::name) both, but a phone does not trust this
 * home's authority until it has installed it from [`ca_url`](Self::ca_url), and Android's
 * resolver does not answer `.local` for a browser. A URL a person is told to open must be one
 * that opens, on the device they happen to be holding.
 */
url: string, 
/**
 * The mDNS name this site answers to, `<slug>-mixengine.local` — roadmap task **T75**.
 *
 * **One label before `.local`**, which is measured rather than chosen: a multi-label name
 * under `.local` does not resolve. Present whenever the site is shared and its primary domain
 * yields a label, whatever the responder is doing — the name is in the configuration and in
 * the certificate either way, and [`advertised`](Self::advertised) is the separate question of
 * whether anything is answering for it.
 */
name: string | null, 
/**
 * Whether this daemon is currently answering mDNS queries for [`name`](Self::name).
 *
 * `false` on a home where UDP 5353 could not be bound, or where a firewall blocks it. The
 * share still works by address, which is what T74 shipped; a client says so rather than
 * printing a name as though it resolved.
 */
advertised: boolean, 
/**
 * Where a phone downloads this home's certificate authority — roadmap task **T75**.
 *
 * Served by the front end from this site's own block, and only while the site is shared. The
 * public certificate and nothing else: the signing key is not in any directory a front end is
 * pointed at.
 */
ca_url: string, 
/**
 * When sharing began.
 */
since: Timestamp, 
/**
 * When this share ends by itself, or [`None`] for one that does not — roadmap task **T76**.
 *
 * Set by `--for`, and measured from [`since`](Self::since) rather than from the request that
 * set it. A share also ends when this machine leaves the network it was shared on, which is
 * not a deadline and so is not here — it arrives as
 * [`SiteSharingChanged`](crate::DaemonEvent::SiteSharingChanged) when it happens.
 */
until?: Timestamp | null, };
