// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SiteRef } from "./SiteRef";

/**
 * Which site `site.show` and `site.delete` are about.
 */
export type SiteQuery = { 
/**
 * Which site.
 */
site: SiteRef, };
