// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SitePool } from "./SitePool";
import type { SiteServiceLink } from "./SiteServiceLink";
import type { SiteSummary } from "./SiteSummary";

/**
 * One site, and everything only a lookup can answer.
 */
export type SiteDetail = { 
/**
 * The site itself.
 */
site: SiteSummary, 
/**
 * The owner's root: the project's directory, or the extension's install directory (roadmap
 * task **T81b**).
 */
root: string, 
/**
 * Root plus doc root, as the filesystem spells it.
 */
doc_root_full: string, 
/**
 * Whether that directory is there.
 *
 * **Reported, never refused** (spec D2): a colleague's `public/` is built by `npm run build`,
 * and a create that refused it would refuse the case the import path exists for.
 */
doc_root_exists: boolean, 
/**
 * Every domain, ordered, the head being the primary.
 */
domains: Array<string>, 
/**
 * The php-fpm pool, both answers, for a php-fpm site.
 */
pool?: SitePool | null, 
/**
 * The services it declares, and what each is doing.
 */
services: Array<SiteServiceLink>, };
