// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SiteSummary } from "./SiteSummary";

/**
 * What `site.list` answers.
 */
export type SiteList = { 
/**
 * Every site asked for, in primary-domain order.
 */
sites: Array<SiteSummary>, };
