// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which site a call is about.
 */
export type SiteRef = { "domain": string } | { "path": string };
