// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SiteRef } from "./SiteRef";

/**
 * Which site to put on the local network, and on which interface — roadmap task **T74**.
 */
export type SiteShare = { 
/**
 * Which site.
 */
site: SiteRef, 
/**
 * The interface to share on, by the name this machine gives it.
 *
 * [`None`] where the machine has exactly one candidate, which is the ordinary case. Where it
 * has more than one the daemon refuses and names them all rather than choosing — a machine
 * that picked would put a site on a network the user did not mean to be on.
 */
interface?: string | null, 
/**
 * How long this share should last, in seconds, or [`None`] for one with no end — roadmap task
 * **T76**.
 *
 * **Measured from when the share began and not from this request** — the T76 design, D6. T74
 * preserves `shared_since` across a repeated share precisely so that typing the command again
 * extends nothing, and a deadline that restarted would undo that. A value that lands in the
 * past is refused rather than honoured: a URL that is dead by the time it is printed is worse
 * than a sentence saying so.
 */
for_seconds?: number | null, };
