// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CertProblem } from "./CertProblem";
import type { CertState } from "./CertState";
import type { Handshake } from "./Handshake";

/**
 * One site: what is on disk, what the server presents, and what is wrong if anything is.
 */
export type SiteCertStatus = { 
/**
 * The site, by its primary domain.
 */
domain: string, 
/**
 * Every name this site declares, in the order it declares them.
 */
domains: Array<string>, 
/**
 * The certificate in `certs/sites/`.
 */
disk: CertState, 
/**
 * The certificate the running front end presents for this name.
 */
handshake: Handshake, 
/**
 * The one condition worth acting on, if there is one.
 */
problem: CertProblem | null, };
