// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SiteDetail } from "./SiteDetail";

/**
 * What `site.create` answers.
 */
export type SiteCreation = { 
/**
 * The site that now exists, as `site.show` would answer it.
 */
site: SiteDetail, };
