// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the web server should have a server block for this site.
 *
 * Two words, because a site is not a process: `starting`, `running` and `failed` belong to the
 * services it uses, which have seven states of their own.
 */
export type SiteState = "enabled" | "disabled";
