// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Timestamp } from "./Timestamp";

/**
 * One site's certificate.
 *
 * **There is no `certificate_pem` and there is no field a private key could travel in.** [`Ca`]
 * carries its PEM because a client installs it; nothing installs a leaf, so the field would be
 * surface with no caller — and `.claude/architecture/security-model.md`'s guarantee is easier to
 * keep on a type with fewer fields.
 */
export type SiteCert = { 
/**
 * The distinguished name, as X.509 spells it.
 */
subject: string, 
/**
 * Every name it covers, in the order it covers them.
 */
sans: Array<string>, 
/**
 * The authority that signed it, as X.509 spells the name.
 *
 * **The fourth question the issuer asks is a comparison of this against the authority's own
 * subject** — the T50 design, D6 — which is free because T48 put the key's identity into that
 * name. On the wire rather than derived only where it is needed, because `mix cert status`
 * (T53) has to be able to show a person *which* authority signed a certificate they cannot get
 * a padlock for.
 */
issuer: string, 
/**
 * SHA-256 of the certificate's DER, lowercase hex, no separators.
 */
fingerprint: string, 
/**
 * When it starts being valid.
 */
not_before: Timestamp, 
/**
 * When it stops.
 */
not_after: Timestamp, 
/**
 * Whole days from now until [`not_after`](Self::not_after).
 *
 * **Signed, and allowed to be negative**, for [`Ca::days_left`]'s reason: an expired
 * certificate is a true statement about one that exists and parses.
 */
days_left: number, };
