// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionId } from "./ExtensionId";

/**
 * Who a site belongs to — roadmap task **T81b**.
 *
 * **A replacement for the old `project: String`, not an option beside it.** Two optionals a reader
 * has to agree about is the shape this codebase spends triggers avoiding. A project is named by
 * its wire handle; an extension by its id, which is also the argument `mix extension uninstall`
 * takes — the one thing a person can do to a site they cannot edit.
 */
export type SiteOwner = { "type": "project", 
/**
 * The project's name.
 */
name: string, } | { "type": "extension", 
/**
 * The extension's id.
 */
id: ExtensionId, };
