// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceId } from "./ServiceId";

/**
 * What the row names, and what the resolver would name today.
 *
 * **Two fields because the row cannot remember who chose it.** A pool is frozen at create while the
 * project's shell keeps following the default, so 8.3.35 arriving tomorrow moves the shell and not
 * the site — and these two side by side are how a person sees that rather than guesses at it.
 */
export type SitePool = { 
/**
 * What the row holds. [`None`] after a `service.delete --force` took the pool away.
 */
declared?: ServiceId | null, 
/**
 * What `core::resolve` answers at this root today, when it answers.
 */
resolved?: ServiceId | null, };
