// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectRef } from "./ProjectRef";

/**
 * Which sites a listing should answer with.
 */
export type SiteListQuery = { 
/**
 * One project's sites, or every site in this home.
 */
project?: ProjectRef | null, };
