// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CertState } from "./CertState";
import type { IssueOutcome } from "./IssueOutcome";

/**
 * One site, and what happened to its certificate.
 */
export type SiteCertOutcome = { 
/**
 * The site, by its primary domain.
 */
domain: string, 
/**
 * What was done.
 */
outcome: IssueOutcome, 
/**
 * What is on disk afterwards.
 */
state: CertState, };
