// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SiteKind } from "./SiteKind";
import type { SiteOwner } from "./SiteOwner";
import type { SiteSharing } from "./SiteSharing";
import type { SiteState } from "./SiteState";

/**
 * One site, as a listing shows it.
 */
export type SiteSummary = { 
/**
 * Its primary domain, which is also how it is addressed.
 */
domain: string, 
/**
 * Who it belongs to.
 */
owner: SiteOwner, 
/**
 * What it serves.
 */
kind: SiteKind, 
/**
 * Relative to the project's root, as stored. `""` is the root itself.
 */
doc_root: string, 
/**
 * Whether HTTPS is declared.
 */
https: boolean, 
/**
 * Whether the plaintext address redirects to the HTTPS one — roadmap task **T98**.
 */
https_redirect: boolean, 
/**
 * Whether the web server should serve it.
 */
state: SiteState, 
/**
 * Where the local network can reach it, when it can — roadmap task **T74**.
 *
 * **On the summary and not only on the detail**, because "what is exposed right now" is a
 * question about every site at once: a list that could not answer it would make a client ask
 * per site, and the one thing a person wants at a glance is whether *anything* is shared.
 */
sharing?: SiteSharing | null, };
