// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceId } from "./ServiceId";

/**
 * What a site serves, and what that kind needs to know.
 *
 * **Internally tagged**, which is what lets one definition read a JSON-RPC request and a flat
 * `[site]` table in TOML with no conversion in between (spec D7).
 */
export type SiteKind = { "kind": "php-fpm", 
/**
 * The pool, which the daemon fills from `core::resolve` when a create does not name one.
 *
 * [`None`] means *this site names no pool*, in both directions: on the way in, decide it;
 * on the way out, the pool it named has been deleted (spec D3).
 */
pool?: ServiceId | null, } | { "kind": "static" } | { "kind": "reverse-proxy", 
/**
 * An absolute `http` or `https` URL with a host. A path is allowed; a query is not.
 */
upstream: string, } | { "kind": "node-app", 
/**
 * The loopback port it listens on.
 */
port: number, };
