// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SiteSummary } from "./SiteSummary";

/**
 * What `site.delete` answers.
 */
export type SiteRemoval = { 
/**
 * The site as it stood before its row went.
 */
removed: SiteSummary, 
/**
 * Freed for another site, and said out loud.
 */
domains_released: Array<string>, 
/**
 * The files were never ours — [`crate::ProjectRemoval::root_kept`]'s rule.
 */
doc_root_kept: string, };
