// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Millis } from "./Millis";
import type { ServiceId } from "./ServiceId";

/**
 * Why a service changed state.
 *
 * `#[non_exhaustive]`, unlike [`ServiceState`], and the asymmetry is the point: the set of states
 * is fixed by the machine, while the set of explanations grows every time a later phase learns to
 * distinguish two failures a user currently sees as one. A client renders what it knows and shows
 * the state alone for what it does not.
 *
 * Every variant here is an edge in [`ServiceState::can_become`]. What is deliberately *not* here is
 * anything the code that would emit it does not exist for yet — which is why [`StateReason::Idle`]
 * arrived with T69 and not before, rather than being declared as a promise the build did not keep.
 */
export type StateReason = { "kind": "requested" } | { "kind": "ready" } | { "kind": "ready_timeout", 
/**
 * How long it was given, so the message can be "no TCP connect within 10 s" rather than
 * "timed out" — the number is what tells the user whether to raise it or fix the service.
 */
after: Millis, } | { "kind": "port_in_use", 
/**
 * The port, which is the only field that is always known.
 */
port: number, 
/**
 * The process holding it, where this account may learn it.
 */
pid: number | null, 
/**
 * The file name of that process's program, where this account may read it.
 */
program: string | null, } | { "kind": "spawn_failed" } | { "kind": "first_run_failed", 
/**
 * What went wrong, in the words of whatever refused: a machine with no credential store, a
 * data directory that is not ours, a bootstrap that exited non-zero.
 */
detail: string, } | { "kind": "uncheckable", 
/**
 * What was asked for, e.g. `"an HTTP ready check"`.
 */
check: string, 
/**
 * Why it cannot be made, phrased for whoever wrote the spec.
 */
reason: string, } | { "kind": "dependency_failed", 
/**
 * The dependency that did not come up.
 *
 * The *direct* one this service names, not the root of the chain. Each service reports the
 * edge it declared, so a chain of four reads as four honest sentences that lead to the one
 * service that actually broke, rather than three copies of a name none of them mention.
 */
dependency: ServiceId, } | { "kind": "unhealthy" } | { "kind": "healthy" } | { "kind": "exited", 
/**
 * The exit status, or `None` where the OS does not report one — a Unix process killed by a
 * signal has no exit code, and reporting `0` for it would say "clean exit" about a crash.
 */
code: number | null, } | { "kind": "backoff_elapsed", 
/**
 * Which attempt this is since the last time the service was healthy, counted from 1. It is
 * what makes "restarting (3 of 5)" possible, which is the sentence that tells a user
 * whether to keep waiting.
 */
attempt: number, } | { "kind": "crash_loop", 
/**
 * How many attempts were made.
 */
attempts: number, 
/**
 * The window they were counted in. Both numbers, because "5 failures" means nothing
 * without "in 5 minutes" — a service that crashes once a day is not in a crash loop.
 */
window: Millis, 
/**
 * The last lines the service printed before the supervisor gave up, oldest first.
 *
 * **The one variant that carries evidence, and the one that has to.** Everything else here
 * explains itself — a ready timeout says how long it waited, an exit says what it exited
 * with — while "it kept crashing" explains nothing at all without the line that says
 * `Address already in use`. Attaching it to the reason is what lets the GUI answer *why*
 * where the user is already looking, instead of sending them to a log viewer to find out
 * whether it is worth reading.
 *
 * Bounded by the supervisor (200 lines) rather than by the ring, so an event is never the
 * size of a log file. Empty is a real answer: a service that said nothing before it died.
 */
tail: Array<string>, } | { "kind": "vanished" } | { "kind": "unadopted", 
/**
 * Which of those was missing, phrased for whoever reads the service list.
 *
 * A sentence rather than a code for the reason [`StateReason::Uncheckable`] carries one:
 * the daemon knows why and the client is only laying it out, and the two reasons a
 * survivor is refused — nothing declares it any more, and a state adoption cannot resume —
 * are not a vocabulary anything branches on.
 */
reason: string, } | { "kind": "idle", 
/**
 * How long it was declared idle after.
 *
 * The policy's duration and not the observed one, which are the same number only when the
 * sweep period divides it — and the useful one is the setting a person would change.
 */
after: Millis, } | { "kind": "over_memory", 
/**
 * What it was measured holding, in bytes.
 *
 * The finished minute's *average*, which is what the watchdog judges — a service twice its
 * usual size for five seconds is a service doing its work. The peak is in the metrics
 * history for whoever wants it.
 */
rss_bytes: number, 
/**
 * The ceiling it was judged against, in megabytes, exactly as declared.
 */
limit_mb: number, };
