// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What happened to one step.
 *
 * **A step is reported by what became true, not by how many calls it took** (the T78 design, D3):
 * one daemon call can make several steps true at once — `site.create` writes the row, queues the
 * hosts entry and issues the certificate — and the steps that follow it report
 * [`AlreadyTrue`](Self::AlreadyTrue).
 */
export type StepResult = { "result": "done" } | { "result": "already_true" } | { "result": "not_run", 
/**
 * The reason, in the words a client prints.
 */
why: string, } | { "result": "failed", 
/**
 * What became of it, in the words a client prints: the exit code, and the last thing the
 * command had to say.
 */
why: string, };
