// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanAction } from "./PlanAction";
import type { StepResult } from "./StepResult";

/**
 * One step, and what became of it.
 */
export type StepOutcome = { 
/**
 * What it was.
 */
action: PlanAction, 
/**
 * What happened.
 */
result: StepResult, };
