// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Millis } from "./Millis";

/**
 * How to ask a service to stop before making it.
 *
 * Every variant ends the same way: when the grace period expires the process group is killed. What
 * differs is what is tried first.
 */
export type StopBehaviour = { "type": "signal", 
/**
 * How long to wait for it to leave on its own.
 */
grace: Millis, } | { "type": "command", 
/**
 * The program to run.
 */
program: string, 
/**
 * Its arguments.
 */
args: Array<string>, 
/**
 * How long to wait for it to work.
 */
grace: Millis, } | { "type": "kill" };
