// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which of a service's two streams a line came from.
 *
 * **Closed, where most of this crate is `non_exhaustive`.** A process has exactly two output
 * streams and that is fixed by the three operating systems rather than by this protocol, so a
 * client is safe to match both arms and be done — the same reasoning that closes
 * [`ServiceState`](crate::ServiceState) while the reasons around it stay open.
 */
export type Stream = "stdout" | "stderr";
