// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A moment, as milliseconds since the Unix epoch.
 *
 * Not [`SystemTime`], whose serde representation is a two-field object nobody would choose, and not
 * an RFC 3339 string, which cannot be produced without a date library — and the crate list in
 * `.claude/standards/rust.md` has none, because until now nothing needed one. A number is
 * unambiguous, sorts, needs no parser, and is `new Date(ms)` in the GUI.
 *
 * Milliseconds rather than seconds because log lines (roadmap task T14) arrive faster than one a
 * second and would otherwise all carry the same timestamp; signed rather than unsigned because a
 * machine whose clock is set before 1970 should produce a strange number instead of a panic.
 */
export type Timestamp = number;
