// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which authority to take back out, and **not which certificate** — the T49a design, D5.
 *
 * **There is no fingerprint field, and that is the whole of this type's security decision.** The
 * install direction is close to harmless: a daemon compromised badly enough to forge one already
 * holds the private key of the authority this machine trusts, and can sign any certificate for any
 * name without installing a second root. A *removal* that named a certificate by its hash is not —
 * it could take out the root that validates Windows Update, or an organisation's own root, through
 * the audited binary and under the user's own Allow click.
 *
 * So what travels is T48's key-id: eight lowercase hex characters, refused by the helper before a
 * store is opened, and unable to describe a corporate root at all. The helper then finds
 * certificates whose subject is exactly `MixEngine Local CA <key_id>`, checks each against D4's
 * table, and removes only those that pass. This is [`ResolverPlan`]'s own argument one capability
 * along: the value an attacker would abuse is not validated, it is absent.
 */
export type TrustTarget = { "method": "system-root", 
/**
 * Eight lowercase hex characters, and nothing else is accepted.
 */
key_id: string, } | { "method": "system-keychain", 
/**
 * As [`SystemRoot`](Self::SystemRoot).
 */
key_id: string, } | { "method": "ca-certificates", 
/**
 * As [`SystemRoot`](Self::SystemRoot).
 */
key_id: string, } | { "method": "ca-trust-anchors", 
/**
 * As [`SystemRoot`](Self::SystemRoot).
 */
key_id: string, };
