// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How this machine is asked to trust MixEngine's own certificate authority — roadmap task **T49a**.
 *
 * **The certificate's DER travels; a path to it does not.** [`ResolverPlan`] above carries the
 * argument in full: what the helper can know is compiled into the helper, and a path is somebody
 * else choosing which file root reads after root has decided to trust the request. The destination
 * store, the file name on Linux and the update command are all constants in `mixengine-elevate`.
 *
 * One variant per OS mechanism, as [`PortAccessPlan`] and [`ResolverPlan`] have and for their
 * reason: a plan naming a mechanism is a plan the helper re-validates against the machine it is
 * actually running on.
 */
export type TrustPlan = { "method": "system-root", 
/**
 * The certificate, DER. Checked against the T49a design's D4 table by the helper itself,
 * before a store is opened.
 */
der: Array<number>, } | { "method": "system-keychain", 
/**
 * As [`SystemRoot`](Self::SystemRoot).
 */
der: Array<number>, } | { "method": "ca-certificates", 
/**
 * As [`SystemRoot`](Self::SystemRoot).
 */
der: Array<number>, } | { "method": "ca-trust-anchors", 
/**
 * As [`SystemRoot`](Self::SystemRoot).
 */
der: Array<number>, };
