// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether this machine holds MixEngine's certificate authority in its own trust store.
 *
 * **This says "is it in the store", not "does a browser trust it".** Firefox and Chrome on Linux
 * read NSS databases and not the system store at all — that is T49b — and a browser already running
 * may not re-read a store it has cached. The honest end-to-end answer is a live TLS handshake,
 * which is `mix cert status`' job (T53).
 * **A nested object rather than a flattened one, unlike [`CaState`] above.** Two reasons, and both
 * are about this type rather than about taste: `Trust::NotInstalled` and `CaState::Unusable` both
 * spell their reason `because`, so flattening would let one silently overwrite the other on the one
 * screen that has to say what is wrong; and the two are about different subjects — the certificate,
 * and the machine — where `CaStatus`' single field was about one. A client reads
 * `status.trust.state`.
 */
export type Trust = { "state": "installed", 
/**
 * Which store, in words a person can go and look in.
 */
store: string, } | { "state": "not_installed", 
/**
 * Which store, and why it is not there — `mix doctor` reports the same sentence.
 */
because: string, } | { "state": "no_store", 
/**
 * Which of those it is, in words.
 */
because: string, } | { "state": "unknown", 
/**
 * What went wrong reading it.
 */
because: string, };
