// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Residue } from "./Residue";

/**
 * What an uninstall found, and what became of each thing.
 *
 * **No `granting` field, where [`RepairReport`](crate::RepairReport) has one.** That method raises
 * its prompt as a job of its own and hands the caller its id; this one *is* a job, and raises the
 * prompt inside itself — so the job a caller would be pointed at is the job they are already
 * following. A field that could only ever be null is a field every client has to handle for
 * nothing. What is waiting when no prompt was raised is on the rows, as
 * [`Removal::Enqueued`].
 */
export type UninstallReport = { 
/**
 * One entry per thing MixEngine can have written, in a fixed order, whatever each answered.
 *
 * Eleven of the twelve ids appear exactly once. [`ResidueId::RelocatedDirectory`] appears once
 * per directory `[paths]` has moved out of the root, and on an ordinary home not at all.
 */
items: Array<Residue>, };
