// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What became of a removal — roadmap task **T54**.
 */
export type UninstallOutcome = { "outcome": "removed", } | { "outcome": "partly_removed", 
/**
 * Which store still holds it, and why it was not taken out.
 */
because: string, } | { "outcome": "nothing_to_remove", 
/**
 * Why not.
 */
because: string, };
