// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One published release, as a person reads it before deciding.
 */
export type UpdateRelease = { 
/**
 * The version offered.
 */
version: string, 
/**
 * When it was published, as `YYYY-MM-DDTHH:MM:SSZ`.
 *
 * A string for [`DaemonStatus`](crate::DaemonStatus)' reason: it is for reading, and nothing
 * here joins or subtracts it.
 */
published_at: string, 
/**
 * What changed.
 */
notes: string, 
/**
 * Where the notes somebody may have edited after the release was signed live.
 */
notes_url?: string | null, 
/**
 * How large the payload for *this* machine is, in bytes.
 *
 * Zero when this release has no build for this machine, which is the case
 * [`UpdateStatus::because`] names.
 */
size: number, };
