// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where this copy of MixEngine is installed, and what that means for updating it.
 */
export type UpdatePlacement = { "kind": "self_updatable", 
/**
 * The directory holding them. A string, for [`UpdateRelease::published_at`]'s reason.
 */
directory: string, } | { "kind": "managed", 
/**
 * Where it is.
 */
directory: string, 
/**
 * Why MixEngine will not replace it, phrased for a person and rendered unchanged.
 */
because: string, };
