// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `update.apply` takes.
 */
export type UpdateApply = { 
/**
 * The version the client showed the user.
 *
 * **The daemon refuses if this is no longer what the feed offers.** Without it, a check that
 * landed between the prompt and the answer would install something nobody read the notes for.
 */
version: string, };
