// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The one line `daemon.status` carries about updates.
 *
 * **Deliberately smaller than [`UpdateStatus`]**: `mix status` prints one sentence and everything
 * else about an update belongs to `update.status`, which is a screen. The same split
 * [`DaemonStatus::elevation`](crate::DaemonStatus::elevation) already makes.
 */
export type UpdateOffer = { 
/**
 * The version waiting.
 */
version: string, 
/**
 * When it was published, as `YYYY-MM-DDTHH:MM:SSZ`.
 */
published_at: string, };
