// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The two answers that are not *install*.
 *
 * **Both are real and both are remembered** — `.claude/features/updates.md`. A decline that was
 * forgotten is a prompt that comes back tomorrow, which is how an update prompt becomes something
 * people dismiss without reading.
 */
export type UpdateDecision = "skip" | "later";
