// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `update.check` takes.
 */
export type UpdateCheck = { 
/**
 * Go to the network even if what is cached is still fresh.
 *
 * What `mix self-update --check` sets, because `.claude/features/updates.md` says that command
 * forces an immediate check. The daemon's own startup check leaves it `false`, so a daemon
 * restarted ten times in an hour makes one request.
 */
force: boolean, };
