// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceId } from "./ServiceId";

/**
 * What an update did on its way out.
 *
 * **The last thing a client hears from the daemon it just replaced.** The connection closes a
 * moment later, which *is* the update rather than a failure of it — the same shape
 * [`DaemonShutdown`](crate::DaemonShutdown) has, and for the same reason.
 */
export type UpdateApplied = { 
/**
 * The version that was running.
 */
from: string, 
/**
 * The version now on disk.
 */
to: string, 
/**
 * The directory the binaries were replaced in.
 *
 * With [`UpdateApplied::replaced`], this is what a client prints when the new daemon will not
 * start: the `.old` paths, and the command that puts them back.
 */
directory: string, 
/**
 * The binaries that were replaced, by name.
 */
replaced: Array<string>, 
/**
 * The binaries the payload carried that were deliberately not replaced.
 *
 * `mixengine-elevate` always, and anything the payload carries that this install does not have.
 */
kept?: Array<string>, 
/**
 * What was stopped, and what the new daemon will start again.
 */
restarting?: Array<ServiceId>, };
