// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateDecision } from "./UpdateDecision";

/**
 * What `update.decide` takes.
 */
export type UpdateDecide = { 
/**
 * The version being decided about.
 *
 * Named rather than implied, so that skipping the release somebody was shown cannot skip a
 * different one that arrived between the prompt and the answer.
 */
version: string, 
/**
 * What they answered.
 */
decision: UpdateDecision, };
