// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceId } from "./ServiceId";
import type { Timestamp } from "./Timestamp";
import type { UpdatePlacement } from "./UpdatePlacement";
import type { UpdateRelease } from "./UpdateRelease";

/**
 * Everything this daemon knows about updating itself.
 */
export type UpdateStatus = { 
/**
 * The version running now — `CARGO_PKG_VERSION`, the string `mixengined --version` prints.
 */
current: string, 
/**
 * The release the feed names, whether or not it is offered.
 *
 * Present-and-not-offered is a real state and the interesting one: it is what lets a client
 * say *"0.3.0 exists; you skipped it"* rather than *"no update"*.
 */
available?: UpdateRelease | null, 
/**
 * Whether a client should put it in front of somebody.
 */
offered: boolean, 
/**
 * Why not, phrased for a person. [`None`] exactly when [`UpdateStatus::offered`] is `true`.
 */
because?: string | null, 
/**
 * When the feed was last read, or [`None`] on a daemon that has never managed to.
 */
checked_at?: Timestamp | null, 
/**
 * Whether that reading came from a cache the daemon could not refresh.
 *
 * **An answer and not an error**, on `index::Freshness::Stale`'s reasoning: the signature was
 * checked exactly as it would have been on a fresh copy, so an offer made from a document read
 * three days ago is a genuine offer. It is carried because *"checked 3 days ago"* is a
 * different sentence from *"checked just now"*, and a client working that out from
 * [`UpdateStatus::checked_at`] and its own clock would be deriving what the daemon knows.
 */
stale: boolean, 
/**
 * Where this copy of MixEngine lives, and whether it may replace itself.
 *
 * Carried by `update.status` so a client can render the refusal *before* anybody commits to
 * anything, rather than after a download.
 */
placement: UpdatePlacement, 
/**
 * The services an update would stop and start again.
 *
 * What makes a consent prompt able to say *"3 services will be stopped and started again"* —
 * which is `.claude/features/updates.md`'s *"never update while a supervised service is under
 * load without asking"* in the only form that rule can take once consent is always required.
 */
will_restart?: Array<ServiceId>, };
