// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How long something has been going on, in whole seconds.
 *
 * Separate from [`Timestamp`] because it answers a different question and is read differently: a
 * client renders it as "up 3 days", never as a date. Whole seconds because nothing displays an
 * uptime more precisely than that.
 */
export type Uptime = number;
