// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a presented chain validates — roadmap task **T53**.
 *
 * **An enum rather than a `bool` with a sentence beside it**, on [`CaState`]'s shape: the pair has
 * two states nobody means — rejected with no reason, and trusted with one — and this makes every
 * branch that can say why say it.
 */
export type Verdict = { "trust": "trusted", } | { "trust": "rejected", 
/**
 * In words, from the TLS library.
 */
because: string, };
