// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The `"jsonrpc": "2.0"` member.
 *
 * A unit type rather than a `String`, so that a payload claiming another version fails to
 * deserialise instead of being served as if it had said 2.0, and so that the daemon cannot forget
 * to write it.
 */
export type Version = "2.0";
