// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A version somebody asked for, which may name more than one.
 *
 * What a `--version` flag, a `MIXENGINE_PHP`, a `mixengine.toml` pin and a project record all
 * carry. Three forms, which is what
 * [runtime-versions.md](../../../../.claude/features/runtime-versions.md) promises:
 *
 * | Written | Means |
 * | --- | --- |
 * | `8.3.12`, `8.3`, `8` | **a prefix.** Every installed version whose segments begin with these |
 * | `^8.3` | **a caret.** From `8.3.0` up to, but not including, `9.0.0` |
 * | `8.5.0RC1` | **that release exactly**, pre-release and all |
 *
 * One rule holds the first two together and is worth stating out loud, because it is the surprise
 * otherwise: **a constraint with no pre-release in it never selects a pre-release.** `8.5` does not
 * mean `8.5.0RC1`, and neither does `^8.5` — somebody who wants a release candidate names it, which
 * is exactly how it is spelled on the third row.
 *
 * **Resolved against installed versions and never against downloadable ones.** That is the feature
 * spec's word, and the reason is that the alternative is a `cd` into a directory silently
 * downloading eighty megabytes. What a constraint matching nothing produces is a message naming the
 * install command.
 */
export type VersionConstraint = string;
