// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnswerSubject } from "./AnswerSubject";
import type { MismatchAnswer } from "./MismatchAnswer";

/**
 * One version question, answered.
 */
export type VersionAnswer = { 
/**
 * What the question was about.
 */
subject: AnswerSubject, 
/**
 * What to do about it.
 */
answer: MismatchAnswer, };
