// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeKind } from "./RuntimeKind";
import type { VersionConstraint } from "./VersionConstraint";

/**
 * What a `web-app` would serve.
 */
export type WebAppSummary = { 
/**
 * The document root, rendered.
 */
root: string, 
/**
 * The label its internal domain is built from.
 */
domain: string, 
/**
 * Which language it needs.
 */
runtime: RuntimeKind, 
/**
 * Which versions of it will do.
 *
 * **MixEngine picks inside this**, and deliberately not the user's project: an administrative
 * interface that broke because somebody pinned their project to an older PHP would be a tool
 * that fails exactly when it is needed.
 */
requires: VersionConstraint, };
