// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What walking into a cap does to the service.
 *
 * **Reported rather than left to be assumed**, because the two endings need different words in
 * front of a person: a program handed a failed allocation usually says something first, and one the
 * kernel kills says nothing at all. A client that offered "limit to 512 MB" without saying which of
 * the two happens would be telling half the truth.
 */
export type WhenExceeded = "allocation_fails" | "killed";
