//! Whether this home stops services nobody is using — roadmap task **T167b**, ADR 0041.
//!
//! **Off unless a person turned it on.** While it is off, a service whose `idle_minutes` is `NULL`
//! gets its recipe's `idle_default()` (which is [`None`] for every recipe), so nothing is
//! idle-stopped. While it is on, that service gets its recipe's `idle_when_saving()` instead. A
//! service somebody gave a number keeps it either way, and `0` stays *never*.
//!
//! **A row in `settings`, not a key in `config.toml`**, because it is changed from a running window
//! and `config.toml` is read once when the daemon starts. The idle sweep rebuilds its graph from the
//! rows on every pass, so a change reaches the next sweep with nothing regenerated by hand. An
//! absent row or one this build cannot read means off — the reading that never stops a site.

use crate::{Result, store::Store, updates::records};

/// The `settings` key.
pub const KEY: &str = "services.save_resources";

/// Whether the home is saving resources.
///
/// # Errors
///
/// [`Error::Database`](crate::Error::Database) when the table cannot be read.
pub async fn get(store: &Store) -> Result<bool> {
    Ok(records::get::<bool>(store, KEY).await?.unwrap_or(false))
}

/// Turn it on or off.
///
/// # Errors
///
/// [`Error::Database`](crate::Error::Database) when the row cannot be written.
pub async fn set(store: &Store, on: bool) -> Result<()> {
    records::set(store, KEY, &on).await
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn off_until_turned_on_and_back() {
        let directory = tempfile::tempdir().expect("a temporary directory");
        let store = Store::open(&directory.path().join(crate::paths::DATABASE_FILE_NAME))
            .await
            .expect("a database");

        assert!(
            !get(&store).await.unwrap(),
            "a home that never chose saves nothing"
        );

        set(&store, true).await.unwrap();
        assert!(get(&store).await.unwrap());

        set(&store, false).await.unwrap();
        assert!(!get(&store).await.unwrap());
    }
}
