// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScaffoldConsent } from "./ScaffoldConsent";
import type { VersionAnswer } from "./VersionAnswer";

/**
 * `blueprint.apply` — what applying one would do, and doing it.
 */
export type BlueprintApply = { 
/**
 * Which blueprint, by slug.
 */
blueprint: string, 
/**
 * What the new project is called, and what `{project}` expands to.
 */
project: string, 
/**
 * Where it would live. Absolute; the client resolves it against its own current directory.
 */
root: string, 
/**
 * Whether to stop after planning.
 *
 * `true` answers [`BlueprintApplyResponse::Planned`](crate::BlueprintApplyResponse) and touches
 * nothing; `false` answers the job carrying the plan out. One method for both, because the plan
 * a person reads and the plan the daemon executes have to be the same list.
 */
dry_run: boolean, 
/**
 * The answers to the version questions this plan raises — roadmap task **T78**.
 *
 * **A question is asked by a client and answered in the request**, because a daemon has no
 * keyboard: a job that stopped halfway to ask one would be a job holding a project directory
 * hostage. An apply meeting a [`Disposition::Choice`](crate::Disposition) with no answer here
 * is refused before anything happens, naming every question it could not answer — and an
 * answer to a question this plan does not ask is refused too, because it is an answer composed
 * against a machine or a moment that has since changed.
 *
 * Defaulted, so a request written before this task still decodes.
 */
answers?: Array<VersionAnswer>, 
/**
 * Agreement to run the blueprint's own `[scaffold]` command — roadmap task **T78a**, its
 * design's D4.
 *
 * **Asked by a client and answered here**, exactly as a version mismatch is, and for the same
 * reason: a daemon has no keyboard, and a job that stopped halfway to ask would be a job
 * holding a project directory hostage.
 *
 * Absent, and the scaffold step ends `NotRun` while everything else is applied — a blueprint
 * must not become worthless because nobody answered one question. Present and disagreeing with
 * the plan, and the apply is refused before anything happens.
 */
scaffold?: ScaffoldConsent | null, 
/**
 * Whether to plan a front end where this home has none — roadmap task **T115**.
 *
 * `core::sites` renders nothing for a home with no front end and succeeds while doing it, so a
 * manifest with a `[site]` applied to a fresh machine ends with a project, a database, a site
 * row, a domain, a certificate — and nothing listening.
 *
 * **Asked for rather than always.** An apply is about a project; provisioning the machine it
 * runs on is a wider thing, and doing it unasked would make every apply on a home with no web
 * server download one — including the ones deliberately about something else. The caller that
 * sets this is the one whose sentence is *get me a working site*.
 *
 * A home that has already chosen a front end — Nginx as much as Caddy — is left alone whatever
 * this says: the question is whether there is one at all, and a blueprint may not name which,
 * because exactly one runs per home and the choice is the home's.
 *
 * Defaulted, so a request written before this task still decodes and still means what it did.
 */
front_end: boolean, };
