// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiskCategory } from "./DiskCategory";
import type { Reclaim } from "./Reclaim";

/**
 * One category, what it weighs, and what would take it back.
 */
export type CategoryUsage = { 
/**
 * A stable name for it, which a client renders and a test asserts on.
 */
id: DiskCategory, 
/**
 * Where it actually is, which `[paths]` may have moved out of the root.
 */
location: string, 
/**
 * **Apparent** bytes — what `ls -l` and Explorer's *Size* column say, not blocks allocated.
 *
 * Stated here because it is the figure somebody will compare against `du`, which says the other
 * one.
 */
bytes: number, 
/**
 * Regular files counted, symbolic links included as themselves.
 */
files: number, 
/**
 * Whether it can be reclaimed and by what.
 */
reclaim: Reclaim, 
/**
 * Set when part of it could not be read, so [`bytes`](Self::bytes) is a floor and not a total.
 *
 * **A note and never an error.** A `[paths]` override onto a disk that is not mounted, or a
 * directory an old install left unreadable, must not cost the whole answer — the same
 * distinction `daemon.bundle` draws between an omission and an empty member.
 */
unreadable?: string | null, };
