// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cleanup } from "./Cleanup";
import type { DiskCategory } from "./DiskCategory";

/**
 * One reclaimable category, and what became of it.
 */
export type Cleaned = { 
/**
 * Which one. Only [`DiskCategory::Logs`] and [`DiskCategory::Cache`] ever appear.
 */
id: DiskCategory, 
/**
 * Where it is, for a person.
 */
location: string, 
/**
 * What became of it.
 */
outcome: Cleanup, };
