// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What became of one reclaimable category.
 *
 * **Internally tagged**, for [`Reclaim`]'s reason.
 */
export type Cleanup = { "cleanup": "empty", } | { "cleanup": "reclaimed", 
/**
 * Files removed.
 */
files: number, 
/**
 * Apparent bytes reclaimed.
 */
bytes: number, } | { "cleanup": "partial", 
/**
 * Files removed.
 */
files: number, 
/**
 * Apparent bytes reclaimed.
 */
bytes: number, 
/**
 * Files that would not go.
 */
left_behind: number, 
/**
 * What the machine said about the first of them — one reason, because a directory that will
 * not empty gives the same one for every file in it.
 */
because: string, } | { "cleanup": "kept", 
/**
 * Why it was left, in a sentence.
 */
because: string, } | { "cleanup": "failed", 
/**
 * What the machine said.
 */
because: string, };
