// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `daemon.cleanup` takes.
 *
 * **Two negative flags and no list**, on [`UninstallQuery`](crate::UninstallQuery)'s idiom: `{}` is
 * the complete cleanup, and there is no field in which `data` or `runtimes` could be spelled at
 * all. A validator refusing them would be a refusal that can be forgotten in a later edit; a field
 * that does not exist cannot be.
 */
export type CleanupQuery = { 
/**
 * Leave the rotated log files where they are.
 */
keep_logs: boolean, 
/**
 * Leave the download cache where it is.
 */
keep_cache: boolean, };
