// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cleaned } from "./Cleaned";

/**
 * What a cleanup took, and what it did not.
 */
export type CleanupReport = { 
/**
 * One entry per reclaimable category, in a fixed order, whatever each answered.
 *
 * Two of them, always: [`DiskCategory::Logs`] and [`DiskCategory::Cache`]. A row appears even
 * when it was kept or had nothing to take, on [`UninstallReport`](crate::UninstallReport)'s
 * rule — a report that printed only what it removed would leave somebody unable to tell *"there
 * were no rotated logs"* from *"the logs were not looked at"*.
 */
items: Array<Cleaned>, };
