// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandSource } from "./CommandSource";

/**
 * One command in `<root>/bin`, and what put it there.
 */
export type CommandOrigin = { 
/**
 * The command, spelled as the file in `bin/` is named.
 */
command: string, 
/**
 * Where it came from.
 */
source: CommandSource, };
