// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeKind } from "./RuntimeKind";

/**
 * The three things that can put a name in `<root>/bin`.
 */
export type CommandSource = { "from": "built_in", } | { "from": "client", 
/**
 * Which package's recipe declared it.
 */
package: string, } | { "from": "global", 
/**
 * Which language's version resolution decides which copy of it runs.
 */
kind: RuntimeKind, };
