// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A command name more than one installed package claimed.
 */
export type CommandConflict = { 
/**
 * The contested command.
 */
command: string, 
/**
 * The package whose program `bin/` fronts under it.
 */
won: string, 
/**
 * The packages that also claimed it, in the order the tie-break rejected them.
 */
lost: Array<string>, };
