// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SecretAddress } from "./SecretAddress";
import type { ServiceId } from "./ServiceId";

/**
 * `database.credentials` — the password held for one account, read from this machine's
 * credential store. Roadmap task **T77b**.
 *
 * **The one exception to this module's own rule.** Every other type here answers *where* a
 * credential is; this answers *what it is*, because its whole purpose is to put a stored password
 * somewhere a person can paste it — into a project's `.env`, most of all. See
 * `docs/superpowers/specs/2026-09-06-t77b-a-password-a-person-can-read-and-choose-design.md`'s D2.
 */
export type DatabaseCredentials = { 
/**
 * Which instance.
 */
service: ServiceId, 
/**
 * The account this password signs in as.
 */
user: string, 
/**
 * Where it lives in this machine's credential store — the same address a `DatabaseAccount`
 * or a `DatabaseHandoff` would have named for the same account.
 */
secret: SecretAddress, 
/**
 * The password itself. Never printed by [`std::fmt::Debug`] — see the hand-written impl
 * below.
 */
password: string, };
