// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceId } from "./ServiceId";

/**
 * `database.credentials` — the password held for one account. Reads only. Roadmap task **T77b**.
 */
export type DatabaseCredentialsQuery = { 
/**
 * Which instance: `mariadb@main`, `postgres@shop`.
 */
service: ServiceId, 
/**
 * The account to read. The server's administrator when nobody says — `database.open`'s own
 * default, for the same reason: the two commands are one question asked by a process and by
 * a person.
 */
user?: string | null, };
