// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a database could be opened, as a state — roadmap tasks **T83** and **T165**.
 *
 * **Two answers, and neither is an error.** A client renders `no_client` as an absent affordance
 * with a sentence beside it; an error would be rendered as a failure of something the person did.
 */
export type DesktopClient = { "state": "installed", 
/**
 * Its display name: `MixLab`.
 */
name: string, 
/**
 * The executable this machine would start.
 */
program: string, } | { "state": "no_client" };
