// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CategoryUsage } from "./CategoryUsage";
import type { Timestamp } from "./Timestamp";

/**
 * Where this home's disk has gone.
 */
export type DiskUsage = { 
/**
 * `MIXENGINE_HOME`, for a person to read.
 *
 * A `String` and not a `PathBuf` for [`DaemonStatus`](crate::DaemonStatus)' reason — serde
 * refuses a `PathBuf` that is not valid UTF-8. A category `[paths]` has moved is **not** under
 * it, which is what [`CategoryUsage::location`] is for.
 */
root: string, 
/**
 * When the walk this answer comes from happened.
 *
 * On the answer rather than implied by the call, because the answer may be up to a minute old
 * — see [`DiskUsageQuery::refresh`].
 */
measured_at: Timestamp, 
/**
 * Exactly five, in [`DiskCategory::ALL`]'s order, whatever each answered.
 */
categories: Array<CategoryUsage>, 
/**
 * Everything else this home holds: `bin/`, `etc/`, `packages/`, `extensions/`, `blueprints/`,
 * `run/`, the database with its write-ahead log, and `config.toml`.
 *
 * **Dominated by `packages/`** — nginx, MariaDB, Redis — on any home with a database installed.
 * That is a compromise rather than a conclusion: `packages/` is reclaimable through
 * `package.uninstall`, which [`Reclaim::ByMethod`] could say, and it is in here only because
 * T96's sentence says *five categories*. A sixth is a roadmap edit.
 *
 * Measured from that closed list of directories and not from a walk of whatever happens to be
 * sitting in the home — `daemon.bundle`'s rule (**T93**) applied in the other direction.
 */
other_bytes: number, };
