// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The five things this build measures separately.
 *
 * **Closed rather than a string**, on [`ResidueId`](crate::ResidueId)'s rule: a client keying off a
 * spelling is a client that silently stops matching, and a row nothing produces does not compile.
 */
export type DiskCategory = "runtimes" | "data" | "logs" | "certs" | "cache";
