// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a machine runs the build it was offered — roadmap task **T92**.
 *
 * A fact about the *pair* of a machine and an artifact rather than about either alone, computed by
 * the daemon out of the index and the target triple it was compiled for, and reported so that a
 * person is never surprised by it.
 *
 * **One enum rather than two**, unlike [`PackageChannel`] directly above: that one mirrors a word
 * the *published document* owns and the two are allowed to move apart. Nothing about this one is
 * written in any document — it is derived, and there is no second vocabulary for it to drift from.
 */
export type Execution = "native" | "emulated";
