// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `extension.available` asks for.
 *
 * Every field has a default, so `{}` is a question a person can type —
 * [`RuntimeFilter`](crate::RuntimeFilter)'s rule.
 */
export type ExtensionAvailable = { 
/**
 * Ask the registry again even if the cached copy is still fresh —
 * [`RuntimeFilter::refresh`](crate::RuntimeFilter::refresh)'s reason, for the registry's own
 * `mixengine_core::index::Client` rather than the package index's.
 */
refresh?: boolean, };
