// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceWalk } from "./ServiceWalk";

/**
 * The five ends a switch can have — roadmap task **T97**.
 */
export type FrontEndOutcome = { "outcome": "unchanged", } | { "outcome": "switched", 
/**
 * The walk that brought the new front end up, and [`None`] when the old one was not
 * running and nothing was started in its place.
 *
 * **A switch preserves what it found.** Starting a server somebody had deliberately
 * stopped is the tool overruling its user.
 */
started?: ServiceWalk | null, } | { "outcome": "not_granted", 
/**
 * What the machine said, phrased for a person.
 */
because: string, } | { "outcome": "rolled_back", 
/**
 * What refused, unedited.
 */
because: string, } | { "outcome": "failed", 
/**
 * What went wrong, in the order it went wrong.
 */
because: string, };
