// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrontEndServer } from "./FrontEndServer";
import type { PackageVersion } from "./PackageVersion";

/**
 * What `service.set_front_end` takes — roadmap task **T97**.
 *
 * **Which program, and not which row.** A caller does not name a `ServiceId`, because the id of the
 * service that is about to exist is the recipe's to decide and the one that is about to go is the
 * daemon's to find — see
 * [ADR 0026](https://github.com/mixnz/mixengine/blob/master/.claude/decisions/0026-the-active-front-end-is-a-row-and-switching-it-is-a-job.md).
 */
export type FrontEndSwitch = { 
/**
 * Which program every site on this machine should be reached through from now on.
 *
 * The same value [`ServiceRole::FrontEnd`] reports, which is what makes a switch drawable from
 * a listing and nothing else.
 */
server: FrontEndServer, 
/**
 * Which installed version of it, and the newest installed when absent.
 *
 * **Optional because nobody choosing a web server is choosing a patch release.** A version
 * that is named and not installed is refused; no version installed at all is refused with the
 * install command, because a switch installs nothing.
 */
version?: PackageVersion | null, 
/**
 * Flush the elevation queue in this same call, raising the one prompt.
 *
 * **Defaults to `false`**, on [`UninstallQuery::grant`](crate::UninstallQuery)'s rule and for
 * its reason: what is about to be allowed is read before it is allowed. A switch that needs a
 * grant it was not allowed to raise answers [`FrontEndOutcome::NotGranted`] with the operation
 * left waiting, so allowing it and asking again works.
 */
grant: boolean, };
