// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the privileged helper installed on this machine turned out to be — roadmap task **T88a**.
 *
 * Read by running that helper as an *ordinary* process with a `probe`, so nothing here costs a
 * prompt: `Probe` needs no administrative token, which is what the T40 design's D5 arranged.
 * Absent when nothing is installed, or when the machine would not answer.
 */
export type InstalledHelper = { 
/**
 * Which release it is.
 */
version: string, 
/**
 * The protocol it speaks, which is the ceiling every request to it is marked at.
 */
protocol: number, 
/**
 * Every operation it knows, by wire name — the evidence behind [`upgrade`](Self::upgrade).
 */
supported_ops: Array<string>, 
/**
 * What to do about it being older than this daemon, when it is.
 *
 * Rendered here rather than by a client, on [`PendingOp::description`]'s rule and for its
 * reason: a client deciding what to say about the helper would be a client deciding what runs
 * as root. Since T182b there is nothing for a person to run: the daemon replaces an older
 * helper at the next prompt, and this says so.
 */
upgrade?: string | null, };
