// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RedistributableArch } from "./RedistributableArch";

/**
 * What the machine lacks.
 */
export type Need = { "need": "glibc", 
/**
 * What the artifact was measured to need.
 */
at_least: string, 
/**
 * What this machine has.
 */
found: string, } | { "need": "macos", 
/**
 * What the artifact was measured to need.
 */
at_least: string, 
/**
 * What this machine runs.
 */
found: string, } | { "need": "visual_cpp", 
/**
 * The redistributable year the artifact names — `2019`.
 */
year: string, 
/**
 * Which build of it.
 */
arch: RedistributableArch, 
/**
 * The version present, `14.29`, when one is present and too old.
 */
found?: string | null, } | { "need": "cpu", 
/**
 * The feature the artifact names, as the index spells it — `avx`.
 */
feature: string, } | { "need": "shared_library", 
/**
 * As the index spells it — `libasound.so.2`.
 */
soname: string, };
