// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageVersion } from "./PackageVersion";

/**
 * What `package.install` takes: a version, and what the person agreed to — roadmap task **T149**.
 *
 * [`RuntimeInstall`](crate::RuntimeInstall)'s shape, for the same reason.
 */
export type PackageInstall = { 
/**
 * Install what this version needs of the machine first.
 */
install_prerequisites?: boolean, 
/**
 * Do not judge what this version needs of the machine at all. The smoke test still runs.
 */
ignore_requirements?: boolean, 
/**
 * Which package, by the name a recipe is found under.
 *
 * A plain [`String`] rather than a closed enum: which packages exist is a property of the
 * build, not of the wire, and the daemon holds the set — so a name this build cannot run is
 * refused with the list of the ones it can, which is a better answer than a decode failure.
 */
package: string, 
/**
 * Which version, exactly as the index publishes it.
 */
version: PackageVersion, };
