// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandConflict } from "./CommandConflict";
import type { CommandOrigin } from "./CommandOrigin";
import type { PathPlace } from "./PathPlace";

/**
 * What every `path.*` method answers.
 */
export type PathReport = { 
/**
 * The directory in question: `<root>/bin`, as a string for display.
 */
directory: string, 
/**
 * Whether every place this OS reads a persisted PATH from carries it.
 *
 * **Every one and not any of them** — see [`PathPlace`]. Composed by the daemon rather than
 * left for each client to fold the list itself, which is business logic and a place for two
 * clients to disagree about what "set up" means.
 */
on_path: boolean, 
/**
 * Each of those places, in the order this OS reads them.
 */
places: Array<PathPlace>, 
/**
 * The commands `<root>/bin` answers to, as the files in it are named.
 *
 * Carried by all three methods because it is the other half of the same question: a PATH entry
 * naming a directory with no `php` in it is a PATH entry that does nothing, and the two are
 * set up together (roadmap task T26).
 */
commands: Array<string>, 
/**
 * What was in `<root>/bin` that no command answers to and could not be removed.
 *
 * Empty on every ordinary call. It is here rather than only in the daemon's log because a name
 * left behind is a name on the user's PATH running something this build no longer understands
 * — on Windows, most often a shim a shell in another window is still holding.
 */
stale?: Array<string>, 
/**
 * Where each of those commands came from — roadmap tasks **T130** and **T131**.
 *
 * **Beside [`commands`](Self::commands) rather than replacing it**, because the two answer
 * different questions and only one of them is the old one: `commands` is what `bin/` holds,
 * read off the directory, and this is what MixEngine believes put each name there. A name in
 * one and not the other is itself information — a command with no origin is a copy left behind
 * by something that has since been uninstalled.
 *
 * In `commands`' order, and empty from a build or a client that does not fill it.
 */
origins?: Array<CommandOrigin>, 
/**
 * Commands more than one installed package claimed, and who got each.
 *
 * Empty on nearly every machine: the only conflict this build can produce is a home with both
 * MariaDB and MySQL installed, where `mysql`, `mysqladmin` and `mysqldump` are spellings
 * MariaDB stands in for and MySQL owns outright.
 */
conflicts?: Array<CommandConflict>, };
