// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a category can be reclaimed, and by what.
 *
 * **Four answers for five categories, and the API states them rather than letting a client work
 * them out.** A client that derived *"runtimes go through `runtime.uninstall`"* would be holding a
 * copy of a table the daemon owns — and a cleanup button that deleted a runtime directly would be
 * the back door around **T32**'s refusal to uninstall a runtime under a running pool.
 *
 * **Internally tagged**, so a client matches on a word rather than working out which fields
 * arrived — [`Outcome`](crate::Outcome)'s rule.
 */
export type Reclaim = { "reclaim": "never", 
/**
 * Why not, in a sentence.
 */
because: string, } | { "reclaim": "by_method", 
/**
 * The RPC method that does it, spelled as [`rpc::method`](crate::rpc::method) spells it.
 */
method: string, 
/**
 * What that method refuses, so a client can say why the button may not work.
 */
because: string, } | { "reclaim": "at_a_cost", 
/**
 * What is given up, in a sentence.
 */
because: string, } | { "reclaim": "by_cleanup", 
/**
 * Apparent bytes that would be reclaimed.
 */
bytes: number, 
/**
 * Files that would be removed.
 */
files: number, };
