// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which build of the Microsoft Visual C++ Redistributable.
 */
export type RedistributableArch = "x64" | "arm64";
