// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageVersion } from "./PackageVersion";
import type { RedistributableArch } from "./RedistributableArch";

/**
 * What can be done about one [`Need`].
 */
export type Remedy = { "remedy": "install_visual_cpp", 
/**
 * Which build.
 */
arch: RedistributableArch, } | { "remedy": "choose_version", 
/**
 * That release.
 */
version: PackageVersion, } | { "remedy": "unavailable" };
