// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Need } from "./Need";
import type { Remedy } from "./Remedy";

/**
 * One thing missing, and what can be done about it.
 */
export type Requirement = { 
/**
 * What is missing.
 */
need: Need, 
/**
 * What can be done about it.
 */
remedy: Remedy, };
