// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Requirement } from "./Requirement";

/**
 * What `runtime.requirements` and `package.requirements` answer.
 */
export type Requirements = { 
/**
 * Everything the version lacks here. Empty when it lacks nothing, or nothing could be judged.
 */
unmet: Array<Requirement>, };
