// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceId } from "./ServiceId";

/**
 * Which database's superuser credential to re-set — roadmap task **T127**.
 *
 * **A type of its own rather than [`ServiceTarget`], and T125 is why.** That type's `service` is
 * optional and [`None`] means *every service this home declares* — which is how both clients came
 * to ask for the whole home when they meant one project. A repair asked for with no subject is that
 * mistake with worse consequences, so the subject is a required field and there is nothing left to
 * refuse at run time.
 *
 * There is no `project` either, for the reason `service.stop` refuses one: a project's services
 * include the front end every *other* site is reached through, and none of them but a database
 * keeps a credential to re-set.
 */
export type ResetCredential = { 
/**
 * The database to repair: `mariadb@main`, `postgres@shop`.
 */
service: ServiceId, 
/**
 * Whether to answer when the repair has finished rather than when it has been accepted.
 *
 * [`ServiceTarget::wait`]'s meaning and its default: a GUI that is already subscribed to the
 * events would rather draw the walk arriving than block a window on it.
 */
wait?: boolean, };
