// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageVersion } from "./PackageVersion";
import type { RuntimeKind } from "./RuntimeKind";

/**
 * What `runtime.install` takes: a version, and what the person agreed to — roadmap task **T149**.
 *
 * Flattened on [`RuntimeUninstall`]'s pattern, so a request with neither flag is the
 * [`RuntimeTarget`] every client has always sent.
 */
export type RuntimeInstall = { 
/**
 * Install what this version needs of the machine first — the Microsoft Visual C++
 * Redistributable, on Windows. Without it an install that needs one is refused before its job
 * exists.
 */
install_prerequisites?: boolean, 
/**
 * Do not judge what this version needs of the machine at all. The smoke test still runs.
 */
ignore_requirements?: boolean, 
/**
 * Which language.
 */
kind: RuntimeKind, 
/**
 * Which version, exactly as the index publishes it.
 */
version: PackageVersion, };
