// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which language runtime something is a version of — or, since T27c, which tool that is installed
 * the way a language is.
 *
 * **Closed, unlike [`JobKind`](crate::JobKind) and like [`JobState`](crate::JobState).** The set
 * grows only when MixEngine learns to manage another language, or a tool it installs like one,
 * which is a release of ours and a migration of the `runtime_installs.kind` `CHECK` — never
 * something a package index gets to extend by publishing. An index naming a sixth one is
 * describing something this build could not install a shim for anyway.
 */
export type RuntimeKind = "php" | "node" | "python" | "ruby" | "composer";
