// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether this home stops services nobody is using — `service.save_resources` answers it, and
 * `service.set_save_resources` answers it after changing it. Roadmap task **T167b**.
 *
 * **Off unless a person turned it on** ([ADR 0041]). While it is off, a service whose own idle
 * setting is unset is never stopped for being idle; a service somebody gave a number keeps it.
 *
 * [ADR 0041]: https://github.com/mixnz/mixengine/blob/master/.claude/decisions/0041-mixengine-stops-nothing-a-person-did-not-ask-it-to.md
 */
export type SaveResources = { 
/**
 * Whether the switch is on.
 */
on: boolean, };
