// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `service.set_save_resources` takes.
 */
export type SaveResourcesSet = { 
/**
 * What it should be.
 */
on: boolean, };
