// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectRef } from "./ProjectRef";
import type { ServiceId } from "./ServiceId";

/**
 * Which services a call is about, and whether the caller waits for the answer to be true.
 *
 * One params type for `service.start`, `service.stop` and `service.restart`, because the question
 * each asks is the same one: *which* service, and *how long may this take*.
 */
export type ServiceTarget = { 
/**
 * The service to act on, or [`None`] for every declared service.
 *
 * Naming one does not mean acting on one: a plan is the transitive set, so starting `php-fpm`
 * pulls in what it depends on and stopping `mariadb` pulls in what depends on *it*. What the
 * walk covered comes back in [`ServiceWalk::planned`].
 */
service?: ServiceId | null, 
/**
 * Every service one project needs, instead of one service or all of them — roadmap task
 * **T125**.
 *
 * **What a project needs is the daemon's answer and never a client's.** It is the services its
 * sites declare — `site_service_links`, which is where `blueprint.apply` writes the database
 * and the cache it ensured — plus the php-fpm pool a site names, plus the front end every one
 * of those sites is reached through. A client working that set out for itself would be
 * business logic in a client, and it is why both clients said *every service this home
 * declares* until this task: the question had no answer to ask for.
 *
 * **`service.start` only.** `service.stop` and `service.restart` refuse it, because the set
 * includes the front end: a project-scoped stop that takes down the web server every *other*
 * site is reached through is a machine-wide outage wearing one project's name.
 *
 * Never sent together with [`ServiceTarget::service`] — two subjects in one call is a request
 * nothing can carry out as asked, so it is refused rather than resolved by precedence.
 */
project?: ProjectRef | null, 
/**
 * Whether to answer when the walk has finished rather than when it has been accepted.
 *
 * **Defaults to true, and the exit code is why.** `mix service start db && mix …` is a sentence
 * about the database being up; an answer sent before the walk would make it exit `0` for a
 * service that never came up, and the only way for a client to know better would be to re-derive
 * the verdict from the event stream — the business-logic-in-a-client bug `CLAUDE.md` forbids.
 *
 * A GUI sends `false`: it is already subscribed to
 * [`ServiceStateChanged`](crate::DaemonEvent::ServiceStateChanged) and would rather draw each
 * service arriving than block a window on the slowest one. What comes back then is the plan and
 * [`ServiceWalk::complete`] is `false` — the walk itself carries on inside the daemon.
 */
wait?: boolean, };
