// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceId } from "./ServiceId";

/**
 * What `service.set_autostart` takes: one service, and whether it starts with the daemon.
 *
 * **A `bool` and not an `Option<bool>`.** [`ServiceIdleSet`] has three states because an absent
 * value restores the recipe's own default; no recipe declares an autostart, so there is no third
 * state for one to restore and an option would be a case every client had to decide about for
 * nothing.
 *
 * Roadmap task **T112**.
 */
export type ServiceAutostartSet = { 
/**
 * The service to change.
 */
service: ServiceId, 
/**
 * What it should be.
 */
autostart: boolean, };
