// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceId } from "./ServiceId";
import type { SiteKind } from "./SiteKind";
import type { SiteRef } from "./SiteRef";
import type { SiteState } from "./SiteState";

/**
 * Change what a site is.
 *
 * `domains` and `services` **replace** rather than merge, on [`crate::ProjectUpdate`]'s rule and
 * for its reason: with a merge there is no way to remove one.
 */
export type SiteUpdate = { 
/**
 * Which site.
 */
site: SiteRef, 
/**
 * The domains, replacing the list the site had. The head becomes the primary.
 */
domains?: Array<string> | null, 
/**
 * A new doc root.
 */
doc_root?: string | null, 
/**
 * A new kind, payload and all.
 */
kind?: SiteKind | null, 
/**
 * The services, replacing the links the site had.
 */
services?: Array<ServiceId> | null, 
/**
 * Whether HTTPS is wanted.
 */
https?: boolean | null, 
/**
 * Whether the plaintext address should redirect to the HTTPS one — roadmap task **T98**.
 *
 * `None` leaves it — except that turning `https` off while this is left unset carries it to
 * `false` as well, a site whose `https` this update leaves `false` for any reason refuses
 * `Some(true)` here.
 */
https_redirect?: boolean | null, 
/**
 * Whether the web server should serve it.
 */
state?: SiteState | null, 
/**
 * `.local`, acknowledged.
 */
accept_risky_tld?: boolean, };
