// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who left a service stopped — the wire half of `mixengine-core`'s `StoppedBy`, and of the
 * `services.stopped_by` column it reads.
 */
export type StoppedBy = "never" | "person" | "daemon";
