// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One of the four directories, and whether it is still where the home would put it.
 */
export type StorageDirectory = { 
/**
 * Where it is now, resolved — so a relative `[paths]` value arrives as the directory it names.
 *
 * A `String` and not a `PathBuf` for [`DiskUsage`](crate::DiskUsage)' reason: serde refuses a
 * `PathBuf` that is not valid UTF-8, and this is a document a person reads.
 */
path: string, 
/**
 * Is this outside the home?
 *
 * The same test `daemon.uninstall_plan` uses to decide whether a directory needs a row of its
 * own: what `[paths]` has moved is what does not lie under the root. Stated by the daemon
 * rather than worked out by a client comparing two strings, because a client that got the
 * comparison wrong would draw a home as relocated and offer to move it again.
 */
relocated: boolean, };
