// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StorageChoice } from "./StorageChoice";
import type { StoragePaths } from "./StoragePaths";

/**
 * What `mixengined --storage` prints: where this home's directories are, and whether that is
 * still a question.
 *
 * **It describes a home that may not exist yet.** A machine before its first start has no
 * `config.toml` and no database, and the honest answer for it is the default layout and
 * [`StorageChoice::Free`] — which is also the answer a window needs in order to offer the choice
 * at all. Producing it therefore creates nothing.
 */
export type StorageReport = { 
/**
 * `MIXENGINE_HOME`, for a person to read.
 */
root: string, 
/**
 * Where each of the four is.
 */
paths: StoragePaths, 
/**
 * Whether that can still be changed by a flag.
 */
changeable: StorageChoice, };
