// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the four may still be moved without moving any files.
 *
 * **Internally tagged**, so a client matches on a word rather than working out which fields
 * arrived — [`Reclaim`](crate::Reclaim)'s rule.
 */
export type StorageChoice = { "changeable": "free" } | { "changeable": "taken", 
/**
 * Rows in `runtime_installs`.
 */
runtimes: number, 
/**
 * Rows in `packages`.
 */
packages: number, 
/**
 * Rows in `services`.
 */
services: number, 
/**
 * What is installed, in a sentence — *"3 runtimes and 1 service are installed"*.
 *
 * **The counts as well as the sentence, and neither is derivable from the other here.** A
 * client that had only the sentence could not put a number in a badge, and one that had
 * only the counts would be writing the sentence a second time — which is the thing the
 * daemon owns. The window renders this the way it renders every other sentence the daemon
 * sends, beside labels of its own.
 */
explanation: string, };
