// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StorageDirectory } from "./StorageDirectory";

/**
 * The four directories `[paths]` can move, in the order the configuration file lists them.
 */
export type StoragePaths = { 
/**
 * Installed language runtimes.
 */
runtimes: StorageDirectory, 
/**
 * Installed servers and databases.
 */
packages: StorageDirectory, 
/**
 * Service data — the databases themselves.
 */
data: StorageDirectory, 
/**
 * The daemon's log and the services'.
 */
logs: StorageDirectory, };
