// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What both uninstall methods take.
 *
 * One type for two methods, on [`PathReport`](crate::PathReport)'s precedent: they ask the same
 * question of the same machine and differ only in whether they act on the answer.
 */
export type UninstallQuery = { 
/**
 * Leave `MIXENGINE_HOME` where it is, and undo only what is outside it.
 *
 * **Defaults to `false`**, which is the complete removal the command exists for. The flag is
 * here because a home holds `data/` — the MySQL and Postgres instances somebody may have spent
 * a week filling — and a product whose only exit destroys them is one people do not try in the
 * first place (the T87 design, D10).
 */
keep_home: boolean, 
/**
 * Leave every directory `[paths]` has moved out of the root where it is — roadmap task **T182**.
 *
 * **Its own choice and not part of `keep_home`** (the T182 design, D2): those directories are
 * moved to another disk because they are large, and a person may want the home gone and the
 * databases on the other disk kept, or the reverse. A directory that was never moved lies inside
 * the home and follows `keep_home`.
 */
keep_relocated: boolean, 
/**
 * Flush the elevation queue in this same call, raising the one prompt.
 *
 * **Defaults to `false`**, and ignored by `daemon.uninstall_plan`, which raises nothing. The
 * two-call path is T64's rule: what is about to be allowed is read before it is allowed.
 */
grant: boolean, };
