// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `update.hand_over` takes — roadmap task **T88f**.
 */
export type UpdateHandOver = { 
/**
 * The version the client showed the user, refused if no longer offered, as
 * [`UpdateApply::version`] is.
 */
version: string, };
