// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `update.finish` takes: nothing — roadmap task **T88f**.
 */
export type UpdateFinish = Record<symbol, never>;
