// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The installer a copy of MixEngine is updated with — roadmap task **T88f**.
 */
export type UpdateInstaller = { 
/**
 * What kind: `pkg`.
 */
kind: string, 
/**
 * How big the download is, for this machine.
 */
size: number, };
