// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `update.hand_over` answers: the verified package is open in the installer, and the daemon
 * is still running — roadmap task **T88f**.
 */
export type UpdateHandedOver = { 
/**
 * The version handed over.
 */
version: string, 
/**
 * Where the verified package is. Kept until the update finishes or a newer one is offered.
 */
package: string, 
/**
 * The line that installs [`UpdateHandedOver::package`] without a window, for a person who is
 * not at this Mac's screen: over SSH, the installer opens on the desktop anyway (the T88f
 * readings, M4). Written by the daemon so no client composes it.
 */
command: string, 
/**
 * Whether a software installer opened on this machine's screen — roadmap task **T182b**, D5.
 * `false` on a Linux machine with no desktop session: the package is verified and waiting,
 * and [`UpdateHandedOver::command`] is the only way to install it.
 */
opened: boolean, };
