/**
 * What MySQL's built-in functions take and give back, for the editor to show on hover.
 *
 * Signatures only, no prose. That is a deliberate limit: a sentence explaining each function would
 * have to be written twice — the app is bilingual — and would be a small manual to keep correct,
 * while the signature is the part someone actually stops to check. `SUBSTRING` takes three
 * arguments or two; `DATE_ADD` wants an `INTERVAL` and not a number. Those are the questions asked
 * mid-script.
 *
 * The spellings are MySQL's own, from its manual, so an optional argument reads as `[...]` and a
 * variadic one as `...`. Names are upper-cased keys; MySQL matches a function name regardless of
 * case, so anything looked up here is upper-cased first.
 *
 * This list is the common ground of MySQL 5.7 and 8.x — a few 8.0-only entries are marked. It is
 * not exhaustive and is not meant to be: a name that is not here simply gets no tooltip, which is
 * the same as today.
 */

/** Every function this knows, keyed by its upper-cased name. */
export const MYSQL_FUNCTIONS: Readonly<Record<string, string>> = {
  // Aggregates.
  AVG: "AVG([DISTINCT] expr)",
  BIT_AND: "BIT_AND(expr)",
  BIT_OR: "BIT_OR(expr)",
  BIT_XOR: "BIT_XOR(expr)",
  COUNT: "COUNT([DISTINCT] expr | *)",
  GROUP_CONCAT: "GROUP_CONCAT([DISTINCT] expr [ORDER BY ...] [SEPARATOR str])",
  JSON_ARRAYAGG: "JSON_ARRAYAGG(expr)",
  JSON_OBJECTAGG: "JSON_OBJECTAGG(key, value)",
  MAX: "MAX([DISTINCT] expr)",
  MIN: "MIN([DISTINCT] expr)",
  STD: "STD(expr)",
  STDDEV_POP: "STDDEV_POP(expr)",
  STDDEV_SAMP: "STDDEV_SAMP(expr)",
  SUM: "SUM([DISTINCT] expr)",
  VAR_POP: "VAR_POP(expr)",
  VAR_SAMP: "VAR_SAMP(expr)",

  // Window functions. All of them want an OVER clause; MySQL 8.0 and later only.
  CUME_DIST: "CUME_DIST() OVER (...)",
  DENSE_RANK: "DENSE_RANK() OVER (...)",
  FIRST_VALUE: "FIRST_VALUE(expr) OVER (...)",
  LAG: "LAG(expr [, n [, default]]) OVER (...)",
  LAST_VALUE: "LAST_VALUE(expr) OVER (...)",
  LEAD: "LEAD(expr [, n [, default]]) OVER (...)",
  NTH_VALUE: "NTH_VALUE(expr, n) OVER (...)",
  NTILE: "NTILE(n) OVER (...)",
  PERCENT_RANK: "PERCENT_RANK() OVER (...)",
  RANK: "RANK() OVER (...)",
  ROW_NUMBER: "ROW_NUMBER() OVER (...)",

  // Strings.
  ASCII: "ASCII(str)",
  BIN: "BIN(n)",
  BIT_LENGTH: "BIT_LENGTH(str)",
  CHAR_LENGTH: "CHAR_LENGTH(str)",
  CHARACTER_LENGTH: "CHARACTER_LENGTH(str)",
  CONCAT: "CONCAT(str1, str2, ...)",
  CONCAT_WS: "CONCAT_WS(separator, str1, str2, ...)",
  ELT: "ELT(n, str1, str2, ...)",
  EXPORT_SET: "EXPORT_SET(bits, on, off [, separator [, number_of_bits]])",
  FIELD: "FIELD(str, str1, str2, ...)",
  FIND_IN_SET: "FIND_IN_SET(str, str_list)",
  FORMAT: "FORMAT(x, decimals [, locale])",
  FROM_BASE64: "FROM_BASE64(str)",
  HEX: "HEX(str | n)",
  INSERT: "INSERT(str, pos, len, newstr)",
  INSTR: "INSTR(str, substr)",
  LCASE: "LCASE(str)",
  LEFT: "LEFT(str, len)",
  LENGTH: "LENGTH(str)",
  LOCATE: "LOCATE(substr, str [, pos])",
  LOWER: "LOWER(str)",
  LPAD: "LPAD(str, len, padstr)",
  LTRIM: "LTRIM(str)",
  MAKE_SET: "MAKE_SET(bits, str1, str2, ...)",
  MID: "MID(str, pos, len)",
  OCT: "OCT(n)",
  ORD: "ORD(str)",
  POSITION: "POSITION(substr IN str)",
  QUOTE: "QUOTE(str)",
  REGEXP_INSTR: "REGEXP_INSTR(str, pattern [, pos [, occurrence [, return_option [, match_type]]]])",
  REGEXP_LIKE: "REGEXP_LIKE(str, pattern [, match_type])",
  REGEXP_REPLACE: "REGEXP_REPLACE(str, pattern, replacement [, pos [, occurrence [, match_type]]])",
  REGEXP_SUBSTR: "REGEXP_SUBSTR(str, pattern [, pos [, occurrence [, match_type]]])",
  REPEAT: "REPEAT(str, count)",
  REPLACE: "REPLACE(str, from_str, to_str)",
  REVERSE: "REVERSE(str)",
  RIGHT: "RIGHT(str, len)",
  RPAD: "RPAD(str, len, padstr)",
  RTRIM: "RTRIM(str)",
  SOUNDEX: "SOUNDEX(str)",
  SPACE: "SPACE(n)",
  SUBSTR: "SUBSTR(str, pos [, len])",
  SUBSTRING: "SUBSTRING(str, pos [, len])",
  SUBSTRING_INDEX: "SUBSTRING_INDEX(str, delim, count)",
  TO_BASE64: "TO_BASE64(str)",
  TRIM: "TRIM([[LEADING | TRAILING | BOTH] [remstr] FROM] str)",
  UCASE: "UCASE(str)",
  UNHEX: "UNHEX(str)",
  UPPER: "UPPER(str)",
  WEIGHT_STRING: "WEIGHT_STRING(str [AS {CHAR | BINARY}(n)])",

  // Numbers.
  ABS: "ABS(x)",
  ACOS: "ACOS(x)",
  ASIN: "ASIN(x)",
  ATAN: "ATAN(x)",
  ATAN2: "ATAN2(y, x)",
  CEIL: "CEIL(x)",
  CEILING: "CEILING(x)",
  CONV: "CONV(n, from_base, to_base)",
  COS: "COS(x)",
  COT: "COT(x)",
  CRC32: "CRC32(str)",
  DEGREES: "DEGREES(x)",
  EXP: "EXP(x)",
  FLOOR: "FLOOR(x)",
  LN: "LN(x)",
  LOG: "LOG([base,] x)",
  LOG2: "LOG2(x)",
  LOG10: "LOG10(x)",
  MOD: "MOD(n, m)",
  PI: "PI()",
  POW: "POW(x, y)",
  POWER: "POWER(x, y)",
  RADIANS: "RADIANS(x)",
  RAND: "RAND([seed])",
  ROUND: "ROUND(x [, decimals])",
  SIGN: "SIGN(x)",
  SIN: "SIN(x)",
  SQRT: "SQRT(x)",
  TAN: "TAN(x)",
  TRUNCATE: "TRUNCATE(x, decimals)",

  // Dates and times.
  ADDDATE: "ADDDATE(date, INTERVAL expr unit) | ADDDATE(date, days)",
  ADDTIME: "ADDTIME(expr1, expr2)",
  CONVERT_TZ: "CONVERT_TZ(dt, from_tz, to_tz)",
  CURDATE: "CURDATE()",
  CURRENT_DATE: "CURRENT_DATE",
  CURRENT_TIME: "CURRENT_TIME [(precision)]",
  CURRENT_TIMESTAMP: "CURRENT_TIMESTAMP [(precision)]",
  CURTIME: "CURTIME([precision])",
  DATE: "DATE(expr)",
  DATE_ADD: "DATE_ADD(date, INTERVAL expr unit)",
  DATE_FORMAT: "DATE_FORMAT(date, format)",
  DATE_SUB: "DATE_SUB(date, INTERVAL expr unit)",
  DATEDIFF: "DATEDIFF(expr1, expr2)",
  DAY: "DAY(date)",
  DAYNAME: "DAYNAME(date)",
  DAYOFMONTH: "DAYOFMONTH(date)",
  DAYOFWEEK: "DAYOFWEEK(date)",
  DAYOFYEAR: "DAYOFYEAR(date)",
  EXTRACT: "EXTRACT(unit FROM date)",
  FROM_DAYS: "FROM_DAYS(n)",
  FROM_UNIXTIME: "FROM_UNIXTIME(unix_timestamp [, format])",
  GET_FORMAT: "GET_FORMAT({DATE | TIME | DATETIME}, {'EUR' | 'USA' | 'JIS' | 'ISO' | 'INTERNAL'})",
  HOUR: "HOUR(time)",
  LAST_DAY: "LAST_DAY(date)",
  LOCALTIME: "LOCALTIME [(precision)]",
  LOCALTIMESTAMP: "LOCALTIMESTAMP [(precision)]",
  MAKEDATE: "MAKEDATE(year, dayofyear)",
  MAKETIME: "MAKETIME(hour, minute, second)",
  MICROSECOND: "MICROSECOND(expr)",
  MINUTE: "MINUTE(time)",
  MONTH: "MONTH(date)",
  MONTHNAME: "MONTHNAME(date)",
  NOW: "NOW([precision])",
  PERIOD_ADD: "PERIOD_ADD(period, months)",
  PERIOD_DIFF: "PERIOD_DIFF(period1, period2)",
  QUARTER: "QUARTER(date)",
  SEC_TO_TIME: "SEC_TO_TIME(seconds)",
  SECOND: "SECOND(time)",
  STR_TO_DATE: "STR_TO_DATE(str, format)",
  SUBDATE: "SUBDATE(date, INTERVAL expr unit) | SUBDATE(date, days)",
  SUBTIME: "SUBTIME(expr1, expr2)",
  SYSDATE: "SYSDATE([precision])",
  TIME: "TIME(expr)",
  TIME_FORMAT: "TIME_FORMAT(time, format)",
  TIME_TO_SEC: "TIME_TO_SEC(time)",
  TIMEDIFF: "TIMEDIFF(expr1, expr2)",
  TIMESTAMP: "TIMESTAMP(expr [, time])",
  TIMESTAMPADD: "TIMESTAMPADD(unit, interval, datetime)",
  TIMESTAMPDIFF: "TIMESTAMPDIFF(unit, datetime1, datetime2)",
  TO_DAYS: "TO_DAYS(date)",
  TO_SECONDS: "TO_SECONDS(expr)",
  UNIX_TIMESTAMP: "UNIX_TIMESTAMP([date])",
  UTC_DATE: "UTC_DATE()",
  UTC_TIME: "UTC_TIME([precision])",
  UTC_TIMESTAMP: "UTC_TIMESTAMP([precision])",
  WEEK: "WEEK(date [, mode])",
  WEEKDAY: "WEEKDAY(date)",
  WEEKOFYEAR: "WEEKOFYEAR(date)",
  YEAR: "YEAR(date)",
  YEARWEEK: "YEARWEEK(date [, mode])",

  // Choosing between things.
  COALESCE: "COALESCE(value, ...)",
  GREATEST: "GREATEST(value1, value2, ...)",
  IF: "IF(condition, then, else)",
  IFNULL: "IFNULL(expr1, expr2)",
  INTERVAL: "INTERVAL(n, n1, n2, ...)",
  ISNULL: "ISNULL(expr)",
  LEAST: "LEAST(value1, value2, ...)",
  NULLIF: "NULLIF(expr1, expr2)",
  STRCMP: "STRCMP(expr1, expr2)",

  // Casting.
  BINARY: "BINARY expr",
  CAST: "CAST(expr AS type)",
  CONVERT: "CONVERT(expr, type) | CONVERT(expr USING charset)",

  // JSON. MySQL 5.7 and later.
  JSON_ARRAY: "JSON_ARRAY(value, ...)",
  JSON_ARRAY_APPEND: "JSON_ARRAY_APPEND(json, path, value, ...)",
  JSON_ARRAY_INSERT: "JSON_ARRAY_INSERT(json, path, value, ...)",
  JSON_CONTAINS: "JSON_CONTAINS(target, candidate [, path])",
  JSON_CONTAINS_PATH: "JSON_CONTAINS_PATH(json, {'one' | 'all'}, path, ...)",
  JSON_DEPTH: "JSON_DEPTH(json)",
  JSON_EXTRACT: "JSON_EXTRACT(json, path, ...)",
  JSON_INSERT: "JSON_INSERT(json, path, value, ...)",
  JSON_KEYS: "JSON_KEYS(json [, path])",
  JSON_LENGTH: "JSON_LENGTH(json [, path])",
  JSON_MERGE_PATCH: "JSON_MERGE_PATCH(json1, json2, ...)",
  JSON_MERGE_PRESERVE: "JSON_MERGE_PRESERVE(json1, json2, ...)",
  JSON_OBJECT: "JSON_OBJECT(key, value, ...)",
  JSON_OVERLAPS: "JSON_OVERLAPS(json1, json2)",
  JSON_PRETTY: "JSON_PRETTY(json)",
  JSON_QUOTE: "JSON_QUOTE(str)",
  JSON_REMOVE: "JSON_REMOVE(json, path, ...)",
  JSON_REPLACE: "JSON_REPLACE(json, path, value, ...)",
  JSON_SEARCH: "JSON_SEARCH(json, {'one' | 'all'}, search [, escape [, path, ...]])",
  JSON_SET: "JSON_SET(json, path, value, ...)",
  JSON_TABLE: "JSON_TABLE(expr, path COLUMNS (...)) AS alias",
  JSON_TYPE: "JSON_TYPE(json)",
  JSON_UNQUOTE: "JSON_UNQUOTE(json)",
  JSON_VALID: "JSON_VALID(value)",

  // Encryption, hashing and compression.
  AES_DECRYPT: "AES_DECRYPT(crypt_str, key [, iv])",
  AES_ENCRYPT: "AES_ENCRYPT(str, key [, iv])",
  COMPRESS: "COMPRESS(str)",
  MD5: "MD5(str)",
  RANDOM_BYTES: "RANDOM_BYTES(len)",
  SHA1: "SHA1(str)",
  SHA2: "SHA2(str, hash_length)",
  UNCOMPRESS: "UNCOMPRESS(str)",
  UNCOMPRESSED_LENGTH: "UNCOMPRESSED_LENGTH(str)",

  // What the server and the session are.
  BENCHMARK: "BENCHMARK(count, expr)",
  CHARSET: "CHARSET(str)",
  COERCIBILITY: "COERCIBILITY(str)",
  COLLATION: "COLLATION(str)",
  CONNECTION_ID: "CONNECTION_ID()",
  CURRENT_ROLE: "CURRENT_ROLE()",
  CURRENT_USER: "CURRENT_USER",
  DATABASE: "DATABASE()",
  FOUND_ROWS: "FOUND_ROWS()",
  LAST_INSERT_ID: "LAST_INSERT_ID([expr])",
  ROW_COUNT: "ROW_COUNT()",
  SCHEMA: "SCHEMA()",
  SESSION_USER: "SESSION_USER()",
  SYSTEM_USER: "SYSTEM_USER()",
  USER: "USER()",
  VERSION: "VERSION()",

  // Identifiers and locks.
  BIT_COUNT: "BIT_COUNT(n)",
  GET_LOCK: "GET_LOCK(name, timeout)",
  INET_ATON: "INET_ATON(expr)",
  INET_NTOA: "INET_NTOA(expr)",
  INET6_ATON: "INET6_ATON(expr)",
  INET6_NTOA: "INET6_NTOA(expr)",
  IS_FREE_LOCK: "IS_FREE_LOCK(name)",
  IS_USED_LOCK: "IS_USED_LOCK(name)",
  IS_UUID: "IS_UUID(str)",
  RELEASE_ALL_LOCKS: "RELEASE_ALL_LOCKS()",
  RELEASE_LOCK: "RELEASE_LOCK(name)",
  SLEEP: "SLEEP(seconds)",
  UUID: "UUID()",
  UUID_SHORT: "UUID_SHORT()",
  UUID_TO_BIN: "UUID_TO_BIN(uuid [, swap_flag])",
  BIN_TO_UUID: "BIN_TO_UUID(binary_uuid [, swap_flag])",

  // Full-text search.
  MATCH: "MATCH (col, ...) AGAINST (expr [IN {NATURAL LANGUAGE | BOOLEAN} MODE])",
};

/** The signature for a function of this name, or null when it is not one this knows. */
export function functionSignature(name: string): string | null {
  return MYSQL_FUNCTIONS[name.toUpperCase()] ?? null;
}
